PORT: "9080"
FRONTEND_URL: "https://frontend.example.com"
BACKEND_UPSTREAM: "backend:8080"
AGENT_UPSTREAM: "agent:8000"
JWT_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExhyKJmlGOYsCV1OV1ZF1yhVuPwcd\nL38DeWGLWil9mK+2nEzDbwLYWnDMZRlNTDRWDBtfIOPQ2F5FKuKlTBTZew==\n-----END PUBLIC KEY-----"
OTEL_EXPORTER_OTLP_ENDPOINT: ""
TZ: "Asia/Shanghai"
