package endusergraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	appEnduser "modelcraft/internal/app/enduser"
	"modelcraft/internal/interfaces/graphql/enduser/generated"
	"modelcraft/pkg/bizerrors"
	"modelcraft/pkg/ctxutils"
	"time"
)

// Me 返回当前认证 end-user 的 meta/user 资料。
// orgName 由中间件从 URL 路径注入，不通过 GraphQL 输入暴露。
func (r *queryResolver) Me(ctx context.Context) (*generated.TuserFindOneResult, error) {
	requestID := ctxutils.GetRequestID(ctx)
	start := time.Now()

	if r.MetaUserService == nil {
		return metaUserInvalidInputResult(requestID, start, "meta user service not initialized"), nil
	}

	dto, err := r.MetaUserService.GetMe(ctx)
	if err != nil {
		return mapMetaUserError(requestID, start, err), nil
	}
	if dto == nil {
		return metaUserInvalidInputResult(requestID, start, "user not found"), nil
	}

	return &generated.TuserFindOneResult{
		Item:     toTuser(dto),
		TimeCost: int32(time.Since(start).Milliseconds()),
		ReqID:    requestID,
	}, nil
}

// FindOne 按唯一条件（id 或 username）查询单个用户。
// orgName 由中间件注入，不通过 GraphQL 输入暴露。
func (r *queryResolver) FindOne(ctx context.Context, where generated.TuserUniqueWhereInput) (*generated.TuserFindOneResult, error) {
	requestID := ctxutils.GetRequestID(ctx)
	start := time.Now()

	if r.MetaUserService == nil {
		return metaUserInvalidInputResult(requestID, start, "meta user service not initialized"), nil
	}

	orgName, _ := ctxutils.GetOrgNameFromContext(ctx)
	if orgName == "" {
		return metaUserInvalidInputResult(requestID, start, "org context required"), nil
	}
	if where.ID == nil && where.Username == nil {
		return metaUserInvalidInputResult(requestID, start, "id or username is required"), nil
	}

	cmd := appEnduser.MetaUserFindOneCommand{OrgName: orgName}
	if where.ID != nil {
		cmd.ID = *where.ID
	}
	if where.Username != nil {
		cmd.Username = *where.Username
	}

	dto, err := r.MetaUserService.FindOne(ctx, cmd)
	if err != nil {
		return mapMetaUserError(requestID, start, err), nil
	}

	return &generated.TuserFindOneResult{
		Item:     toTuser(dto),
		TimeCost: int32(time.Since(start).Milliseconds()),
		ReqID:    requestID,
	}, nil
}

// FindMany 按受限条件查询用户列表。
// 白名单字段：id、username、createdAt；排序字段：createdAt；take<=50；skip<=1000。
// orgName 由中间件注入，不通过 GraphQL 输入暴露。
func (r *queryResolver) FindMany(ctx context.Context, where *generated.TuserWhereInput, orderBy []*generated.TuserOrderByInput, skip *int32, take *int32) (*generated.TuserFindManyResult, error) {
	requestID := ctxutils.GetRequestID(ctx)
	start := time.Now()

	if r.MetaUserService == nil {
		return &generated.TuserFindManyResult{
			Items:    []*generated.Tuser{},
			TimeCost: 0,
			ReqID:    requestID,
		}, nil
	}

	orgName, _ := ctxutils.GetOrgNameFromContext(ctx)
	if orgName == "" {
		return nil, bizerrors.NewErrorFromContext(ctx, bizerrors.EndUserParamInvalid, "org context required")
	}

	cmd := appEnduser.MetaUserFindManyCommand{OrgName: orgName}

	if skip != nil {
		cmd.Skip = int(*skip)
	}
	if take != nil {
		cmd.Take = int(*take)
	}

	// 映射 where 条件
	if where != nil {
		cmd.Where = buildMetaUserFilter(where)
	}

	// 映射 orderBy
	for _, ob := range orderBy {
		if ob == nil {
			continue
		}
		field := appEnduser.MetaUserOrderByField{}
		if ob.CreatedAt != nil {
			dir := string(*ob.CreatedAt)
			field.CreatedAt = &dir
		} else {
			return nil, bizerrors.NewErrorFromContext(ctx, bizerrors.EndUserParamInvalid,
				"unsupported orderBy field: only createdAt is allowed")
		}
		cmd.OrderBy = append(cmd.OrderBy, field)
	}

	result, err := r.MetaUserService.FindMany(ctx, cmd)
	if err != nil {
		return nil, err
	}

	items := make([]*generated.Tuser, 0, len(result.Items))
	for _, dto := range result.Items {
		items = append(items, toTuser(dto))
	}

	return &generated.TuserFindManyResult{
		Items:    items,
		TimeCost: int32(time.Since(start).Milliseconds()),
		ReqID:    requestID,
	}, nil
}
