package endusergraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	appmodeldesign "modelcraft/internal/app/modeldesign"
	"modelcraft/internal/domain/modeldesign"
	"modelcraft/internal/interfaces/graphql/enduser/generated"
	"modelcraft/pkg/bizerrors"
	"modelcraft/pkg/ctxutils"
)

// Model is the resolver for the model field.
func (r *queryResolver) Model(ctx context.Context, id string) (*generated.EndUserGetModelPayload, error) {
	requestID := ctxutils.GetRequestID(ctx)

	orgName, _ := ctxutils.GetOrgNameFromContext(ctx)
	projectSlug, _ := ctxutils.GetProjectSlugFromContext(ctx)
	if orgName == "" || projectSlug == "" {
		return &generated.EndUserGetModelPayload{
			Error: generated.InvalidInput{Message: "organization and project context required"},
		}, nil
	}
	if id == "" {
		return &generated.EndUserGetModelPayload{
			Error: generated.InvalidInput{Message: "id is required"},
		}, nil
	}

	modelEntity, err := r.ModelDesignService.GetModelByID(ctx, id, appmodeldesign.NewGetModelOptions())
	if err != nil {
		bizErr, ok := err.(*bizerrors.BusinessError)
		if !ok {
			return &generated.EndUserGetModelPayload{
				Error: generated.InvalidInput{Message: fmt.Sprintf("internal server error (requestId: %s)", requestID)},
			}, nil
		}

		switch bizErr.Info().GetCode() {
		case bizerrors.ModelNotFound.Code, bizerrors.NotFound.Code:
			return &generated.EndUserGetModelPayload{
				Error: generated.EndUserModelNotFound{Message: bizErr.Msg()},
			}, nil
		case bizerrors.ProjectNotFound.Code:
			return &generated.EndUserGetModelPayload{
				Error: generated.ProjectNotFound{Message: bizErr.Msg()},
			}, nil
		default:
			return &generated.EndUserGetModelPayload{
				Error: generated.InvalidInput{Message: bizErr.Msg()},
			}, nil
		}
	}

	generator := modeldesign.NewJSONSchemaGenerator()
	schemaJSON, err := generator.GenerateSchema(modelEntity)
	if err != nil {
		return nil, fmt.Errorf("failed to generate JSON schema for model %s: %w", id, err)
	}

	fields := make([]*generated.EndUserField, 0, len(modelEntity.Fields))
	for _, field := range modelEntity.Fields {
		if field == nil {
			continue
		}
		fields = append(fields, &generated.EndUserField{
			Name:         field.Name,
			IsDeprecated: field.IsDeprecated,
		})
	}

	return &generated.EndUserGetModelPayload{
		Model: &generated.EndUserModel{
			ID:           modelEntity.ID,
			Name:         modelEntity.ModelName,
			Title:        modelEntity.Title,
			Description:  modelEntity.Description,
			DatabaseName: modelEntity.DatabaseName,
			JSONSchema:   &schemaJSON,
			Fields:       fields,
		},
	}, nil
}
