package orggraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"
	appEnduser "modelcraft/internal/app/enduser"
	"modelcraft/internal/interfaces/graphql/org/generated"
	"modelcraft/pkg/bizerrors"
	"modelcraft/pkg/ctxutils"
	"modelcraft/pkg/logfacade"
	"strings"
)

// CreateEndUser is the resolver for the createEndUser field.
func (r *mutationResolver) CreateEndUser(ctx context.Context, input generated.CreateEndUserInput) (*generated.CreateEndUserPayload, error) {
	if strings.TrimSpace(input.Username) == "" {
		return &generated.CreateEndUserPayload{
			Error: &generated.InvalidInput{Message: "username is required"},
		}, nil
	}
	if strings.TrimSpace(input.Password) == "" {
		return &generated.CreateEndUserPayload{
			Error: &generated.InvalidInput{Message: "password is required"},
		}, nil
	}

	service := r.EndUserMgmtAppService
	if service == nil {
		return &generated.CreateEndUserPayload{
			Error: &generated.InvalidInput{Message: "end-user service not initialized"},
		}, nil
	}

	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return &generated.CreateEndUserPayload{
			Error: &generated.InvalidInput{Message: "orgName not found in context"},
		}, nil
	}

	projectSlug := ""
	if slug, slugErr := ctxutils.GetProjectSlugFromContext(ctx); slugErr == nil {
		projectSlug = slug
	}

	createdBy, _ := ctxutils.GetTenantUserIDFromContext(ctx)
	result, err := service.CreateEndUser(ctx, appEnduser.CreateEndUserCommand{
		OrgName:     orgName,
		ProjectSlug: projectSlug,
		Username:    input.Username,
		Password:    input.Password,
		CreatedBy:   createdBy,
	})
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			logger := logfacade.GetLogger(ctx)
			logger.Error(ctx, "failed to create end user",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.CreateEndUserPayload{Error: convertOrgCreateEndUserError(bizErr)}, nil
		}
		return nil, err
	}

	return &generated.CreateEndUserPayload{
		EndUser: &generated.EndUser{
			ID:          result.ID,
			Username:    result.Username,
			IsForbidden: result.IsForbidden,
			IsBuiltin:   false,
			CreatedBy:   nil,
			CreatedAt:   result.CreatedAt,
			UpdatedAt:   result.UpdatedAt,
		},
	}, nil
}

// UpdateEndUserStatus is the resolver for the updateEndUserStatus field.
func (r *mutationResolver) UpdateEndUserStatus(ctx context.Context, input generated.UpdateEndUserStatusInput) (*generated.UpdateEndUserStatusPayload, error) {
	if strings.TrimSpace(input.UserID) == "" {
		return &generated.UpdateEndUserStatusPayload{
			Error: &generated.InvalidInput{Message: "userId is required"},
		}, nil
	}

	service := r.EndUserMgmtAppService
	if service == nil {
		return &generated.UpdateEndUserStatusPayload{
			Error: &generated.InvalidInput{Message: "end-user service not initialized"},
		}, nil
	}

	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return &generated.UpdateEndUserStatusPayload{
			Error: &generated.InvalidInput{Message: "orgName not found in context"},
		}, nil
	}

	projectSlug := ""
	if slug, slugErr := ctxutils.GetProjectSlugFromContext(ctx); slugErr == nil {
		projectSlug = slug
	}

	result, err := service.UpdateEndUserStatus(ctx, appEnduser.UpdateEndUserStatusCommand{
		OrgName:     orgName,
		ProjectSlug: projectSlug,
		UserID:      input.UserID,
		IsForbidden: input.IsForbidden,
	})
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			logger := logfacade.GetLogger(ctx)
			logger.Error(ctx, "failed to update end user status",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.UpdateEndUserStatusPayload{Error: convertOrgUpdateEndUserError(bizErr)}, nil
		}
		return nil, err
	}

	return &generated.UpdateEndUserStatusPayload{
		EndUser: &generated.EndUser{
			ID:          result.ID,
			Username:    result.Username,
			IsForbidden: result.IsForbidden,
			IsBuiltin:   false,
			CreatedBy:   nil,
			CreatedAt:   result.CreatedAt,
			UpdatedAt:   result.UpdatedAt,
		},
	}, nil
}

// DeleteEndUser is the resolver for the deleteEndUser field.
func (r *mutationResolver) DeleteEndUser(ctx context.Context, input generated.DeleteEndUserInput) (*generated.DeleteEndUserPayload, error) {
	if strings.TrimSpace(input.UserID) == "" {
		return &generated.DeleteEndUserPayload{
			Success: false,
			Error:   &generated.ResourceNotFound{Message: "userId is required", ResourceType: generated.ResourceTypeEndUser},
		}, nil
	}

	service := r.EndUserMgmtAppService
	if service == nil {
		return &generated.DeleteEndUserPayload{
			Success: false,
			Error:   &generated.ResourceNotFound{Message: "end-user service not initialized", ResourceType: generated.ResourceTypeEndUser},
		}, nil
	}

	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return &generated.DeleteEndUserPayload{
			Success: false,
			Error:   &generated.ResourceNotFound{Message: "orgName not found in context", ResourceType: generated.ResourceTypeEndUser},
		}, nil
	}

	projectSlug := ""
	if slug, slugErr := ctxutils.GetProjectSlugFromContext(ctx); slugErr == nil {
		projectSlug = slug
	}

	err = service.DeleteEndUser(ctx, appEnduser.DeleteEndUserCommand{
		OrgName:     orgName,
		ProjectSlug: projectSlug,
		UserID:      input.UserID,
	})
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			logger := logfacade.GetLogger(ctx)
			logger.Error(ctx, "failed to delete end user",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.DeleteEndUserPayload{
				Success: false,
				Error:   convertOrgDeleteEndUserError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.DeleteEndUserPayload{Success: true}, nil
}

// ResetEndUserPassword is the resolver for the resetEndUserPassword field.
func (r *mutationResolver) ResetEndUserPassword(ctx context.Context, input generated.ResetEndUserPasswordInput) (*generated.ResetEndUserPasswordPayload, error) {
	if strings.TrimSpace(input.UserID) == "" {
		return &generated.ResetEndUserPasswordPayload{
			Error: &generated.InvalidInput{Message: "userId is required"},
		}, nil
	}
	if strings.TrimSpace(input.NewPassword) == "" {
		return &generated.ResetEndUserPasswordPayload{
			Error: &generated.InvalidInput{Message: "newPassword is required"},
		}, nil
	}

	service := r.EndUserMgmtAppService
	if service == nil {
		return &generated.ResetEndUserPasswordPayload{
			Error: &generated.InvalidInput{Message: "end-user service not initialized"},
		}, nil
	}

	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return &generated.ResetEndUserPasswordPayload{
			Error: &generated.InvalidInput{Message: "orgName not found in context"},
		}, nil
	}

	err = service.ResetEndUserPassword(ctx, appEnduser.ResetEndUserPasswordCommand{
		OrgName:     orgName,
		UserID:      input.UserID,
		NewPassword: input.NewPassword,
	})
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			logger := logfacade.GetLogger(ctx)
			logger.Error(ctx, "failed to reset end user password",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.ResetEndUserPasswordPayload{
				Error: convertOrgResetEndUserPasswordError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.ResetEndUserPasswordPayload{Success: true}, nil
}

// ListEndUsers is the resolver for the listEndUsers field.
func (r *queryResolver) ListEndUsers(ctx context.Context, input *generated.ListEndUsersInput) (*generated.ListEndUsersPayload, error) {
	service := r.EndUserMgmtAppService
	if service == nil {
		return &generated.ListEndUsersPayload{
			Error: &generated.InvalidInput{Message: "end-user service not initialized"},
		}, nil
	}

	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return &generated.ListEndUsersPayload{
			Error: &generated.InvalidInput{Message: "orgName not found in context"},
		}, nil
	}

	projectSlug := ""
	if slug, slugErr := ctxutils.GetProjectSlugFromContext(ctx); slugErr == nil {
		projectSlug = slug
	}

	cmd := appEnduser.ListEndUsersCommand{OrgName: orgName, ProjectSlug: projectSlug}
	if input != nil {
		if input.Search != nil {
			cmd.Search = *input.Search
		}
		if input.First != nil {
			if *input.First <= 0 {
				return &generated.ListEndUsersPayload{
					Error: &generated.InvalidInput{Message: "first must be greater than 0"},
				}, nil
			}
			cmd.First = int(*input.First)
		}
		if input.After != nil {
			cmd.After = *input.After
		}
	}

	result, err := service.ListEndUsers(ctx, cmd)
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			logger := logfacade.GetLogger(ctx)
			logger.Error(ctx, "failed to list end users",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.ListEndUsersPayload{Error: convertOrgListEndUsersError(bizErr)}, nil
		}
		return nil, err
	}

	nodes := make([]*generated.EndUser, 0, len(result.Items))
	for _, item := range result.Items {
		nodes = append(nodes, &generated.EndUser{
			ID:          item.ID,
			Username:    item.Username,
			IsForbidden: item.IsForbidden,
			IsBuiltin:   false,
			CreatedBy:   nil,
			CreatedAt:   item.CreatedAt,
			UpdatedAt:   item.UpdatedAt,
		})
	}

	pageInfo := &generated.PageInfo{
		HasNextPage:     result.HasNextPage,
		HasPreviousPage: input != nil && input.After != nil && *input.After != "",
	}
	if len(nodes) > 0 {
		start := nodes[0].ID
		end := nodes[len(nodes)-1].ID
		pageInfo.StartCursor = &start
		pageInfo.EndCursor = &end
	}

	return &generated.ListEndUsersPayload{
		Connection: &generated.EndUserConnection{
			Nodes:      nodes,
			PageInfo:   pageInfo,
			TotalCount: int32(result.TotalCount),
		},
	}, nil
}

// FindUsers is the resolver for the findUsers field.
func (r *queryResolver) FindUsers(ctx context.Context, where *generated.UserWhereInput, after *string, first *int32) (*generated.UserFindManyResult, error) {
	reqID := ctxutils.GetRequestID(ctx)

	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil || orgName == "" {
		return nil, newGQLError("organization context required", "MISSING_ORGANIZATION")
	}

	cmd := appEnduser.MetaUserFindManyCommand{
		OrgName: orgName,
	}
	if after != nil {
		cmd.After = *after
	}
	if first != nil {
		cmd.First = int(*first)
	}
	if where != nil {
		cmd.Where = convertUserWhereInput(where)
	}

	result, err := r.MetaUserAppService.FindMany(ctx, cmd)
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			return nil, newGQLError(bizErr.Msg(), bizErr.Info().GetCode())
		}
		return nil, err
	}

	items := make([]*generated.EndUserPublic, 0, len(result.Items))
	for _, dto := range result.Items {
		items = append(items, &generated.EndUserPublic{
			ID:        dto.ID,
			Username:  dto.Username,
			IsBuiltin: false,
			CreatedAt: dto.CreatedAt,
		})
	}

	var nextCursor *string
	if result.NextCursor != "" {
		nextCursor = &result.NextCursor
	}

	return &generated.UserFindManyResult{
		Items:      items,
		NextCursor: nextCursor,
		HasMore:    result.HasMore,
		ReqID:      reqID,
	}, nil
}

// EndUserProjects is the resolver for the endUserProjects field.
func (r *queryResolver) EndUserProjects(ctx context.Context) ([]*generated.Project, error) {
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return nil, bizerrors.NewError(bizerrors.ParamInvalid, "organization context required")
	}

	userID, err := ctxutils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, bizerrors.NewError(bizerrors.ParamInvalid, "user context required")
	}

	service := r.EndUserMgmtAppService
	if service == nil {
		return nil, bizerrors.NewError(bizerrors.ParamInvalid, "end-user service not initialized")
	}

	projects, err := service.ListAccessibleProjects(ctx, orgName, userID)
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			return nil, newGQLError(bizErr.Msg(), bizErr.Info().GetCode())
		}
		return nil, err
	}

	result := make([]*generated.Project, 0, len(projects))
	for _, p := range projects {
		status := generated.ProjectStatusActive
		if p.Status == "archived" {
			status = generated.ProjectStatusArchived
		}
		result = append(result, &generated.Project{
			ID:          p.Slug,
			Slug:        p.Slug,
			Title:       p.Title,
			Description: p.Description,
			Status:      status,
			OrgName:     orgName,
			AuthSchema:  &generated.ProjectAuthSchema{Variables: []*generated.AuthVariable{}},
			CreatedAt:   p.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
			UpdatedAt:   p.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
		})
	}
	return result, nil
}
