package orggraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"modelcraft/internal/interfaces/graphql/org/generated"
	"time"
)

// CreateEndUserAPIToken is the resolver for the createEndUserAPIToken field.
func (r *mutationResolver) CreateEndUserAPIToken(ctx context.Context, name string, expiresAt *time.Time) (*generated.CreateAPITokenPayload, error) {
	panic(fmt.Errorf("not implemented: CreateEndUserAPIToken - createEndUserAPIToken"))
}

// RevokeEndUserAPIToken is the resolver for the revokeEndUserAPIToken field.
func (r *mutationResolver) RevokeEndUserAPIToken(ctx context.Context, id string) (*generated.RevokeAPITokenPayload, error) {
	panic(fmt.Errorf("not implemented: RevokeEndUserAPIToken - revokeEndUserAPIToken"))
}

// EndUserAPITokens is the resolver for the endUserAPITokens field.
func (r *queryResolver) EndUserAPITokens(ctx context.Context) ([]*generated.EndUserAPIToken, error) {
	panic(fmt.Errorf("not implemented: EndUserAPITokens - endUserAPITokens"))
}
