package orggraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	appPermission "modelcraft/internal/app/permission"
	"modelcraft/internal/interfaces/graphql/org/generated"
	"modelcraft/pkg/bizerrors"
)

// CreateCustomRole is the resolver for the createCustomRole field.
func (r *mutationResolver) CreateCustomRole(ctx context.Context, input generated.CreateCustomRoleInput) (*generated.CreateCustomRolePayload, error) {
	role, err := r.RoleService.CreateCustomRole(ctx, &appPermission.CreateCustomRoleInput{
		Name: input.Name,
		Description: func() string {
			if input.Description == nil {
				return ""
			}
			return *input.Description
		}(),
		OrgName: input.OrgName,
	})
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.CreateCustomRolePayload{
				Error: convertToCreateCustomRoleError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.CreateCustomRolePayload{
		Role: convertRoleToGraphQL(role),
	}, nil
}

// UpdatePermissionRole is the resolver for the updatePermissionRole field.
func (r *mutationResolver) UpdatePermissionRole(ctx context.Context, roleID int32, input generated.UpdateRoleInput) (*generated.UpdatePermissionRolePayload, error) {
	role, err := r.RoleService.UpdateRole(ctx, int(roleID), &appPermission.UpdateRoleInput{
		Name: func() string {
			if input.Name == nil {
				return ""
			}
			return *input.Name
		}(),
		Description: func() string {
			if input.Description == nil {
				return ""
			}
			return *input.Description
		}(),
	})
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.UpdatePermissionRolePayload{
				Error: convertToUpdateRoleError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.UpdatePermissionRolePayload{
		Role: convertRoleToGraphQL(role),
	}, nil
}

// DeletePermissionRole is the resolver for the deletePermissionRole field.
func (r *mutationResolver) DeletePermissionRole(ctx context.Context, roleID int32) (*generated.DeletePermissionRolePayload, error) {
	err := r.RoleService.DeleteRole(ctx, int(roleID))
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.DeletePermissionRolePayload{
				Success: false,
				Error:   convertToDeleteRoleError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.DeletePermissionRolePayload{
		Success: true,
	}, nil
}

// AddPermissionToRole is the resolver for the addPermissionToRole field.
func (r *mutationResolver) AddPermissionToRole(ctx context.Context, roleID int32, obj string, act string) (*generated.AddRolePermissionPayload, error) {
	err := r.PermissionService.AddPermissionToRole(ctx, int(roleID), obj, act)
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.AddRolePermissionPayload{
				Success: false,
				Error:   convertToRolePermissionError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.AddRolePermissionPayload{
		Success: true,
	}, nil
}

// RemovePermissionFromRole is the resolver for the removePermissionFromRole field.
func (r *mutationResolver) RemovePermissionFromRole(ctx context.Context, roleID int32, obj string, act string) (*generated.RemoveRolePermissionPayload, error) {
	err := r.PermissionService.RemovePermissionFromRole(ctx, int(roleID), obj, act)
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.RemoveRolePermissionPayload{
				Success: false,
				Error:   convertToRolePermissionError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.RemoveRolePermissionPayload{
		Success: true,
	}, nil
}

// AssignRoleToUser is the resolver for the assignRoleToUser field.
func (r *mutationResolver) AssignRoleToUser(ctx context.Context, userID string, roleID int32, orgName string) (*generated.AssignRolePayload, error) {
	err := r.UserRoleService.AssignRoleToUser(ctx, userID, int(roleID), orgName)
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.AssignRolePayload{
				Error: convertToAssignRoleError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.AssignRolePayload{
		UserRole: nil, // Could populate this but not required
	}, nil
}

// RevokeRoleFromUser is the resolver for the revokeRoleFromUser field.
func (r *mutationResolver) RevokeRoleFromUser(ctx context.Context, userID string, roleID int32, orgName string) (*generated.RevokeRolePayload, error) {
	err := r.UserRoleService.RevokeRoleFromUser(ctx, userID, int(roleID), orgName)
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.RevokeRolePayload{
				Success: false,
				Error:   convertToRevokeRoleError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.RevokeRolePayload{
		Success: true,
	}, nil
}

// PermissionRoles is the resolver for the permissionRoles field.
func (r *queryResolver) PermissionRoles(ctx context.Context, orgName string, includeSystem *bool) ([]*generated.PermissionRole, error) {
	include := false
	if includeSystem != nil {
		include = *includeSystem
	}

	roles, err := r.RoleService.ListRoles(ctx, orgName, include)
	if err != nil {
		return nil, err
	}

	return convertRolesToGraphQL(roles), nil
}

// PermissionRole is the resolver for the permissionRole field.
func (r *queryResolver) PermissionRole(ctx context.Context, id int32) (*generated.PermissionRole, error) {
	role, err := r.RoleService.GetRole(ctx, int(id))
	if err != nil {
		return nil, err
	}

	return convertRoleToGraphQL(role), nil
}

// UserRoleAssignments is the resolver for the userRoleAssignments field.
func (r *queryResolver) UserRoleAssignments(ctx context.Context, userID string, orgName string) ([]*generated.UserRoleAssignment, error) {
	userRoles, err := r.UserRoleService.ListUserRoles(ctx, userID, orgName)
	if err != nil {
		return nil, err
	}

	return convertUserRolesToGraphQL(userRoles), nil
}

// RolePermissionsList is the resolver for the rolePermissionsList field.
func (r *queryResolver) RolePermissionsList(ctx context.Context, roleID int32) ([]*generated.PermissionDef, error) {
	perms, err := r.PermissionService.ListRolePermissions(ctx, int(roleID))
	if err != nil {
		return nil, err
	}

	return convertPermissionsToGraphQL(perms), nil
}
