package orggraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	clusterApp "modelcraft/internal/app/cluster"
	appProject "modelcraft/internal/app/project"
	domainCluster "modelcraft/internal/domain/cluster"
	"modelcraft/internal/domain/project"
	"modelcraft/internal/interfaces/graphql/org/adapter"
	"modelcraft/internal/interfaces/graphql/org/generated"
	"modelcraft/pkg/bizerrors"
	"modelcraft/pkg/bizutils"
	"modelcraft/pkg/ctxutils"
	"modelcraft/pkg/logfacade"
	"time"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input generated.CreateProjectInput) (*generated.CreateProjectPayload, error) {
	errorAdapter := adapter.NewProjectErrorAdapter(ctx)
	logger := logfacade.GetLogger(ctx)

	// Extract organization name from context
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return nil, bizerrors.NewError(bizerrors.ParamInvalid, "organization context required")
	}

	// Build command with embedded cluster input
	cmd := appProject.CreateProjectCommand{
		OrgName:     orgName,
		Slug:        input.Slug,
		Title:       input.Title,
		Description: bizutils.SafeString(input.Description),
	}
	if input.ClusterInput != nil {
		ci := input.ClusterInput
		cmd.ClusterInput = appProject.CreateClusterForProjectInput{
			Title: ci.Title,
		}
		if ci.Description != nil {
			cmd.ClusterInput.Description = *ci.Description
		}
		if ci.ConnectionInfo != nil {
			cmd.ClusterInput.Host = ci.ConnectionInfo.Host
			cmd.ClusterInput.Port = int(ci.ConnectionInfo.Port)
			cmd.ClusterInput.Username = ci.ConnectionInfo.Username
			cmd.ClusterInput.Password = ci.ConnectionInfo.Password
			if ci.ConnectionInfo.ConnectionTimeout != nil {
				cmd.ClusterInput.ConnectionTimeout = int(*ci.ConnectionInfo.ConnectionTimeout)
			}
		}
	}
	if input.SkipConnectionTest != nil {
		cmd.SkipConnectionTest = *input.SkipConnectionTest
	}

	// Create project (atomically with cluster)
	proj, err := r.ProjectAppService.CreateProject(ctx, cmd)
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			logger.Error(ctx, "Failed to create project",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			gqlError := errorAdapter.ConvertToCreateProjectErrors(bizErr)
			return &generated.CreateProjectPayload{
				Project: nil,
				Error:   gqlError,
			}, nil
		}
		return nil, err
	}

	return &generated.CreateProjectPayload{
		Project: adapter.ProjectMapper.ConvertProjectToGraphQL(proj),
		Error:   nil,
	}, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, input generated.UpdateProjectInput) (*generated.UpdateProjectPayload, error) {
	errorAdapter := adapter.NewProjectErrorAdapter(ctx)

	// Extract organization name from context
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return nil, bizerrors.NewError(bizerrors.ParamInvalid, "organization context required")
	}

	// Build command
	cmd := appProject.UpdateProjectCommand{
		OrgName:     orgName,
		Slug:        input.Slug,
		Title:       bizutils.SafeString(input.Title),
		Description: bizutils.SafeString(input.Description),
	}

	// Update project
	proj, err := r.ProjectAppService.UpdateProjectMetadata(ctx, cmd)
	// Convert business errors to typed GraphQL errors
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			gqlError := errorAdapter.ConvertToUpdateProjectErrors(bizErr)
			return &generated.UpdateProjectPayload{
				Project: nil,
				Error:   gqlError,
			}, nil
		}
		// For non-business errors, still throw as GraphQL error
		return nil, err
	}

	// Success case
	return &generated.UpdateProjectPayload{
		Project: adapter.ProjectMapper.ConvertProjectToGraphQL(proj),
		Error:   nil,
	}, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, slug string) (*generated.DeleteProjectPayload, error) {
	errorAdapter := adapter.NewProjectErrorAdapter(ctx)

	// Extract organization name from context
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return nil, bizerrors.NewError(bizerrors.ParamInvalid, "organization context required")
	}

	// Build command
	cmd := appProject.DeleteProjectCommand{
		OrgName: orgName,
		Slug:    slug,
	}

	// Delete project
	err = r.ProjectAppService.DeleteProject(ctx, cmd)
	// Convert business errors to typed GraphQL errors
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			gqlError := errorAdapter.ConvertToDeleteProjectErrors(bizErr)
			return &generated.DeleteProjectPayload{
				Success: false,
				Error:   gqlError,
			}, nil
		}
		// For non-business errors, still throw as GraphQL error
		return nil, err
	}

	// Success case
	return &generated.DeleteProjectPayload{
		Success: true,
		Error:   nil,
	}, nil
}

// UpdateProjectCluster is the resolver for the updateProjectCluster field.
func (r *mutationResolver) UpdateProjectCluster(ctx context.Context, projectSlug string, input generated.UpdateClusterConnectionInput) (*generated.UpdateClusterPayload, error) {
	clusterMapper := adapter.NewClusterMapper()
	errorAdapter := adapter.NewClusterErrorAdapter(ctx)
	logger := logfacade.GetLogger(ctx)

	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return nil, bizerrors.NewError(bizerrors.ParamInvalid, "organization context required")
	}

	cmd := clusterMapper.ToUpdateProjectClusterCommand(orgName, projectSlug, input)
	clusterEntity, err := r.ClusterAppService.UpdateProjectCluster(ctx, cmd)
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			logger.Error(ctx, "Failed to update project cluster",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.UpdateClusterPayload{
				Cluster: nil,
				Error:   errorAdapter.ConvertToUpdateClusterError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.UpdateClusterPayload{
		Cluster: clusterMapper.ToGraphQLCluster(clusterEntity),
		Error:   nil,
	}, nil
}

// TestDatabaseConnection is the resolver for the testDatabaseConnection field.
func (r *mutationResolver) TestDatabaseConnection(ctx context.Context, input generated.TestDatabaseConnectionInput) (*generated.TestConnectionPayload, error) {
	errorAdapter := adapter.NewClusterErrorAdapter(ctx)

	// projectSlug is optional in this API:
	// 1) project not created yet: test with raw connectionInfo only (no cluster lookup)
	// 2) project exists: optionally provide projectSlug to reuse stored cluster password
	projectSlug := ""
	if input.ProjectSlug != nil {
		projectSlug = *input.ProjectSlug
	}

	// Build the test command from the request connection info.
	// When password is the server sentinel, app layer should fallback to persisted password,
	// which requires loading existing cluster by project.
	var testCmd *clusterApp.TestConnectionCommand
	useStoredPassword := false
	if input.ConnectionInfo != nil {
		password := input.ConnectionInfo.Password
		useStoredPassword = password == domainCluster.EncryptedByServerPlaceholder
		if useStoredPassword {
			password = ""
		}
		cmd := clusterApp.TestConnectionCommand{
			Username: input.ConnectionInfo.Username,
			Password: password,
			Host:     input.ConnectionInfo.Host,
			Port:     int(input.ConnectionInfo.Port),
		}
		if input.ConnectionInfo.ConnectionTimeout != nil {
			ct := int(*input.ConnectionInfo.ConnectionTimeout)
			cmd.ConnectionTimeout = &ct
		}
		testCmd = &cmd
	}

	// Resolve cluster only when needed:
	// - no connectionInfo (test existing project cluster)
	// - using stored password placeholder (needs fallback password)
	needClusterByProject := input.ConnectionInfo == nil || useStoredPassword
	var clusterID *string
	if needClusterByProject {
		if projectSlug == "" {
			bizErr := bizerrors.NewErrorFromContext(
				ctx,
				bizerrors.ParamInvalid,
				"projectSlug is required when connectionInfo is absent or uses stored password",
			)
			return &generated.TestConnectionPayload{
				Success:        false,
				ConnectionTime: nil,
				Error:          errorAdapter.ConvertToTestConnectionError(bizErr),
			}, nil
		}

		existingCluster, err := r.ClusterAppService.GetClusterByProject(ctx, projectSlug)
		if err != nil {
			if bizErr, ok := err.(*bizerrors.BusinessError); ok {
				return &generated.TestConnectionPayload{
					Success:        false,
					ConnectionTime: nil,
					Error:          errorAdapter.ConvertToTestConnectionError(bizErr),
				}, nil
			}
			return nil, err
		}
		clusterID = &existingCluster.ID
	}

	// 测量连接时间
	start := time.Now()
	err := r.ClusterAppService.TestConnection(ctx, projectSlug, clusterID, testCmd)
	connectionTime := float64(time.Since(start).Nanoseconds()) / 1e6 // 转换为毫秒

	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.TestConnectionPayload{
				Success:        false,
				ConnectionTime: &connectionTime,
				Error:          errorAdapter.ConvertToTestConnectionError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.TestConnectionPayload{
		Success:        true,
		ConnectionTime: &connectionTime,
		Error:          nil,
	}, nil
}

// SetProjectAuthSchema is the resolver for the setProjectAuthSchema field (deprecated, no-op).
func (r *mutationResolver) SetProjectAuthSchema(ctx context.Context, input generated.SetProjectAuthSchemaInput) (*generated.SetProjectAuthSchemaPayload, error) {
	return &generated.SetProjectAuthSchemaPayload{
		AuthSchema: emptyProjectAuthSchema(),
		Error:      nil,
	}, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, slug string) (*generated.GetProjectPayload, error) {
	errorAdapter := adapter.NewProjectErrorAdapter(ctx)

	// Extract organization name from context
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		return nil, bizerrors.NewError(bizerrors.ParamInvalid, "organization context required")
	}

	// Build command
	cmd := appProject.GetProjectCommand{
		OrgName: orgName,
		Slug:    slug,
	}

	// Get project with organization validation
	proj, err := r.ProjectAppService.GetProjectByNameAndOrg(ctx, cmd)
	// Convert business errors to typed GraphQL errors
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			gqlError := errorAdapter.ConvertToGetProjectErrors(bizErr)
			return &generated.GetProjectPayload{
				Project: nil,
				Error:   gqlError,
			}, nil
		}
		// For non-business errors, still throw as GraphQL error
		return nil, err
	}

	// Success case
	return &generated.GetProjectPayload{
		Project: adapter.ProjectMapper.ConvertProjectToGraphQL(proj),
		Error:   nil,
	}, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, input *generated.ListProjectsInput) ([]*generated.Project, error) {
	var result []*generated.Project
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		// Extract organization name from context
		orgName, err := ctxutils.GetOrgNameFromContext(ctx)
		if err != nil {
			return bizerrors.NewError(bizerrors.ParamInvalid, "organization context required")
		}

		// List projects for current organization
		var statusFilter *project.ProjectStatus
		if input != nil && input.Status != nil {
			domainStatus := adapter.ConvertProjectStatusFromGraphQL(*input.Status)
			statusFilter = &domainStatus
		}

		// Build command
		cmd := appProject.ListProjectsCommand{
			OrgName: orgName,
			Status:  statusFilter,
		}

		projects, err := r.ProjectAppService.ListProjectsByOrg(ctx, cmd)
		if err != nil {
			return err
		}

		result = adapter.ProjectMapper.ConvertProjectsToGraphQL(projects)
		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return result, nil
}

// DatabaseCluster is the resolver for the databaseCluster field.
func (r *queryResolver) DatabaseCluster(ctx context.Context, projectSlug string) (*generated.GetClusterPayload, error) {
	clusterMapper := adapter.NewClusterMapper()
	errorAdapter := adapter.NewClusterErrorAdapter(ctx)

	cluster, err := r.ClusterAppService.GetClusterByProject(ctx, projectSlug)
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.GetClusterPayload{
				Cluster: nil,
				Error:   errorAdapter.ConvertToGetClusterError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.GetClusterPayload{
		Cluster: clusterMapper.ToGraphQLCluster(cluster),
		Error:   nil,
	}, nil
}
