// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../../../tmp/tmp.8mSPO84F8u
// gowrap: http://github.com/hexdigest/gowrap

package repository

import (
	"context"
	"database/sql"
	"modelcraft/internal/infrastructure/dbgen"
)

type safeLogicalFKQuerier struct {
	delegate dbgen.Querier
}

var _ logicalFKQuerier = (*safeLogicalFKQuerier)(nil)

func newSafeLogicalFKQuerier(delegate dbgen.Querier) logicalFKQuerier {
	return &safeLogicalFKQuerier{delegate: delegate}
}
func (s *safeLogicalFKQuerier) CreateLogicalForeignKey(ctx context.Context, arg dbgen.CreateLogicalForeignKeyParams) (err error) {
	err = s.delegate.CreateLogicalForeignKey(ctx, arg)
	WrapSQLErrorInPlace(&err)
	return
}
func (s *safeLogicalFKQuerier) DeleteLogicalForeignKeyByPairID(ctx context.Context, pairID string) (err error) {
	err = s.delegate.DeleteLogicalForeignKeyByPairID(ctx, pairID)
	WrapSQLErrorInPlace(&err)
	return
}
func (s *safeLogicalFKQuerier) FindFieldsByBelongsToFKID(ctx context.Context, belongsToFkID sql.NullString) (fa1 []dbgen.FindFieldsByBelongsToFKIDRow, err error) {
	fa1, err = s.delegate.FindFieldsByBelongsToFKID(ctx, belongsToFkID)
	WrapSQLErrorInPlace(&err)
	return
}
func (s *safeLogicalFKQuerier) FindFieldsByRelateFKID(ctx context.Context, relateFkID sql.NullString) (fa1 []dbgen.FindFieldsByRelateFKIDRow, err error) {
	fa1, err = s.delegate.FindFieldsByRelateFKID(ctx, relateFkID)
	WrapSQLErrorInPlace(&err)
	return
}
func (s *safeLogicalFKQuerier) FindLogicalForeignKeysByModelID(ctx context.Context, modelID string) (la1 []dbgen.LogicalForeignKey, err error) {
	la1, err = s.delegate.FindLogicalForeignKeysByModelID(ctx, modelID)
	WrapSQLErrorInPlace(&err)
	return
}
func (s *safeLogicalFKQuerier) FindLogicalForeignKeysByPairID(ctx context.Context, pairID string) (la1 []dbgen.LogicalForeignKey, err error) {
	la1, err = s.delegate.FindLogicalForeignKeysByPairID(ctx, pairID)
	WrapSQLErrorInPlace(&err)
	return
}
func (s *safeLogicalFKQuerier) GetLogicalForeignKeyByID(ctx context.Context, id string) (l1 dbgen.LogicalForeignKey, err error) {
	l1, err = s.delegate.GetLogicalForeignKeyByID(ctx, id)
	WrapSQLErrorInPlace(&err)
	return
}
