'use client'

import { Button } from '@web/components/ui/button'
import { Avatar, AvatarFallback, AvatarImage } from '@web/components/ui/avatar'
import { Card, CardContent, CardHeader, CardTitle } from '@web/components/ui/card'
import { Separator } from '@web/components/ui/separator'
import { Pencil } from 'lucide-react'
import type { UserProfileView } from '@/types'

export interface ProfileOverviewPanelProps {
  profile: UserProfileView
  onEdit: () => void
}

function formatDateTime(dateText: string): string {
  if (!dateText) {
    return '-'
  }

  const parsed = new Date(dateText)
  if (Number.isNaN(parsed.getTime())) {
    return '-'
  }

  return parsed.toLocaleString()
}

const STATUS_LABEL: Record<string, string> = {
  ACTIVE: '正常',
  REGISTERED: '已注册',
  SUSPENDED: '已停用',
}

/** 判断是否是系统自动生成的随机昵称（如 user_KMKQSU） */
function isAutoGeneratedNickname(nickname: string): boolean {
  return /^user_[A-Z0-9]{4,}$/.test(nickname)
}

export function ProfileOverviewPanel({ profile, onEdit }: ProfileOverviewPanelProps) {
  const isAutoNickname = isAutoGeneratedNickname(profile.nickname)
  const displayNickname = isAutoNickname ? profile.userName : profile.nickname
  const fallbackText = displayNickname.slice(0, 1).toUpperCase() || 'U'

  return (
    <Card className="border bg-background">
      <CardHeader className="flex flex-row items-start justify-between gap-4">
        <div className="flex items-center gap-4">
          <Avatar className="size-16">
            {profile.avatarUrl && !profile.avatarUrl.startsWith('mock://') && (
              <AvatarImage src={profile.avatarUrl} alt={displayNickname} />
            )}
            <AvatarFallback className="bg-primary text-lg font-semibold text-primary-foreground">
              {fallbackText}
            </AvatarFallback>
          </Avatar>
          <div className="flex flex-col gap-1">
            <CardTitle className="text-xl font-semibold text-foreground">
              {isAutoNickname ? (
                <span className="italic text-muted-foreground">未设置昵称</span>
              ) : (
                displayNickname
              )}
            </CardTitle>
            <p className="text-sm font-medium text-muted-foreground">@{profile.userName}</p>
            {isAutoNickname && (
              <p className="text-xs text-muted-foreground">点击「编辑资料」完善昵称信息</p>
            )}
          </div>
        </div>

        <Button onClick={onEdit} className="gap-2">
          <Pencil className="size-4" />
          编辑资料
        </Button>
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="grid gap-3 md:grid-cols-2">
          <div className="space-y-1.5">
            <p className="text-sm font-medium text-muted-foreground">手机号</p>
            <p className="text-sm font-medium text-foreground">{profile.phone}</p>
          </div>
          <div className="space-y-1.5">
            <p className="text-sm font-medium text-muted-foreground">账号状态</p>
            <p className="text-sm font-medium text-foreground">
              {STATUS_LABEL[profile.status] ?? profile.status}
            </p>
          </div>
        </div>

        <Separator />

        <div className="space-y-1.5">
          <p className="text-sm font-medium text-muted-foreground">头像地址</p>
          <p className="break-all text-sm font-medium text-foreground">
            {(!profile.avatarUrl || profile.avatarUrl.startsWith('mock://')) ? '未设置' : profile.avatarUrl}
          </p>
        </div>

        <div className="space-y-1.5">
          <p className="text-sm font-medium text-muted-foreground">个人简介</p>
          <p className="text-sm font-medium text-foreground">{profile.bio || '暂无简介'}</p>
        </div>

        <Separator />

        <div className="grid gap-3 md:grid-cols-2">
          <div className="space-y-1.5">
            <p className="text-sm font-medium text-muted-foreground">创建时间</p>
            <p className="text-sm font-medium text-foreground">{formatDateTime(profile.createdAt)}</p>
          </div>
          <div className="space-y-1.5">
            <p className="text-sm font-medium text-muted-foreground">更新时间</p>
            <p className="text-sm font-medium text-foreground">{formatDateTime(profile.updatedAt)}</p>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
