package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"modelcraft/internal/interfaces/graphql/project/generated"
)

// RegisterModelDatabase is the resolver for the registerModelDatabase field.
func (r *mutationResolver) RegisterModelDatabase(ctx context.Context, input generated.RegisterModelDatabaseInput) (generated.RegisterModelDatabaseResult, error) {
	panic(fmt.Errorf("not implemented: RegisterModelDatabase - registerModelDatabase"))
}

// UpdateModelDatabase is the resolver for the updateModelDatabase field.
func (r *mutationResolver) UpdateModelDatabase(ctx context.Context, id string, input generated.UpdateModelDatabaseInput) (*generated.ModelDatabase, error) {
	panic(fmt.Errorf("not implemented: UpdateModelDatabase - updateModelDatabase"))
}

// UnregisterModelDatabase is the resolver for the unregisterModelDatabase field.
func (r *mutationResolver) UnregisterModelDatabase(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnregisterModelDatabase - unregisterModelDatabase"))
}

// ModelDatabases is the resolver for the modelDatabases field.
func (r *queryResolver) ModelDatabases(ctx context.Context) ([]*generated.ModelDatabase, error) {
	panic(fmt.Errorf("not implemented: ModelDatabases - modelDatabases"))
}

// ClusterRawDatabases is the resolver for the clusterRawDatabases field.
func (r *queryResolver) ClusterRawDatabases(ctx context.Context) ([]*generated.RawDatabase, error) {
	panic(fmt.Errorf("not implemented: ClusterRawDatabases - clusterRawDatabases"))
}
