package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	appmodeldatabase "modelcraft/internal/app/modeldatabase"
	"modelcraft/internal/interfaces/graphql/project/generated"
	"modelcraft/pkg/bizerrors"
	"modelcraft/pkg/logfacade"
)

// RegisterModelDatabase is the resolver for the registerModelDatabase field.
func (r *mutationResolver) RegisterModelDatabase(ctx context.Context, input generated.RegisterModelDatabaseInput) (generated.RegisterModelDatabaseResult, error) {
	logger := logfacade.GetLogger(ctx)
	cmd := appmodeldatabase.RegisterCommand{
		Name:        input.Name,
		Title:       input.Title,
		Description: derefStringOrEmpty(input.Description),
		Mode:        gqlDatabaseModeToDomain(input.Mode),
	}
	db, err := r.ModelDatabaseAppService.Register(ctx, cmd)
	if err != nil {
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			logger.With(
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			).Errorf(ctx, nil, "RegisterModelDatabase failed")
			switch bizErr.Info().GetCode() {
			case bizerrors.Conflict.GetCode(), bizerrors.ParamInvalid.GetCode():
				return &generated.InvalidInput{Message: bizErr.Msg()}, nil
			case bizerrors.NotFound.GetCode():
				return &generated.ResourceNotFound{
					Message:      bizErr.Msg(),
					ResourceType: generated.ResourceTypeUnknown,
				}, nil
			}
		}
		return nil, err
	}
	return modelDatabaseToGQL(db), nil
}

// BatchRegisterModelDatabases is the resolver for the batchRegisterModelDatabases field.
func (r *mutationResolver) BatchRegisterModelDatabases(ctx context.Context, input generated.BatchRegisterModelDatabaseInput) (*generated.BatchRegisterModelDatabaseResult, error) {
	cmds := make([]appmodeldatabase.RegisterCommand, 0, len(input.Databases))
	for _, db := range input.Databases {
		cmds = append(cmds, appmodeldatabase.RegisterCommand{
			Name:        db.Name,
			Title:       db.Title,
			Description: derefStringOrEmpty(db.Description),
			Mode:        gqlDatabaseModeToDomain(db.Mode),
		})
	}
	batchResult, err := r.ModelDatabaseAppService.BatchRegister(ctx, cmds)
	if err != nil {
		return nil, err
	}
	succeeded := make([]*generated.ModelDatabase, 0, len(batchResult.Succeeded))
	for _, db := range batchResult.Succeeded {
		succeeded = append(succeeded, modelDatabaseToGQL(db))
	}
	failed := make([]*generated.BatchRegisterError, 0, len(batchResult.Failed))
	for _, f := range batchResult.Failed {
		failed = append(failed, &generated.BatchRegisterError{
			Name:    f.Name,
			Message: f.Message,
		})
	}
	return &generated.BatchRegisterModelDatabaseResult{
		Succeeded: succeeded,
		Failed:    failed,
	}, nil
}

// UpdateModelDatabase is the resolver for the updateModelDatabase field.
func (r *mutationResolver) UpdateModelDatabase(ctx context.Context, id string, input generated.UpdateModelDatabaseInput) (*generated.ModelDatabase, error) {
	cmd := appmodeldatabase.UpdateCommand{
		ID:          id,
		Title:       input.Title,
		Description: input.Description,
		Mode:        domainDatabaseModeFromGQLPtr(input.Mode),
	}
	db, err := r.ModelDatabaseAppService.Update(ctx, cmd)
	if err != nil {
		return nil, err
	}
	return modelDatabaseToGQL(db), nil
}

// UnregisterModelDatabase is the resolver for the unregisterModelDatabase field.
func (r *mutationResolver) UnregisterModelDatabase(ctx context.Context, id string) (bool, error) {
	err := r.ModelDatabaseAppService.Unregister(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// StartModelDatabaseSync is the resolver for the startModelDatabaseSync field.
func (r *mutationResolver) StartModelDatabaseSync(ctx context.Context, databaseID string) (*generated.StartModelDatabaseSyncPayload, error) {
	job, err := r.ModelDatabaseSyncAppService.StartSync(ctx, databaseID)
	if err != nil {
		return nil, err
	}
	return &generated.StartModelDatabaseSyncPayload{Job: modelDatabaseSyncJobToGQL(job)}, nil
}

// ModelDatabases is the resolver for the modelDatabases field.
func (r *queryResolver) ModelDatabases(ctx context.Context) ([]*generated.ModelDatabase, error) {
	items, err := r.ModelDatabaseAppService.ListRegistered(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*generated.ModelDatabase, 0, len(items))
	for _, item := range items {
		result = append(result, modelDatabaseToGQL(item))
	}
	return result, nil
}

// ClusterRawDatabases is the resolver for the clusterRawDatabases field.
func (r *queryResolver) ClusterRawDatabases(ctx context.Context) ([]*generated.RawDatabase, error) {
	items, err := r.ModelDatabaseAppService.ListRaw(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*generated.RawDatabase, 0, len(items))
	for _, item := range items {
		result = append(result, &generated.RawDatabase{
			Name:         item.Name,
			IsRegistered: item.IsRegistered,
		})
	}
	return result, nil
}

// ModelDatabaseSyncJob is the resolver for the modelDatabaseSyncJob field.
func (r *queryResolver) ModelDatabaseSyncJob(ctx context.Context, jobID string) (*generated.ModelDatabaseSyncJob, error) {
	job, err := r.ModelDatabaseSyncAppService.GetJob(ctx, jobID)
	if err != nil || job == nil {
		return nil, err
	}
	return modelDatabaseSyncJobToGQL(job), nil
}
