package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"
	"strings"

	appEnduser "modelcraft/internal/app/enduser"
	"modelcraft/internal/interfaces/graphql/project/generated"
	"modelcraft/pkg/bizerrors"
	"modelcraft/pkg/ctxutils"
	"modelcraft/pkg/logfacade"
)

// GrantEndUserProjectAccess is the resolver for the grantEndUserProjectAccess field.
func (r *mutationResolver) GrantEndUserProjectAccess(ctx context.Context, input generated.GrantEndUserProjectAccessInput) (*generated.GrantEndUserProjectAccessPayload, error) {
	if strings.TrimSpace(input.EndUserID) == "" {
		return &generated.GrantEndUserProjectAccessPayload{
			Error: &generated.InvalidInput{Message: "endUserId is required"},
		}, nil
	}
	if strings.TrimSpace(input.PermissionBundleID) == "" {
		return &generated.GrantEndUserProjectAccessPayload{
			Error: &generated.InvalidInput{Message: "permissionBundleId is required"},
		}, nil
	}

	service := r.EndUserAccessAppService
	if service == nil {
		return &generated.GrantEndUserProjectAccessPayload{
			Error: &generated.InvalidInput{Message: "end-user access service not initialized"},
		}, nil
	}

	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return &generated.GrantEndUserProjectAccessPayload{
			Error: &generated.InvalidInput{Message: err.Error()},
		}, nil
	}

	grantedBy, _ := ctxutils.GetUserIDFromContext(ctx)
	result, err := service.GrantProjectAccess(ctx, appEnduser.GrantEndUserProjectAccessCommand{
		OrgName:            orgName,
		ProjectSlug:        projectSlug,
		EndUserID:          input.EndUserID,
		PermissionBundleID: input.PermissionBundleID,
		GrantedBy:          grantedBy,
	})
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			logger := logfacade.GetLogger(ctx)
			logger.Error(ctx, "failed to grant end-user project access",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.GrantEndUserProjectAccessPayload{
				Error: convertGrantEndUserProjectAccessError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.GrantEndUserProjectAccessPayload{
		Access: toGraphQLEndUserProjectAccess(result),
	}, nil
}

// UpdateEndUserProjectAccess is the resolver for the updateEndUserProjectAccess field.
func (r *mutationResolver) UpdateEndUserProjectAccess(ctx context.Context, input generated.UpdateEndUserProjectAccessInput) (*generated.UpdateEndUserProjectAccessPayload, error) {
	if strings.TrimSpace(input.AccessID) == "" {
		return &generated.UpdateEndUserProjectAccessPayload{
			Error: &generated.InvalidInput{Message: "accessId is required"},
		}, nil
	}
	if strings.TrimSpace(input.PermissionBundleID) == "" {
		return &generated.UpdateEndUserProjectAccessPayload{
			Error: &generated.InvalidInput{Message: "permissionBundleId is required"},
		}, nil
	}

	service := r.EndUserAccessAppService
	if service == nil {
		return &generated.UpdateEndUserProjectAccessPayload{
			Error: &generated.InvalidInput{Message: "end-user access service not initialized"},
		}, nil
	}

	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return &generated.UpdateEndUserProjectAccessPayload{
			Error: &generated.InvalidInput{Message: err.Error()},
		}, nil
	}

	result, err := service.UpdateProjectAccess(ctx, appEnduser.UpdateEndUserProjectAccessCommand{
		OrgName:            orgName,
		ProjectSlug:        projectSlug,
		AccessID:           input.AccessID,
		PermissionBundleID: input.PermissionBundleID,
	})
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			logger := logfacade.GetLogger(ctx)
			logger.Error(ctx, "failed to update end-user project access",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.UpdateEndUserProjectAccessPayload{
				Error: convertUpdateEndUserProjectAccessError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.UpdateEndUserProjectAccessPayload{
		Access: toGraphQLEndUserProjectAccess(result),
	}, nil
}

// RevokeEndUserProjectAccess is the resolver for the revokeEndUserProjectAccess field.
func (r *mutationResolver) RevokeEndUserProjectAccess(ctx context.Context, input generated.RevokeEndUserProjectAccessInput) (*generated.RevokeEndUserProjectAccessPayload, error) {
	if strings.TrimSpace(input.AccessID) == "" {
		return &generated.RevokeEndUserProjectAccessPayload{
			Success: false,
			Error:   &generated.EndUserProjectAccessNotFound{Message: "accessId is required"},
		}, nil
	}

	service := r.EndUserAccessAppService
	if service == nil {
		return &generated.RevokeEndUserProjectAccessPayload{
			Success: false,
			Error:   &generated.EndUserProjectAccessNotFound{Message: "end-user access service not initialized"},
		}, nil
	}

	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return &generated.RevokeEndUserProjectAccessPayload{
			Success: false,
			Error:   &generated.EndUserProjectAccessNotFound{Message: err.Error()},
		}, nil
	}

	err = service.RevokeProjectAccess(ctx, appEnduser.RevokeEndUserProjectAccessCommand{
		OrgName:     orgName,
		ProjectSlug: projectSlug,
		AccessID:    input.AccessID,
	})
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			logger := logfacade.GetLogger(ctx)
			logger.Error(ctx, "failed to revoke end-user project access",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.RevokeEndUserProjectAccessPayload{
				Success: false,
				Error:   convertRevokeEndUserProjectAccessError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.RevokeEndUserProjectAccessPayload{Success: true}, nil
}

// ListProjectEndUserAccess is the resolver for the listProjectEndUserAccess field.
func (r *queryResolver) ListProjectEndUserAccess(ctx context.Context, input *generated.ListProjectEndUserAccessInput) (*generated.ListProjectEndUserAccessPayload, error) {
	service := r.EndUserAccessAppService
	if service == nil {
		return &generated.ListProjectEndUserAccessPayload{
			Error: &generated.InvalidInput{Message: "end-user access service not initialized"},
		}, nil
	}

	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return &generated.ListProjectEndUserAccessPayload{
			Error: &generated.InvalidInput{Message: err.Error()},
		}, nil
	}

	cmd := appEnduser.ListEndUserProjectAccessCommand{OrgName: orgName, ProjectSlug: projectSlug}
	if input != nil {
		if input.Search != nil {
			cmd.Search = *input.Search
		}
		if input.First != nil {
			if *input.First <= 0 {
				return &generated.ListProjectEndUserAccessPayload{
					Error: &generated.InvalidInput{Message: "first must be greater than 0"},
				}, nil
			}
			cmd.First = int(*input.First)
		}
		if input.After != nil {
			cmd.After = *input.After
		}
	}

	result, err := service.ListProjectAccess(ctx, cmd)
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			logger := logfacade.GetLogger(ctx)
			logger.Error(ctx, "failed to list end-user project access",
				logfacade.Err(bizErr),
				logfacade.Stack(bizErr),
			)
			return &generated.ListProjectEndUserAccessPayload{
				Error: convertListProjectEndUserAccessError(bizErr),
			}, nil
		}
		return nil, err
	}

	nodes := make([]*generated.EndUserProjectAccess, 0, len(result.Items))
	for _, item := range result.Items {
		nodes = append(nodes, toGraphQLEndUserProjectAccess(item))
	}

	pageInfo := &generated.PageInfo{
		HasNextPage:     result.HasNextPage,
		HasPreviousPage: input != nil && input.After != nil && *input.After != "",
	}
	if len(nodes) > 0 {
		start := nodes[0].ID
		end := nodes[len(nodes)-1].ID
		pageInfo.StartCursor = &start
		pageInfo.EndCursor = &end
	}

	return &generated.ListProjectEndUserAccessPayload{
		Connection: &generated.EndUserProjectAccessConnection{
			Nodes:      nodes,
			PageInfo:   pageInfo,
			TotalCount: int32(result.TotalCount),
		},
	}, nil
}

func toGraphQLEndUserProjectAccess(access *appEnduser.EndUserProjectAccessDTO) *generated.EndUserProjectAccess {
	if access == nil {
		return nil
	}

	endUser := &generated.EndUser{}
	if access.EndUser != nil {
		endUser = &generated.EndUser{
			ID:          access.EndUser.ID,
			Username:    access.EndUser.Username,
			IsForbidden: access.EndUser.IsForbidden,
			CreatedBy:   access.EndUser.CreatedBy,
			CreatedAt:   access.EndUser.CreatedAt,
			UpdatedAt:   access.EndUser.UpdatedAt,
		}
	}

	return &generated.EndUserProjectAccess{
		ID:                   access.ID,
		EndUser:              endUser,
		PermissionBundleID:   access.PermissionBundleID,
		PermissionBundleName: access.PermissionBundleName,
		GrantedBy:            access.GrantedBy,
		GrantedAt:            access.GrantedAt,
	}
}

func convertGrantEndUserProjectAccessError(err *bizerrors.BusinessError) generated.GrantEndUserProjectAccessError {
	if err == nil {
		return nil
	}

	switch err.Info().GetCode() {
	case bizerrors.EndUserNotFound.GetCode(), bizerrors.EndUserNotFoundInProject.GetCode():
		return &generated.EndUserNotFound{Message: err.Msg()}
	case bizerrors.EndUserPermissionBundleNotFound.GetCode():
		return &generated.EndUserPermissionBundleNotFound{Message: err.Msg()}
	case bizerrors.ProjectNotFound.GetCode():
		return &generated.ProjectNotFound{Message: err.Msg()}
	case bizerrors.Conflict.GetCode():
		return &generated.EndUserProjectAccessAlreadyExists{Message: err.Msg()}
	case bizerrors.ParamInvalid.GetCode(), bizerrors.EndUserParamInvalid.GetCode():
		return &generated.InvalidInput{Message: err.Msg()}
	default:
		return &generated.InvalidInput{Message: err.Msg()}
	}
}

func convertUpdateEndUserProjectAccessError(err *bizerrors.BusinessError) generated.UpdateEndUserProjectAccessError {
	if err == nil {
		return nil
	}

	switch err.Info().GetCode() {
	case bizerrors.NotFound.GetCode():
		return &generated.EndUserProjectAccessNotFound{Message: err.Msg()}
	case bizerrors.EndUserPermissionBundleNotFound.GetCode():
		return &generated.EndUserPermissionBundleNotFound{Message: err.Msg()}
	case bizerrors.ProjectNotFound.GetCode():
		return &generated.ProjectNotFound{Message: err.Msg()}
	case bizerrors.ParamInvalid.GetCode(), bizerrors.EndUserParamInvalid.GetCode():
		return &generated.InvalidInput{Message: err.Msg()}
	default:
		return &generated.InvalidInput{Message: err.Msg()}
	}
}

func convertRevokeEndUserProjectAccessError(err *bizerrors.BusinessError) generated.RevokeEndUserProjectAccessError {
	if err == nil {
		return nil
	}

	switch err.Info().GetCode() {
	case bizerrors.ProjectNotFound.GetCode():
		return &generated.ProjectNotFound{Message: err.Msg()}
	case bizerrors.NotFound.GetCode():
		return &generated.EndUserProjectAccessNotFound{Message: err.Msg()}
	default:
		return &generated.EndUserProjectAccessNotFound{Message: err.Msg()}
	}
}

func convertListProjectEndUserAccessError(err *bizerrors.BusinessError) generated.ListProjectEndUserAccessError {
	if err == nil {
		return nil
	}

	switch err.Info().GetCode() {
	case bizerrors.ProjectNotFound.GetCode():
		return &generated.ProjectNotFound{Message: err.Msg()}
	default:
		return &generated.InvalidInput{Message: err.Msg()}
	}
}
