package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"
	"modelcraft/internal/app/modeldesign"
	domainModeldesign "modelcraft/internal/domain/modeldesign"
	"modelcraft/internal/interfaces/graphql/project/adapter"
	"modelcraft/internal/interfaces/graphql/project/generated"
	"modelcraft/pkg/bizerrors"
	"modelcraft/pkg/bizutils"
	"modelcraft/pkg/ctxutils"
)

// CreateEnum is the resolver for the createEnum field.
func (r *mutationResolver) CreateEnum(ctx context.Context, input generated.CreateEnumInput) (*generated.CreateEnumPayload, error) {
	enumErrorAdapter := adapter.NewEnumErrorAdapter(ctx)

	// Extract projectSlug from context
	projectSlug, err := ctxutils.GetProjectSlugFromContext(ctx)
	if err != nil {
		return &generated.CreateEnumPayload{
			Error: &generated.InvalidInput{Message: "projectSlug not found in context"},
		}, nil
	}

	// Get orgName from context
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		// Use default org if not found in context
		orgName = "modelcraft"
	}

	// Convert input to domain model
	options := make([]domainModeldesign.EnumOption, 0, len(input.Options))
	for _, opt := range input.Options {
		options = append(options, domainModeldesign.EnumOption{
			Code:        opt.Code,
			Label:       opt.Label,
			Order:       opt.Order,
			Description: bizutils.SafeString(opt.Description),
		})
	}

	// Build command
	cmd := modeldesign.CreateEnumCommand{
		OrgName:       orgName,
		ProjectSlug:   projectSlug,
		Name:          input.Name,
		DisplayName:   input.DisplayName,
		Description:   bizutils.SafeString(input.Description),
		Options:       options,
		IsMultiSelect: false,
	}

	// Create enum
	enum, err := r.EnumAppService.CreateEnum(ctx, cmd)
	if err != nil {
		// Convert error to typed GraphQL error
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			return &generated.CreateEnumPayload{
				Enum:  nil,
				Error: enumErrorAdapter.ConvertToCreateEnumError(bizErr),
			}, nil
		}
		return nil, err
	}

	result := adapter.EnumMapper.ConvertEnumDefinitionToGraphQL(enum)
	return &generated.CreateEnumPayload{
		Enum:  result,
		Error: nil,
	}, nil
}

// UpdateEnum is the resolver for the updateEnum field.
func (r *mutationResolver) UpdateEnum(ctx context.Context, name string, input generated.UpdateEnumInput) (*generated.UpdateEnumPayload, error) {
	enumErrorAdapter := adapter.NewEnumErrorAdapter(ctx)

	// Extract projectSlug from context
	projectSlug, err := ctxutils.GetProjectSlugFromContext(ctx)
	if err != nil {
		return &generated.UpdateEnumPayload{
			Error: &generated.InvalidInput{Message: "projectSlug not found in context"},
		}, nil
	}

	// Get orgName from context
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		// Use default org if not found in context
		orgName = "modelcraft"
	}

	// Convert options if provided
	var options []domainModeldesign.EnumOption
	if input.Options != nil {
		options = make([]domainModeldesign.EnumOption, 0, len(input.Options))
		for _, opt := range input.Options {
			options = append(options, domainModeldesign.EnumOption{
				Code:        opt.Code,
				Label:       opt.Label,
				Order:       opt.Order,
				Description: bizutils.SafeString(opt.Description),
			})
		}
	}

	// Build command
	cmd := modeldesign.UpdateEnumCommand{
		OrgName:     orgName,
		ProjectSlug: projectSlug,
		Name:        name,
		DisplayName: input.DisplayName,
		Description: input.Description,
		Options:     options,
	}

	// Update enum
	err = r.EnumAppService.UpdateEnum(ctx, cmd)
	if err != nil {
		// Convert error to typed GraphQL error
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			return &generated.UpdateEnumPayload{
				Enum:  nil,
				Error: enumErrorAdapter.ConvertToUpdateEnumError(bizErr),
			}, nil
		}
		return nil, err
	}

	// Get updated enum
	getCmd := modeldesign.GetEnumCommand{
		OrgName:     "", // Will use default in service
		ProjectSlug: projectSlug,
		Name:        name,
	}
	enum, err := r.EnumAppService.GetEnum(ctx, getCmd)
	if err != nil {
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			return &generated.UpdateEnumPayload{
				Enum:  nil,
				Error: enumErrorAdapter.ConvertToUpdateEnumError(bizErr),
			}, nil
		}
		return nil, err
	}

	result := adapter.EnumMapper.ConvertEnumDefinitionToGraphQL(enum)
	return &generated.UpdateEnumPayload{
		Enum:  result,
		Error: nil,
	}, nil
}

// DeleteEnum is the resolver for the deleteEnum field.
func (r *mutationResolver) DeleteEnum(ctx context.Context, name string) (*generated.DeleteEnumPayload, error) {
	enumErrorAdapter := adapter.NewEnumErrorAdapter(ctx)

	// Extract projectSlug from context
	projectSlug, err := ctxutils.GetProjectSlugFromContext(ctx)
	if err != nil {
		return &generated.DeleteEnumPayload{
			Success: false,
			Error:   &generated.EnumNotFound{Message: "projectSlug not found in context"},
		}, nil
	}

	// Get orgName from context
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		// Use default org if not found in context
		orgName = "modelcraft"
	}

	// Build command
	cmd := modeldesign.DeleteEnumCommand{
		OrgName:     orgName,
		ProjectSlug: projectSlug,
		Name:        name,
	}

	err = r.EnumAppService.DeleteEnum(ctx, cmd)
	if err != nil {
		// Convert error to typed GraphQL error
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			return &generated.DeleteEnumPayload{
				Success: false,
				Error:   enumErrorAdapter.ConvertToDeleteEnumError(bizErr),
			}, nil
		}
		return nil, err
	}

	return &generated.DeleteEnumPayload{
		Success: true,
		Error:   nil,
	}, nil
}

// Enum is the resolver for the enum field.
func (r *queryResolver) Enum(ctx context.Context, name string) (*generated.GetEnumPayload, error) {
	enumErrorAdapter := adapter.NewEnumErrorAdapter(ctx)

	// Extract projectSlug from context
	projectSlug, err := ctxutils.GetProjectSlugFromContext(ctx)
	if err != nil {
		return &generated.GetEnumPayload{
			Error: &generated.EnumNotFound{Message: "projectSlug not found in context"},
		}, nil
	}

	// Get orgName from context
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		// Use default org if not found in context
		orgName = "modelcraft"
	}

	// Build command
	cmd := modeldesign.GetEnumCommand{
		OrgName:     orgName,
		ProjectSlug: projectSlug,
		Name:        name,
	}

	enum, err := r.EnumAppService.GetEnum(ctx, cmd)
	if err != nil {
		// Convert error to typed GraphQL error
		var bizErr *bizerrors.BusinessError
		if errors.As(err, &bizErr) {
			return &generated.GetEnumPayload{
				Enum:  nil,
				Error: enumErrorAdapter.ConvertToGetEnumError(bizErr),
			}, nil
		}
		return nil, err
	}

	result := adapter.EnumMapper.ConvertEnumDefinitionToGraphQL(enum)
	return &generated.GetEnumPayload{
		Enum:  result,
		Error: nil,
	}, nil
}

// Enums is the resolver for the enums field.
func (r *queryResolver) Enums(ctx context.Context) ([]*generated.EnumDefinition, error) {
	// Extract projectSlug from context
	projectSlug, err := ctxutils.GetProjectSlugFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Get orgName from context
	orgName, err := ctxutils.GetOrgNameFromContext(ctx)
	if err != nil {
		// Use default org if not found in context
		orgName = "modelcraft"
	}

	var result []*generated.EnumDefinition
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		// Build command
		cmd := modeldesign.ListEnumsCommand{
			OrgName:     orgName,
			ProjectSlug: projectSlug,
		}

		enums, err := r.EnumAppService.ListEnums(ctx, cmd)
		if err != nil {
			return err
		}

		result = make([]*generated.EnumDefinition, 0, len(enums))
		for _, enum := range enums {
			result = append(result, adapter.EnumMapper.ConvertEnumDefinitionToGraphQL(enum))
		}
		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return result, nil
}

// EnumReferences is the resolver for the enumReferences field.
func (r *queryResolver) EnumReferences(ctx context.Context, name string) ([]string, error) {
	// Extract projectSlug from context
	projectSlug, err := ctxutils.GetProjectSlugFromContext(ctx)
	if err != nil {
		return nil, err
	}

	var result []string
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		// Build command
		cmd := modeldesign.GetEnumReferencesCommand{
			OrgName:     "", // Will use default in service
			ProjectSlug: projectSlug,
			Name:        name,
		}

		references, err := r.EnumAppService.GetEnumReferences(ctx, cmd)
		if err != nil {
			return err
		}
		result = references
		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return result, nil
}
