package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"modelcraft/internal/app/modeldesign"
	"modelcraft/internal/interfaces/graphql/project/adapter"
	"modelcraft/internal/interfaces/graphql/project/generated"
	"modelcraft/pkg/logfacade"
	"time"
)

// CreateFieldEnumRelation is the resolver for the createFieldEnumRelation field.
func (r *mutationResolver) CreateFieldEnumRelation(ctx context.Context, input generated.CreateFieldEnumRelationInput) (*generated.CreateFieldEnumRelationPayload, error) {
	errorAdapter := adapter.NewModelErrorAdapter(ctx)

	relation, err := r.ModelDesignService.CreateFieldEnumRelation(ctx, modeldesign.CreateFieldEnumRelationCommand{
		ModelID:         input.ModelID,
		LabelFieldName:  input.LabelFieldName,
		SourceFieldName: input.SourceFieldName,
		EnumName:        input.EnumName,
	})
	if err != nil {
		logfacade.GetLogger(ctx).Error(ctx, "failed to create field enum relation", logfacade.Err(err), logfacade.Stack(err))
		return &generated.CreateFieldEnumRelationPayload{
			Relation: nil,
			Error:    errorAdapter.ConvertToCreateFieldEnumRelationError(err),
		}, nil
	}

	return &generated.CreateFieldEnumRelationPayload{
		Relation: &generated.FieldEnumRelation{
			ID:              relation.ID,
			ModelID:         relation.ModelID,
			LabelFieldName:  relation.LabelFieldName,
			SourceFieldName: relation.SourceFieldName,
			EnumName:        relation.EnumName,
			OrgName:         relation.OrgName,
			ProjectSlug:     relation.ProjectSlug,
			CreatedAt:       relation.CreatedAt.Format(time.RFC3339),
			UpdatedAt:       relation.UpdatedAt.Format(time.RFC3339),
		},
		Error: nil,
	}, nil
}

// DeleteFieldEnumRelation is the resolver for the deleteFieldEnumRelation field.
func (r *mutationResolver) DeleteFieldEnumRelation(ctx context.Context, id string) (*generated.DeleteFieldEnumRelationPayload, error) {
	errorAdapter := adapter.NewModelErrorAdapter(ctx)

	err := r.ModelDesignService.DeleteFieldEnumRelation(ctx, modeldesign.DeleteFieldEnumRelationCommand{ID: id})
	if err != nil {
		logfacade.GetLogger(ctx).Error(ctx, "failed to delete field enum relation", logfacade.Err(err), logfacade.Stack(err))
		return &generated.DeleteFieldEnumRelationPayload{
			Success: false,
			Error:   errorAdapter.ConvertToDeleteFieldEnumRelationError(err),
		}, nil
	}

	return &generated.DeleteFieldEnumRelationPayload{Success: true, Error: nil}, nil
}

// FieldEnumRelations is the resolver for the fieldEnumRelations field.
func (r *queryResolver) FieldEnumRelations(ctx context.Context, modelID string) ([]*generated.FieldEnumRelation, error) {
	relations, err := r.ModelDesignService.ListFieldEnumRelations(ctx, modeldesign.ListFieldEnumRelationsCommand{ModelID: modelID})
	if err != nil {
		logfacade.GetLogger(ctx).Error(ctx, "failed to list field enum relations", logfacade.Err(err), logfacade.Stack(err))
		return nil, err
	}

	result := make([]*generated.FieldEnumRelation, 0, len(relations))
	for _, relation := range relations {
		result = append(result, &generated.FieldEnumRelation{
			ID:              relation.ID,
			ModelID:         relation.ModelID,
			LabelFieldName:  relation.LabelFieldName,
			SourceFieldName: relation.SourceFieldName,
			EnumName:        relation.EnumName,
			OrgName:         relation.OrgName,
			ProjectSlug:     relation.ProjectSlug,
			CreatedAt:       relation.CreatedAt.Format(time.RFC3339),
			UpdatedAt:       relation.UpdatedAt.Format(time.RFC3339),
		})
	}
	return result, nil
}
