package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	appmodeldesign "modelcraft/internal/app/modeldesign"
	"modelcraft/internal/domain/modeldesign"
	"modelcraft/internal/interfaces/graphql/project/adapter"
	"modelcraft/internal/interfaces/graphql/project/generated"
	"modelcraft/internal/interfaces/mapper"
	"modelcraft/pkg/bizerrors"
	"modelcraft/pkg/logfacade"
)

// AddFields is the resolver for the addFields field.
func (r *mutationResolver) AddFields(ctx context.Context, modelID string, input []*generated.AddFieldInput) (*generated.AddFieldsPayload, error) {
	errorAdapter := adapter.NewModelErrorAdapter(ctx)
	results := make([]*generated.AddFieldItemResult, 0, len(input))
	hasSuccess := false

	for _, inputItem := range input {
		if inputItem == nil {
			gqlErr := &generated.InvalidInput{Message: "field input is required"}
			results = append(results, &generated.AddFieldItemResult{Name: "", Success: false, Error: gqlErr})
			continue
		}

		dto, err := adapter.FieldMapper.ConvertAddFieldInputToDTO(inputItem)
		if err != nil {
			gqlErr := convertToAddFieldsError(err, errorAdapter)
			results = append(results, &generated.AddFieldItemResult{Name: inputItem.Name, Success: false, Error: gqlErr})
			continue
		}

		field, err := mapper.FieldMapper.ConvertFieldDTOToDomain(modelID, nil, dto)
		if err != nil {
			gqlErr := convertToAddFieldsError(err, errorAdapter)
			results = append(results, &generated.AddFieldItemResult{Name: inputItem.Name, Success: false, Error: gqlErr})
			continue
		}

		appResults, appErr := r.ModelDesignService.AddFieldsWithResults(ctx, appmodeldesign.AddFieldCommand{
			ModelID: modelID,
			Fields:  []*modeldesign.FieldDefinition{field},
		})
		if appErr != nil {
			return nil, appErr
		}
		if len(appResults) == 0 {
			gqlErr := &generated.InvalidInput{Message: "failed to process add field request"}
			results = append(results, &generated.AddFieldItemResult{Name: inputItem.Name, Success: false, Error: gqlErr})
			continue
		}

		result := appResults[0]
		if result.Success {
			hasSuccess = true
			results = append(results, &generated.AddFieldItemResult{Name: result.Name, Success: true, Error: nil})
			continue
		}

		gqlErr := convertToAddFieldsError(result.Err, errorAdapter)
		results = append(results, &generated.AddFieldItemResult{Name: result.Name, Success: false, Error: gqlErr})
	}

	payload := &generated.AddFieldsPayload{Results: results}
	for _, item := range results {
		if !item.Success {
			payload.Error = item.Error
			break
		}
	}

	if hasSuccess {
		updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions().WithEnumOptions())
		if err != nil {
			return nil, err
		}
		graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
		if err != nil {
			return nil, fmt.Errorf("failed to convert domain model to GraphQL model: %w", err)
		}
		payload.Model = graphqlModel
	}

	return payload, nil
}

// UpdateField is the resolver for the updateField field.
func (r *mutationResolver) UpdateField(ctx context.Context, modelID string, fieldName string, input generated.UpdateFieldInput) (*generated.UpdateFieldPayload, error) {
	errorAdapter := adapter.NewModelErrorAdapter(ctx)

	cmd := appmodeldesign.UpdateFieldCommand{
		ModelID:   modelID,
		FieldName: fieldName,
	}
	if input.Title != nil {
		cmd.Title = *input.Title
	}
	if input.Description != nil {
		cmd.Description = *input.Description
	}
	if input.ValidationConfig != nil {
		cmd.ValidationConfig = adapter.FieldMapper.ConvertValidationInputToDomain(input.ValidationConfig)
	}

	if err := r.ModelDesignService.UpdateFieldSync(ctx, cmd); err != nil {
		logfacade.GetLogger(ctx).Error(ctx, "failed to update field", logfacade.Err(err), logfacade.Stack(err))
		return &generated.UpdateFieldPayload{Error: errorAdapter.ConvertToUpdateFieldError(err)}, nil
	}

	updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions())
	if err != nil {
		return nil, err
	}

	graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
	if err != nil {
		return nil, err
	}

	return &generated.UpdateFieldPayload{Model: graphqlModel}, nil
}

// RemoveField is the resolver for the removeField field.
func (r *mutationResolver) RemoveField(ctx context.Context, modelID string, fieldName string) (*generated.RemoveFieldPayload, error) {
	errorAdapter := adapter.NewModelErrorAdapter(ctx)

	cmd := appmodeldesign.RemoveFieldCommand{
		ModelID:   modelID,
		FieldName: fieldName,
	}

	if err := r.ModelDesignService.RemoveFieldSync(ctx, cmd); err != nil {
		logfacade.GetLogger(ctx).Error(ctx, "failed to remove field", logfacade.Err(err), logfacade.Stack(err))
		return &generated.RemoveFieldPayload{Error: errorAdapter.ConvertToRemoveFieldError(err)}, nil
	}

	updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions())
	if err != nil {
		return nil, err
	}

	graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
	if err != nil {
		return nil, err
	}

	return &generated.RemoveFieldPayload{Model: graphqlModel}, nil
}

// DeprecateField is the resolver for the deprecateField field.
func (r *mutationResolver) DeprecateField(ctx context.Context, modelID string, fieldName string) (*generated.Model, error) {
	var payload *generated.Model
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		cmd := appmodeldesign.DeprecateFieldCommand{
			ModelID:   modelID,
			FieldName: fieldName,
		}

		if err := r.ModelDesignService.DeprecateField(ctx, cmd); err != nil {
			return err
		}

		updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions())
		if err != nil {
			return err
		}

		graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
		if err != nil {
			return err
		}

		payload = graphqlModel
		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return payload, nil
}

// UndeprecateField is the resolver for the undeprecateField field.
func (r *mutationResolver) UndeprecateField(ctx context.Context, modelID string, fieldName string) (*generated.Model, error) {
	var payload *generated.Model
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		cmd := appmodeldesign.UndeprecateFieldCommand{
			ModelID:   modelID,
			FieldName: fieldName,
		}

		if err := r.ModelDesignService.UndeprecateField(ctx, cmd); err != nil {
			return err
		}

		updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions())
		if err != nil {
			return err
		}

		graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
		if err != nil {
			return err
		}

		payload = graphqlModel
		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return payload, nil
}

// Fields is the resolver for the fields field.
func (r *queryResolver) Fields(ctx context.Context, modelID string) ([]*generated.Field, error) {
	var payload []*generated.Field
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		cmd := appmodeldesign.GetFieldsCommand{ModelID: modelID}

		fields, err := r.ModelDesignService.GetFieldsByModelID(ctx, cmd)
		if err != nil {
			return err
		}

		modelMapper := adapter.ModelMapper
		graphqlFields := make([]*generated.Field, 0, len(fields))
		for _, field := range fields {
			graphqlField, err := modelMapper.ConvertFieldToGraphQLField(*field)
			if err != nil {
				return err
			}
			graphqlFields = append(graphqlFields, graphqlField)
		}
		payload = graphqlFields

		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return payload, nil
}
