package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	appmodeldesign "modelcraft/internal/app/modeldesign"
	"modelcraft/internal/domain/modeldesign"
	"modelcraft/internal/interfaces/graphql/project/adapter"
	"modelcraft/internal/interfaces/graphql/project/generated"
	"modelcraft/internal/interfaces/mapper"
	"modelcraft/pkg/bizerrors"
	"strings"
)

// AddFields is the resolver for the addFields field.
func (r *mutationResolver) AddFields(ctx context.Context, modelID string, input []*generated.AddFieldInput) (*generated.AddFieldsPayload, error) {
	errorAdapter := adapter.NewModelErrorAdapter(ctx)

	// Convert GraphQL input to domain field definitions via DTO intermediate
	fields := make([]*modeldesign.FieldDefinition, 0, len(input))
	for _, inputItem := range input {
		dto, err := adapter.FieldMapper.ConvertAddFieldInputToDTO(inputItem)
		if err != nil {
			if bizErr, ok := err.(*bizerrors.BusinessError); ok {
				return &generated.AddFieldsPayload{
					Error: errorAdapter.ConvertToAddFieldsError(bizErr),
				}, nil
			}
			return nil, err
		}
		field, err := mapper.FieldMapper.ConvertFieldDTOToDomain(modelID, nil, dto)
		if err != nil {
			if bizErr, ok := err.(*bizerrors.BusinessError); ok {
				return &generated.AddFieldsPayload{
					Error: errorAdapter.ConvertToAddFieldsError(bizErr),
				}, nil
			}
			return nil, err
		}
		fields = append(fields, field)
	}

	// Create command
	cmd := appmodeldesign.AddFieldCommand{
		ModelID: modelID,
		Fields:  fields,
	}

	// Add field using app service
	err := r.ModelDesignService.AddFieldSync(ctx, cmd)
	if err != nil {
		// Convert business errors to typed GraphQL errors
		if bizErr, ok := err.(*bizerrors.BusinessError); ok {
			return &generated.AddFieldsPayload{
				Model: nil,
				Error: errorAdapter.ConvertToAddFieldsError(bizErr),
			}, nil
		}

		// Domain validation errors should also be mapped to AddFieldsPayload.error
		if strings.Contains(err.Error(), "(FieldValidate)") {
			return &generated.AddFieldsPayload{
				Model: nil,
				Error: &generated.InvalidModelInput{Message: err.Error()},
			}, nil
		}

		// For non-business errors, still throw as GraphQL error
		return nil, err
	}

	// Get updated model
	updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions())
	if err != nil {
		return nil, err
	}

	// Convert domain model to GraphQL model
	graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
	if err != nil {
		return nil, fmt.Errorf("failed to convert domain model to GraphQL model: %w", err)
	}

	return &generated.AddFieldsPayload{
		Model: graphqlModel,
		Error: nil,
	}, nil
}

// UpdateField is the resolver for the updateField field.
func (r *mutationResolver) UpdateField(ctx context.Context, modelID string, fieldName string, input generated.UpdateFieldInput) (*generated.Model, error) {
	var payload *generated.Model
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		// Convert GraphQL input to command
		cmd := appmodeldesign.UpdateFieldCommand{
			ModelID:   modelID,
			FieldName: fieldName,
		}
		if input.Title != nil {
			cmd.Title = *input.Title
		}
		if input.Description != nil {
			cmd.Description = *input.Description
		}
		if input.ValidationConfig != nil {
			cmd.ValidationConfig = adapter.FieldMapper.ConvertValidationInputToDomain(input.ValidationConfig)
		}

		// Update field using app service
		err := r.ModelDesignService.UpdateFieldSync(ctx, cmd)
		if err != nil {
			return err
		}

		// Get updated model
		updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions())
		if err != nil {
			return err
		}

		// Convert domain model to GraphQL model
		graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
		if err != nil {
			return err
		}

		payload = graphqlModel
		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return payload, nil
}

// RemoveField is the resolver for the removeField field.
func (r *mutationResolver) RemoveField(ctx context.Context, modelID string, fieldName string) (*generated.Model, error) {
	// Remove field using app service
	var payload *generated.Model
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		// Build command
		cmd := appmodeldesign.RemoveFieldCommand{
			ModelID:   modelID,
			FieldName: fieldName,
		}

		err := r.ModelDesignService.RemoveFieldSync(ctx, cmd)
		if err != nil {
			return err
		}

		// Get updated model
		updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions())
		if err != nil {
			return err
		}

		// Convert domain model to GraphQL model
		graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
		if err != nil {
			return err
		}

		payload = graphqlModel
		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return payload, nil
}

// DeprecateField is the resolver for the deprecateField field.
func (r *mutationResolver) DeprecateField(ctx context.Context, modelID string, fieldName string) (*generated.Model, error) {
	var payload *generated.Model
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		cmd := appmodeldesign.DeprecateFieldCommand{
			ModelID:   modelID,
			FieldName: fieldName,
		}

		if err := r.ModelDesignService.DeprecateField(ctx, cmd); err != nil {
			return err
		}

		updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions())
		if err != nil {
			return err
		}

		graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
		if err != nil {
			return err
		}

		payload = graphqlModel
		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return payload, nil
}

// UndeprecateField is the resolver for the undeprecateField field.
func (r *mutationResolver) UndeprecateField(ctx context.Context, modelID string, fieldName string) (*generated.Model, error) {
	var payload *generated.Model
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		cmd := appmodeldesign.UndeprecateFieldCommand{
			ModelID:   modelID,
			FieldName: fieldName,
		}

		if err := r.ModelDesignService.UndeprecateField(ctx, cmd); err != nil {
			return err
		}

		updatedModel, err := r.ModelDesignService.GetModelByID(ctx, modelID, appmodeldesign.NewGetModelOptions())
		if err != nil {
			return err
		}

		graphqlModel, err := adapter.ModelMapper.ConvertToGraphQLModel(updatedModel)
		if err != nil {
			return err
		}

		payload = graphqlModel
		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return payload, nil
}

// Fields is the resolver for the fields field.
func (r *queryResolver) Fields(ctx context.Context, modelID string) ([]*generated.Field, error) {
	var payload []*generated.Field
	graphqlErr := bizerrors.WithGraphqlErrorHandler(ctx, func() error {
		// Build command
		cmd := appmodeldesign.GetFieldsCommand{
			ModelID: modelID,
		}

		// Get model by ID using app service
		fields, err := r.ModelDesignService.GetFieldsByModelID(ctx, cmd)
		if err != nil {
			return err
		}

		// Convert domain fields to GraphQL fields
		modelMapper := adapter.ModelMapper
		graphqlFields := make([]*generated.Field, 0, len(fields))
		for _, field := range fields {
			graphqlField, err := modelMapper.ConvertFieldToGraphQLField(*field)
			if err != nil {
				return err
			}
			graphqlFields = append(graphqlFields, graphqlField)
		}
		payload = graphqlFields

		return nil
	})

	if graphqlErr != nil {
		return nil, graphqlErr
	}
	return payload, nil
}
