package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	apprbac "modelcraft/internal/app/rbac"
	domainproject "modelcraft/internal/domain/project"
	rbacdomain "modelcraft/internal/domain/rbac"
	"modelcraft/internal/interfaces/graphql/project/adapter"
	"modelcraft/internal/interfaces/graphql/project/generated"
	"modelcraft/pkg/logfacade"
)

// CreateEndUserPermission is the resolver for the createEndUserPermission field.
func (r *mutationResolver) CreateEndUserPermission(ctx context.Context, input generated.CreateEndUserPermissionInput) (*generated.CreateEndUserPermissionPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	var colPolicy *rbacdomain.ColumnPolicy
	if input.ColumnPolicy != nil {
		colPolicy = adapter.ToColumnPolicyDomain(input.ColumnPolicy)
	}

	perm, appErr := r.RBACPermissionSvc.CreatePermission(ctx, apprbac.CreatePermissionCommand{
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
		ModelID:      input.ModelID,
		Name:         derefString(input.DisplayName),
		Description:  input.Description,
		Action:       adapter.ToRbacActionDomain(input.Action),
		ColumnPolicy: colPolicy,
		RowScope:     adapter.ToRowScopeDomain(input.RowScope),
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.CreateEndUserPermissionPayload{
			Error: errAdapter.ConvertToCreatePermissionError(toBizErr(appErr)),
		}, nil
	}
	return &generated.CreateEndUserPermissionPayload{
		Permission: adapter.ToEndUserPermissionDTO(perm),
	}, nil
}

// UpdateEndUserPermission is the resolver for the updateEndUserPermission field.
func (r *mutationResolver) UpdateEndUserPermission(ctx context.Context, id string, input generated.UpdateEndUserPermissionInput) (*generated.UpdateEndUserPermissionPayload, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	var colPolicy *rbacdomain.ColumnPolicy
	if input.ColumnPolicy != nil {
		colPolicy = adapter.ToColumnPolicyDomain(input.ColumnPolicy)
	}

	perm, appErr := r.RBACPermissionSvc.UpdatePermission(ctx, apprbac.UpdatePermissionCommand{
		OrgName:      orgName,
		ID:           id,
		Name:         derefString(input.DisplayName),
		Description:  input.Description,
		ColumnPolicy: colPolicy,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.UpdateEndUserPermissionPayload{
			Error: errAdapter.ConvertToUpdatePermissionError(toBizErr(appErr)),
		}, nil
	}
	return &generated.UpdateEndUserPermissionPayload{
		Permission: adapter.ToEndUserPermissionDTO(perm),
	}, nil
}

// DeleteEndUserPermission is the resolver for the deleteEndUserPermission field.
func (r *mutationResolver) DeleteEndUserPermission(ctx context.Context, id string) (*generated.DeleteEndUserPermissionPayload, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	appErr := r.RBACPermissionSvc.DeletePermission(ctx, apprbac.DeletePermissionCommand{
		OrgName: orgName,
		ID:      id,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.DeleteEndUserPermissionPayload{
			Success: false,
			Error:   errAdapter.ConvertToDeletePermissionError(toBizErr(appErr)),
		}, nil
	}
	return &generated.DeleteEndUserPermissionPayload{Success: true}, nil
}

// ApplyEndUserPresetPolicy is the resolver for the applyEndUserPresetPolicy field.
func (r *mutationResolver) ApplyEndUserPresetPolicy(ctx context.Context, input generated.ApplyEndUserPresetPolicyInput) (*generated.ApplyEndUserPresetPolicyPayload, error) {
	panic(fmt.Errorf("not implemented: ApplyEndUserPresetPolicy - applyEndUserPresetPolicy"))
}

// CreateEndUserPermissionBundle is the resolver for the createEndUserPermissionBundle field.
func (r *mutationResolver) CreateEndUserPermissionBundle(ctx context.Context, input generated.CreateEndUserPermissionBundleInput) (*generated.CreateEndUserPermissionBundlePayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	bundle, appErr := r.RBACBundleSvc.CreateBundle(ctx, apprbac.CreateBundleCommand{
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
		Name:         input.Name,
		Description:  input.Description,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.CreateEndUserPermissionBundlePayload{
			Error: errAdapter.ConvertToCreateBundleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.CreateEndUserPermissionBundlePayload{
		Bundle: adapter.ToEndUserPermissionBundleDTO(bundle),
	}, nil
}

// UpdateEndUserPermissionBundle is the resolver for the updateEndUserPermissionBundle field.
func (r *mutationResolver) UpdateEndUserPermissionBundle(ctx context.Context, id string, input generated.UpdateEndUserPermissionBundleInput) (*generated.UpdateEndUserPermissionBundlePayload, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	bundle, appErr := r.RBACBundleSvc.UpdateBundle(ctx, apprbac.UpdateBundleCommand{
		OrgName:     orgName,
		ID:          id,
		Name:        derefString(input.Name),
		Description: input.Description,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.UpdateEndUserPermissionBundlePayload{
			Error: errAdapter.ConvertToUpdateBundleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.UpdateEndUserPermissionBundlePayload{
		Bundle: adapter.ToEndUserPermissionBundleDTO(bundle),
	}, nil
}

// DeleteEndUserPermissionBundle is the resolver for the deleteEndUserPermissionBundle field.
func (r *mutationResolver) DeleteEndUserPermissionBundle(ctx context.Context, id string) (*generated.DeleteEndUserPermissionBundlePayload, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	appErr := r.RBACBundleSvc.DeleteBundle(ctx, apprbac.DeleteBundleCommand{
		OrgName: orgName,
		ID:      id,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.DeleteEndUserPermissionBundlePayload{
			Success: false,
			Error:   errAdapter.ConvertToDeleteBundleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.DeleteEndUserPermissionBundlePayload{Success: true}, nil
}

// AddEndUserPermissionToBundle is the resolver for the addEndUserPermissionToBundle field.
func (r *mutationResolver) AddEndUserPermissionToBundle(ctx context.Context, input generated.AddEndUserPermissionToBundleInput) (*generated.AddEndUserPermissionToBundlePayload, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	sortOrder := 0
	if input.SortOrder != nil {
		sortOrder = int(*input.SortOrder)
	}

	bundle, appErr := r.RBACBundleSvc.AddPermissionToBundle(ctx, apprbac.AddPermissionToBundleCommand{
		OrgName:      orgName,
		BundleID:     input.BundleID,
		PermissionID: input.PermissionID,
		SortOrder:    sortOrder,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.AddEndUserPermissionToBundlePayload{
			Error: errAdapter.ConvertToAddPermissionToBundleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.AddEndUserPermissionToBundlePayload{
		Bundle: adapter.ToEndUserPermissionBundleDTO(bundle),
	}, nil
}

// RemoveEndUserPermissionFromBundle is the resolver for the removeEndUserPermissionFromBundle field.
func (r *mutationResolver) RemoveEndUserPermissionFromBundle(ctx context.Context, input generated.RemoveEndUserPermissionFromBundleInput) (*generated.RemoveEndUserPermissionFromBundlePayload, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	bundle, appErr := r.RBACBundleSvc.RemovePermissionFromBundle(ctx, apprbac.RemovePermissionFromBundleCommand{
		OrgName:      orgName,
		BundleID:     input.BundleID,
		PermissionID: input.PermissionID,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.RemoveEndUserPermissionFromBundlePayload{
			Error: errAdapter.ConvertToRemovePermissionFromBundleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.RemoveEndUserPermissionFromBundlePayload{
		Bundle: adapter.ToEndUserPermissionBundleDTO(bundle),
	}, nil
}

// CreateEndUserRole is the resolver for the createEndUserRole field.
func (r *mutationResolver) CreateEndUserRole(ctx context.Context, input generated.CreateEndUserRoleInput) (*generated.CreateEndUserRolePayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	role, appErr := r.RBACRoleSvc.CreateRole(ctx, apprbac.CreateRoleCommand{
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
		Name:         input.Name,
		Description:  input.Description,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.CreateEndUserRolePayload{
			Error: errAdapter.ConvertToCreateRoleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.CreateEndUserRolePayload{
		Role: adapter.ToEndUserRoleDTO(role),
	}, nil
}

// UpdateEndUserRole is the resolver for the updateEndUserRole field.
func (r *mutationResolver) UpdateEndUserRole(ctx context.Context, id string, input generated.UpdateEndUserRoleInput) (*generated.UpdateEndUserRolePayload, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	role, appErr := r.RBACRoleSvc.UpdateRole(ctx, apprbac.UpdateRoleCommand{
		OrgName:     orgName,
		ID:          id,
		Name:        derefString(input.Name),
		Description: input.Description,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.UpdateEndUserRolePayload{
			Error: errAdapter.ConvertToUpdateRoleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.UpdateEndUserRolePayload{
		Role: adapter.ToEndUserRoleDTO(role),
	}, nil
}

// DeleteEndUserRole is the resolver for the deleteEndUserRole field.
func (r *mutationResolver) DeleteEndUserRole(ctx context.Context, id string) (*generated.DeleteEndUserRolePayload, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	appErr := r.RBACRoleSvc.DeleteRole(ctx, apprbac.DeleteRoleCommand{
		OrgName: orgName,
		ID:      id,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.DeleteEndUserRolePayload{
			Success: false,
			Error:   errAdapter.ConvertToDeleteRoleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.DeleteEndUserRolePayload{Success: true}, nil
}

// AssignBundleToEndUserRole is the resolver for the assignBundleToEndUserRole field.
func (r *mutationResolver) AssignBundleToEndUserRole(ctx context.Context, input generated.AssignBundleToEndUserRoleInput) (*generated.AssignBundleToEndUserRolePayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	role, appErr := r.RBACRoleSvc.AssignBundleToRole(ctx, apprbac.AssignBundleToRoleCommand{
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
		RoleID:       input.RoleID,
		BundleID:     input.BundleID,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.AssignBundleToEndUserRolePayload{
			Error: errAdapter.ConvertToAssignBundleToRoleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.AssignBundleToEndUserRolePayload{
		Role: adapter.ToEndUserRoleDTO(role),
	}, nil
}

// RevokeBundleFromEndUserRole is the resolver for the revokeBundleFromEndUserRole field.
func (r *mutationResolver) RevokeBundleFromEndUserRole(ctx context.Context, input generated.RevokeBundleFromEndUserRoleInput) (*generated.RevokeBundleFromEndUserRolePayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	role, appErr := r.RBACRoleSvc.RevokeBundleFromRole(ctx, apprbac.RevokeBundleFromRoleCommand{
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
		RoleID:       input.RoleID,
		BundleID:     input.BundleID,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.RevokeBundleFromEndUserRolePayload{
			Error: errAdapter.ConvertToRevokeBundleFromRoleError(toBizErr(appErr)),
		}, nil
	}
	return &generated.RevokeBundleFromEndUserRolePayload{
		Role: adapter.ToEndUserRoleDTO(role),
	}, nil
}

// AssignBundleToEndUser is the resolver for the assignBundleToEndUser field.
func (r *mutationResolver) AssignBundleToEndUser(ctx context.Context, input generated.AssignBundleToEndUserInput) (*generated.AssignBundleToEndUserPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	appErr := r.RBACBundleSvc.GrantBundleToUser(ctx, apprbac.GrantBundleToUserCommand{
		UserID:       input.EndUserID,
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
		BundleID:     input.BundleID,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.AssignBundleToEndUserPayload{
			EndUserID: input.EndUserID,
			Error:     errAdapter.ConvertToAssignBundleToUserError(toBizErr(appErr)),
		}, nil
	}
	return &generated.AssignBundleToEndUserPayload{EndUserID: input.EndUserID}, nil
}

// RevokeBundleFromEndUser is the resolver for the revokeBundleFromEndUser field.
func (r *mutationResolver) RevokeBundleFromEndUser(ctx context.Context, input generated.RevokeBundleFromEndUserInput) (*generated.RevokeBundleFromEndUserPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	appErr := r.RBACBundleSvc.RevokeBundleFromUser(ctx, apprbac.RevokeBundleFromUserCommand{
		UserID:       input.EndUserID,
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
		BundleID:     input.BundleID,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.RevokeBundleFromEndUserPayload{
			Success: false,
			Error:   errAdapter.ConvertToRevokeBundleFromUserError(toBizErr(appErr)),
		}, nil
	}
	return &generated.RevokeBundleFromEndUserPayload{Success: true}, nil
}

// AssignEndUserRole is the resolver for the assignEndUserRole field.
func (r *mutationResolver) AssignEndUserRole(ctx context.Context, input generated.AssignEndUserRoleInput) (*generated.AssignEndUserRolePayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	appErr := r.RBACRoleSvc.AssignRoleToUser(ctx, apprbac.AssignRoleToUserCommand{
		UserID:       input.EndUserID,
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
		RoleID:       input.RoleID,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.AssignEndUserRolePayload{
			EndUserID: input.EndUserID,
			Error:     errAdapter.ConvertToAssignRoleToUserError(toBizErr(appErr)),
		}, nil
	}
	return &generated.AssignEndUserRolePayload{EndUserID: input.EndUserID}, nil
}

// RevokeEndUserRole is the resolver for the revokeEndUserRole field.
func (r *mutationResolver) RevokeEndUserRole(ctx context.Context, input generated.RevokeEndUserRoleInput) (*generated.RevokeEndUserRolePayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	appErr := r.RBACRoleSvc.RevokeRoleFromUser(ctx, apprbac.RevokeRoleFromUserCommand{
		UserID:       input.EndUserID,
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
		RoleID:       input.RoleID,
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		errAdapter := adapter.NewRbacErrorAdapter(ctx)
		return &generated.RevokeEndUserRolePayload{
			Success: false,
			Error:   errAdapter.ConvertToRevokeRoleFromUserError(toBizErr(appErr)),
		}, nil
	}
	return &generated.RevokeEndUserRolePayload{Success: true}, nil
}

// EndUserPermission is the resolver for the endUserPermission field.
func (r *queryResolver) EndUserPermission(ctx context.Context, id string) (*generated.EndUserPermission, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}
	perm, appErr := r.RBACPermissionSvc.GetPermissionByID(ctx, orgName, id)
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		return nil, appErr
	}
	return adapter.ToEndUserPermissionDTO(perm), nil
}

// EndUserPermissions is the resolver for the endUserPermissions field.
func (r *queryResolver) EndUserPermissions(ctx context.Context, input *generated.ListEndUserPermissionsInput) (*generated.EndUserPermissionConnection, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}
	perms, appErr := r.RBACPermissionSvc.ListPermissionsByProject(ctx, orgName, projectSlug)
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		return nil, appErr
	}
	edges := make([]*generated.EndUserPermissionEdge, 0, len(perms))
	for _, p := range perms {
		edges = append(edges, &generated.EndUserPermissionEdge{
			Node:   adapter.ToEndUserPermissionDTO(p),
			Cursor: p.ID,
		})
	}
	return &generated.EndUserPermissionConnection{
		Edges:      edges,
		PageInfo:   &generated.PageInfo{},
		TotalCount: int32(len(perms)),
	}, nil
}

// EndUserPermissionBundle is the resolver for the endUserPermissionBundle field.
func (r *queryResolver) EndUserPermissionBundle(ctx context.Context, id string) (*generated.EndUserPermissionBundle, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}
	bundle, appErr := r.RBACBundleSvc.GetBundleByID(ctx, orgName, id)
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		return nil, appErr
	}
	return adapter.ToEndUserPermissionBundleDTO(bundle), nil
}

// EndUserPermissionBundles is the resolver for the endUserPermissionBundles field.
func (r *queryResolver) EndUserPermissionBundles(ctx context.Context, input *generated.ListEndUserPermissionBundlesInput) (*generated.EndUserPermissionBundleConnection, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}
	bundles, appErr := r.RBACBundleSvc.ListBundlesByProject(ctx, orgName, projectSlug)
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		return nil, appErr
	}
	edges := make([]*generated.EndUserPermissionBundleEdge, 0, len(bundles))
	for _, b := range bundles {
		edges = append(edges, &generated.EndUserPermissionBundleEdge{
			Node:   adapter.ToEndUserPermissionBundleDTO(b),
			Cursor: b.ID,
		})
	}
	return &generated.EndUserPermissionBundleConnection{
		Edges:      edges,
		PageInfo:   &generated.PageInfo{},
		TotalCount: int32(len(bundles)),
	}, nil
}

// EndUserRole is the resolver for the endUserRole field.
func (r *queryResolver) EndUserRole(ctx context.Context, id string) (*generated.EndUserRole, error) {
	orgName, _, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}
	role, appErr := r.RBACRoleSvc.GetRoleByID(ctx, orgName, id)
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		return nil, appErr
	}
	return adapter.ToEndUserRoleDTO(role), nil
}

// EndUserRoles is the resolver for the endUserRoles field.
func (r *queryResolver) EndUserRoles(ctx context.Context, input *generated.ListEndUserRolesInput) (*generated.EndUserRoleConnection, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}
	roles, appErr := r.RBACRoleSvc.ListRolesByProject(ctx, orgName, projectSlug)
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		return nil, appErr
	}
	edges := make([]*generated.EndUserRoleEdge, 0, len(roles))
	for _, role := range roles {
		edges = append(edges, &generated.EndUserRoleEdge{
			Node:   adapter.ToEndUserRoleDTO(role),
			Cursor: role.ID,
		})
	}
	return &generated.EndUserRoleConnection{
		Edges:      edges,
		PageInfo:   &generated.PageInfo{},
		TotalCount: int32(len(roles)),
	}, nil
}

// EndUserBundleAssignments is the resolver for the endUserBundleAssignments field.
func (r *queryResolver) EndUserBundleAssignments(ctx context.Context, endUserID string) ([]*generated.EndUserBundleAssignment, error) {
	// TODO: implement with dedicated query when needed
	return []*generated.EndUserBundleAssignment{}, nil
}

// EndUserRoleAssignments is the resolver for the endUserRoleAssignments field.
func (r *queryResolver) EndUserRoleAssignments(ctx context.Context, endUserID string) ([]*generated.EndUserRoleAssignment, error) {
	// TODO: implement with dedicated query when needed
	return []*generated.EndUserRoleAssignment{}, nil
}

// EffectivePermissions is the resolver for the effectivePermissions field.
func (r *queryResolver) EffectivePermissions(ctx context.Context, input generated.GetEffectivePermissionsInput) (*generated.GetEffectivePermissionsPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	eps, appErr := r.RBACAuthzSvc.GetEffectivePermissions(ctx, apprbac.GetEffectivePermissionsQuery{
		UserID:       input.EndUserID,
		ProjectScope: domainproject.ProjectScope{OrgName: orgName, ProjectSlug: projectSlug},
	})
	if appErr != nil {
		logfacade.GetLogger(ctx).Error(ctx, "rbac operation failed", logfacade.Err(appErr), logfacade.Stack(appErr))
		return nil, appErr
	}

	// Convert EffectivePermissionSet to EffectivePermissions DTO
	grants := make([]*generated.EffectiveGrant, 0)
	for _, ep := range eps {
		grants = append(grants, &generated.EffectiveGrant{
			Action:       generated.RbacAction(ep.Action),
			ColumnPolicy: adapter.ToColumnPolicyDTO(ep.ColumnPolicy),
			RowScope:     generated.RowScopeType(ep.RowScope),
		})
	}

	return &generated.GetEffectivePermissionsPayload{
		EffectivePermissions: &generated.EffectivePermissions{
			EndUserID: input.EndUserID,
			ModelID:   input.ModelID,
			Grants:    grants,
			Sources: &generated.EffectivePermissionSources{
				DirectBundles:       []*generated.EndUserPermissionBundle{},
				ExplicitRoleBundles: []*generated.EndUserRoleBundleSource{},
				ImplicitRoleBundles: []*generated.EndUserRoleBundleSource{},
			},
		},
	}, nil
}
