package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"encoding/json"
	"fmt"
	appRLS "modelcraft/internal/app/rls"
	domainRLS "modelcraft/internal/domain/rls"
	"modelcraft/internal/interfaces/graphql/project/generated"
	"modelcraft/internal/interfaces/http/middleware"
)

// SetModelRLSPolicy is the resolver for the setModelRLSPolicy field.
func (r *mutationResolver) SetModelRLSPolicy(ctx context.Context, input generated.SetModelRLSPolicyInput) (*generated.SetModelRLSPolicyPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Convert GraphQL input to AppService DTO
	appInput := appRLS.SetModelRLSPolicyInput{
		ModelID:         input.ModelID,
		SelectPredicate: domainRLS.JsonExpr(input.SelectPredicate),
		InsertCheck:     domainRLS.JsonExpr(input.InsertCheck),
		UpdatePredicate: domainRLS.JsonExpr(input.UpdatePredicate),
		UpdateCheck:     domainRLS.JsonExpr(input.UpdateCheck),
		DeletePredicate: domainRLS.JsonExpr(input.DeletePredicate),
	}

	// Call AppService
	policy, err := r.RLSPolicyAppService.SetPolicy(ctx, orgName, projectSlug, appInput)
	if err != nil {
		return &generated.SetModelRLSPolicyPayload{
			Policy: nil,
			Error:  convertRLSErrorToGraphQLType(ctx, err),
		}, nil
	}

	// Convert domain model to GraphQL type
	graphqlPolicy := convertPolicyToGraphQL(policy)

	return &generated.SetModelRLSPolicyPayload{
		Policy: graphqlPolicy,
		Error:  nil,
	}, nil
}

// ValidateRLSExpr is the resolver for the validateRLSExpr field.
func (r *mutationResolver) ValidateRLSExpr(ctx context.Context, input generated.ValidateRLSExprInput) (*generated.ValidateRLSExprPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Convert exprType
	exprType := convertGraphQLExprTypeToDomain(input.ExprType)

	// Call AppService
	validationErrors := r.RLSPolicyAppService.ValidateExpr(
		ctx, orgName, projectSlug, input.ModelID,
		domainRLS.ExprType(exprType), domainRLS.JsonExpr(input.Expression),
	)

	// Convert validation errors
	graphqlErrors := make([]*generated.ValidationError, 0, len(validationErrors))
	for _, e := range validationErrors {
		graphqlErrors = append(graphqlErrors, &generated.ValidationError{
			Path:    e.Path,
			Message: e.Message,
			Code:    e.Code,
		})
	}

	var sampleInput map[string]any
	if input.SampleInput != nil && *input.SampleInput != "" {
		if err := json.Unmarshal([]byte(*input.SampleInput), &sampleInput); err != nil {
			graphqlErrors = append(graphqlErrors, &generated.ValidationError{
				Path:    "sampleInput",
				Message: err.Error(),
				Code:    "INVALID_SAMPLE_INPUT",
			})
		}
	}

	dryRunResult := r.RLSPolicyAppService.DryRunExpr(
		ctx,
		orgName,
		projectSlug,
		input.ModelID,
		domainRLS.ExprType(exprType),
		input.Expression,
		sampleInput,
		middleware.GetUserContext(ctx),
	)

	var dryRun *generated.RLSExprDryRun
	if dryRunResult.Valid {
		dryRun = &generated.RLSExprDryRun{
			SQL:    stringPtrIfNotEmpty(dryRunResult.SQL),
			Result: dryRunResult.Result,
		}
		if len(dryRunResult.Params) > 0 {
			params := make([]string, 0, len(dryRunResult.Params))
			for _, param := range dryRunResult.Params {
				params = append(params, fmt.Sprint(param))
			}
			dryRun.Params = params
		}
	}

	return &generated.ValidateRLSExprPayload{
		Result: &generated.ValidationResult{
			Valid:  len(graphqlErrors) == 0,
			Errors: graphqlErrors,
		},
		DryRun: dryRun,
	}, nil
}

// SetProjectAuthSchema is the resolver for the setProjectAuthSchema field (deprecated, no-op).
func (r *mutationResolver) SetProjectAuthSchema(ctx context.Context, input generated.SetProjectAuthSchemaInput) (*generated.SetProjectAuthSchemaPayload, error) {
	return &generated.SetProjectAuthSchemaPayload{
		AuthSchema: emptyProjectAuthSchema(),
		Error:      nil,
	}, nil
}

// ModelRLSPolicy is the resolver for the modelRLSPolicy field.
func (r *queryResolver) ModelRLSPolicy(ctx context.Context, modelID string) (*generated.ModelRLSPolicy, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Call AppService
	policy, err := r.RLSPolicyAppService.GetPolicy(ctx, orgName, projectSlug, modelID)
	if err != nil {
		return nil, err
	}

	if policy == nil {
		return nil, nil //nolint:nilnil // nil policy with nil error means no policy exists
	}

	return convertPolicyToGraphQL(policy), nil
}

// ProjectAuthSchema is the resolver for the projectAuthSchema field (deprecated, no-op).
func (r *queryResolver) ProjectAuthSchema(ctx context.Context) (*generated.ProjectAuthSchema, error) {
	return emptyProjectAuthSchema(), nil
}
