package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	appRLS "modelcraft/internal/app/rls"
	domainRLS "modelcraft/internal/domain/rls"
	"modelcraft/internal/interfaces/graphql/project/generated"
	"sort"
	"strconv"
)

// UpsertRlsPolicy is the resolver for the upsertRlsPolicy field.
func (r *mutationResolver) UpsertRlsPolicy(ctx context.Context, modelID string, role string, input generated.RlsActionPolicyInput) (*generated.UpsertRlsPolicyPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	if role == "" {
		return &generated.UpsertRlsPolicyPayload{
			ActionPolicy: nil,
			Error:        &generated.InvalidInput{Message: "role must not be empty"},
		}, nil
	}

	var policyName string
	if input.PolicyName != nil {
		policyName = *input.PolicyName
	}
	var usingExpr domainRLS.JsonExpr
	if input.UsingExpr != nil {
		usingExpr = domainRLS.JsonExpr(*input.UsingExpr)
	}
	var withCheckExpr domainRLS.JsonExpr
	if input.WithCheckExpr != nil {
		withCheckExpr = domainRLS.JsonExpr(*input.WithCheckExpr)
	}

	policy, err := r.PolicyCRUDService.Upsert(ctx, orgName, projectSlug, appRLS.UpsertInput{
		ModelID:       modelID,
		PolicyName:    policyName,
		Action:        domainRLS.Action(input.Action),
		Role:          role,
		UsingExpr:     usingExpr,
		WithCheckExpr: withCheckExpr,
	})
	if err != nil {
		return &generated.UpsertRlsPolicyPayload{
			ActionPolicy: nil,
			Error:        &generated.InvalidInput{Message: err.Error()},
		}, nil
	}

	return &generated.UpsertRlsPolicyPayload{
		ActionPolicy: toActionPolicy(policy),
		Error:        nil,
	}, nil
}

// DeleteRlsPolicy is the resolver for the deleteRlsPolicy field.
func (r *mutationResolver) DeleteRlsPolicy(ctx context.Context, id string) (*generated.DeleteRlsPolicyPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	policyID, parseErr := strconv.ParseInt(id, 10, 64)
	if parseErr != nil {
		return &generated.DeleteRlsPolicyPayload{
			Success: false,
			Error:   &generated.ResourceNotFound{Message: "policy not found"},
		}, nil
	}

	if err := r.PolicyCRUDService.Delete(ctx, orgName, projectSlug, policyID); err != nil {
		return &generated.DeleteRlsPolicyPayload{
			Success: false,
			Error:   &generated.ResourceNotFound{Message: err.Error()},
		}, nil
	}

	return &generated.DeleteRlsPolicyPayload{Success: true, Error: nil}, nil
}

// DeleteRlsPoliciesByRole is the resolver for the deleteRlsPoliciesByRole field.
func (r *mutationResolver) DeleteRlsPoliciesByRole(ctx context.Context, modelID string, role string) (*generated.DeleteRlsPolicyPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.PolicyCRUDService.DeleteByRole(ctx, orgName, projectSlug, modelID, role); err != nil {
		return &generated.DeleteRlsPolicyPayload{
			Success: false,
			Error:   &generated.ResourceNotFound{Message: err.Error()},
		}, nil
	}

	return &generated.DeleteRlsPolicyPayload{Success: true, Error: nil}, nil
}

// DeleteRlsPoliciesByModel is the resolver for the deleteRlsPoliciesByModel field.
func (r *mutationResolver) DeleteRlsPoliciesByModel(ctx context.Context, modelID string) (*generated.DeleteRlsPolicyPayload, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.PolicyCRUDService.DeleteByModel(ctx, orgName, projectSlug, modelID); err != nil {
		return &generated.DeleteRlsPolicyPayload{
			Success: false,
			Error:   &generated.ResourceNotFound{Message: err.Error()},
		}, nil
	}

	return &generated.DeleteRlsPolicyPayload{Success: true, Error: nil}, nil
}

// RlsPolicies is the resolver for the rlsPolicies field.
// Returns policies grouped by role — the minimum unit the frontend displays.
func (r *queryResolver) RlsPolicies(ctx context.Context, modelID string) ([]*generated.RlsRolePolicy, error) {
	orgName, projectSlug, err := getOrgAndProjectFromContext(ctx)
	if err != nil {
		return nil, err
	}

	policies, err := r.PolicyCRUDService.ListByModel(ctx, orgName, projectSlug, modelID)
	if err != nil {
		return nil, err
	}

	// Sort by role then action for deterministic output
	sort.SliceStable(policies, func(i, j int) bool {
		if policies[i].Role != policies[j].Role {
			return policies[i].Role < policies[j].Role
		}
		return policies[i].Action < policies[j].Action
	})

	// Group by role
	grouped := make(map[string][]*generated.RlsActionPolicy)
	roleOrder := make([]string, 0, len(policies))
	for _, p := range policies {
		actions, ok := grouped[p.Role]
		if !ok {
			roleOrder = append(roleOrder, p.Role)
		}
		grouped[p.Role] = append(actions, toActionPolicy(p))
	}

	result := make([]*generated.RlsRolePolicy, 0, len(roleOrder))
	for _, role := range roleOrder {
		result = append(result, &generated.RlsRolePolicy{
			Role:    role,
			Actions: grouped[role],
		})
	}
	return result, nil
}
