package projectgraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"modelcraft/internal/interfaces/graphql/project/generated"
)

// UpsertRlsPolicy is the resolver for the upsertRlsPolicy field.
func (r *mutationResolver) UpsertRlsPolicy(ctx context.Context, modelID string, input generated.RlsPolicyInput) (*generated.UpsertRlsPolicyPayload, error) {
	panic(fmt.Errorf("not implemented: UpsertRlsPolicy - upsertRlsPolicy"))
}

// DeleteRlsPolicy is the resolver for the deleteRlsPolicy field.
func (r *mutationResolver) DeleteRlsPolicy(ctx context.Context, id string) (*generated.DeleteRlsPolicyPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteRlsPolicy - deleteRlsPolicy"))
}

// DeleteRlsPoliciesByModel is the resolver for the deleteRlsPoliciesByModel field.
func (r *mutationResolver) DeleteRlsPoliciesByModel(ctx context.Context, modelID string) (*generated.DeleteRlsPolicyPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteRlsPoliciesByModel - deleteRlsPoliciesByModel"))
}

// RlsPolicies is the resolver for the rlsPolicies field.
func (r *queryResolver) RlsPolicies(ctx context.Context, modelID string) ([]*generated.RlsPolicy, error) {
	panic(fmt.Errorf("not implemented: RlsPolicies - rlsPolicies"))
}
