package middleware

import (
	"net/http"
	"time"

	chiMiddleware "github.com/go-chi/chi/v5/middleware"
	"github.com/rs/zerolog/log"
	"go.opentelemetry.io/otel/trace"
)

// RequestLogger logs each incoming request with method, path, status, duration,
// and all tracing identifiers: request_id, client_request_id, trace_id, span_id.
func RequestLogger(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		rw := &responseWriter{ResponseWriter: w, status: http.StatusOK}

		next.ServeHTTP(rw, r)

		// request_id — generated by middleware.RequestID (always present)
		reqID := chiMiddleware.GetReqID(r.Context())

		// client_request_id — original ID sent by the browser (may be absent)
		clientReqID := GetClientRequestID(r)

		// trace_id / span_id — from the OTel span injected by otelchi
		var traceID, spanID string
		if sc := trace.SpanFromContext(r.Context()).SpanContext(); sc.IsValid() {
			traceID = sc.TraceID().String()
			spanID = sc.SpanID().String()
		}

		evt := log.Ctx(r.Context()).Info().
			Str("method", r.Method).
			Str("path", r.URL.Path).
			Int("status", rw.status).
			Dur("duration", time.Since(start)).
			Str("request_id", reqID)

		if clientReqID != "" {
			evt = evt.Str("client_request_id", clientReqID)
		}
		if traceID != "" {
			evt = evt.Str("trace_id", traceID).Str("span_id", spanID)
		}

		evt.Msg("request")
	})
}

type responseWriter struct {
	http.ResponseWriter
	status int
}

func (rw *responseWriter) WriteHeader(code int) {
	rw.status = code
	rw.ResponseWriter.WriteHeader(code)
}
