// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package dbgen

import (
	"context"
	"database/sql"
)

const countActiveAPIKeysByUserID = `-- name: CountActiveAPIKeysByUserID :one
SELECT COUNT(*) FROM api_keys
WHERE user_id = ? AND revoked_at IS NULL
`

func (q *Queries) CountActiveAPIKeysByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAPIKeysByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRevokedAPIKeys = `-- name: DeleteRevokedAPIKeys :exec
DELETE FROM api_keys
WHERE revoked_at IS NOT NULL AND revoked_at < DATE_SUB(NOW(), INTERVAL 90 DAY)
`

func (q *Queries) DeleteRevokedAPIKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRevokedAPIKeys)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, key_hash, key_prefix, last_used_at, expires_at, created_at, revoked_at
FROM api_keys
WHERE key_hash = ?
LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, user_id, name, key_hash, key_prefix, last_used_at, expires_at, created_at, revoked_at
FROM api_keys
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys (id, user_id, name, key_hash, key_prefix, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, NOW())
`

type InsertAPIKeyParams struct {
	ID        string
	UserID    string
	Name      string
	KeyHash   string
	KeyPrefix string
	ExpiresAt sql.NullTime
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.ExpiresAt,
	)
	return err
}

const listAPIKeysByUserID = `-- name: ListAPIKeysByUserID :many
SELECT id, user_id, name, key_hash, key_prefix, last_used_at, expires_at, created_at, revoked_at
FROM api_keys
WHERE user_id = ? AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUserID(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = ? AND user_id = ?
`

type RevokeAPIKeyParams struct {
	ID     string
	UserID string
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE api_keys
SET name = ?, expires_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateAPIKeyParams struct {
	Name      string
	ExpiresAt sql.NullTime
	ID        string
	UserID    string
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKey,
		arg.Name,
		arg.ExpiresAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = ?
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}
