// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authz.sql

package dbgen

import (
	"context"
	"strings"
)

const getBundleIDsByImplicitRoles = `-- name: GetBundleIDsByImplicitRoles :many
SELECT DISTINCT rb.bundle_id
FROM project_roles r
  JOIN end_user_role_bundles rb
    ON r.id = rb.role_id
   AND r.org_name = rb.org_name
WHERE r.org_name = ?
  AND rb.project_slug = ?
  AND r.is_implicit = TRUE AND ` + "`" + `r` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
`

type GetBundleIDsByImplicitRolesParams struct {
	OrgName     string
	ProjectSlug string
}

// ⚡ 鉴权链 Step 3: 隐式角色关联的权限包 ID 列表（对所有认证用户执行，无需 user_id）
func (q *Queries) GetBundleIDsByImplicitRoles(ctx context.Context, arg GetBundleIDsByImplicitRolesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBundleIDsByImplicitRoles, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bundle_id string
		if err := rows.Scan(&bundle_id); err != nil {
			return nil, err
		}
		items = append(items, bundle_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBundleIDsByUserDirect = `-- name: GetBundleIDsByUserDirect :many
SELECT bundle_id
FROM end_user_user_bundles
WHERE user_id = ?
  AND org_name = ?
  AND project_slug = ?
`

type GetBundleIDsByUserDirectParams struct {
	UserID      string
	OrgName     string
	ProjectSlug string
}

// ⚡ 鉴权链 Step 1: 用户直接关联的权限包 ID 列表
func (q *Queries) GetBundleIDsByUserDirect(ctx context.Context, arg GetBundleIDsByUserDirectParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBundleIDsByUserDirect, arg.UserID, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bundle_id string
		if err := rows.Scan(&bundle_id); err != nil {
			return nil, err
		}
		items = append(items, bundle_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBundleIDsByUserExplicitRoles = `-- name: GetBundleIDsByUserExplicitRoles :many
SELECT DISTINCT rb.bundle_id
FROM project_role_users ur
  JOIN end_user_role_bundles rb
    ON ur.role_id = rb.role_id
   AND ur.org_name = rb.org_name
WHERE ur.user_id = ?
  AND ur.org_name = ?
  AND rb.project_slug = ?
`

type GetBundleIDsByUserExplicitRolesParams struct {
	UserID      string
	OrgName     string
	ProjectSlug string
}

// ⚡ 鉴权链 Step 2: 通过显式角色关联的权限包 ID 列表（单次 JOIN 查询，避免 N+1）
func (q *Queries) GetBundleIDsByUserExplicitRoles(ctx context.Context, arg GetBundleIDsByUserExplicitRolesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBundleIDsByUserExplicitRoles, arg.UserID, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bundle_id string
		if err := rows.Scan(&bundle_id); err != nil {
			return nil, err
		}
		items = append(items, bundle_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomPermissionsByIDs = `-- name: GetCustomPermissionsByIDs :many
SELECT p.id, p.org_name, p.project_slug, p.database_name, p.model_name, p.model_id, p.name, p.description, p.column_policy, p.row_policy, p.created_at, p.updated_at, p.deleted_at, p.delete_token
FROM end_user_data_permissions p
WHERE p.id IN (/*SLICE:permissionids*/?)
  AND p.org_name = ?
  AND ` + "`" + `p` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
`

type GetCustomPermissionsByIDsParams struct {
	Permissionids []string
	OrgName       string
}

// ⚡ 鉴权链 Step 5: 批量加载 custom permission 实体（CUSTOM item 引用）
func (q *Queries) GetCustomPermissionsByIDs(ctx context.Context, arg GetCustomPermissionsByIDsParams) ([]EndUserDataPermission, error) {
	query := getCustomPermissionsByIDs
	var queryParams []interface{}
	if len(arg.Permissionids) > 0 {
		for _, v := range arg.Permissionids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:permissionids*/?", strings.Repeat(",?", len(arg.Permissionids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:permissionids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OrgName)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserDataPermission
	for rows.Next() {
		var i EndUserDataPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.DatabaseName,
			&i.ModelName,
			&i.ModelID,
			&i.Name,
			&i.Description,
			&i.ColumnPolicy,
			&i.RowPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeleteToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataPermissionItemsByBundleIDs = `-- name: GetDataPermissionItemsByBundleIDs :many
SELECT i.id, i.bundle_id, i.model_id, i.grant_type, i.preset, i.custom_permission_id, i.sort_order, i.created_at, i.updated_at
FROM end_user_bundle_data_permission_items i
WHERE i.bundle_id IN (/*SLICE:bundleids*/?)
`

// ⚡ 鉴权链 Step 4: 展开权限包 → data permission items
func (q *Queries) GetDataPermissionItemsByBundleIDs(ctx context.Context, bundleids []string) ([]EndUserBundleDataPermissionItem, error) {
	query := getDataPermissionItemsByBundleIDs
	var queryParams []interface{}
	if len(bundleids) > 0 {
		for _, v := range bundleids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:bundleids*/?", strings.Repeat(",?", len(bundleids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:bundleids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserBundleDataPermissionItem
	for rows.Next() {
		var i EndUserBundleDataPermissionItem
		if err := rows.Scan(
			&i.ID,
			&i.BundleID,
			&i.ModelID,
			&i.GrantType,
			&i.Preset,
			&i.CustomPermissionID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
