// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bundle_snapshot.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const deleteOldBundleSnapshots = `-- name: DeleteOldBundleSnapshots :exec
DELETE snap
FROM end_user_permission_bundle_snapshots snap
LEFT JOIN (
  SELECT s.id AS keep_id
  FROM end_user_permission_bundle_snapshots s
  WHERE s.bundle_id = ?
  ORDER BY s.version DESC
  LIMIT 5
) AS latest ON snap.id = latest.keep_id
WHERE snap.bundle_id = ?
  AND latest.keep_id IS NULL
`

type DeleteOldBundleSnapshotsParams struct {
	BundleID   string
	BundleID_2 string
}

func (q *Queries) DeleteOldBundleSnapshots(ctx context.Context, arg DeleteOldBundleSnapshotsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldBundleSnapshots, arg.BundleID, arg.BundleID_2)
	return err
}

const getBundleCurrentVersion = `-- name: GetBundleCurrentVersion :one
SELECT COALESCE(MAX(version), 0) AS current_version
FROM end_user_permission_bundle_snapshots
WHERE bundle_id = ?
`

func (q *Queries) GetBundleCurrentVersion(ctx context.Context, bundleID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getBundleCurrentVersion, bundleID)
	var current_version interface{}
	err := row.Scan(&current_version)
	return current_version, err
}

const getBundleSnapshotByVersion = `-- name: GetBundleSnapshotByVersion :one
SELECT id, bundle_id, version, items, created_at, created_by, restored_from
FROM end_user_permission_bundle_snapshots
WHERE bundle_id = ?
  AND version = ?
`

type GetBundleSnapshotByVersionParams struct {
	BundleID string
	Version  int32
}

func (q *Queries) GetBundleSnapshotByVersion(ctx context.Context, arg GetBundleSnapshotByVersionParams) (EndUserPermissionBundleSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getBundleSnapshotByVersion, arg.BundleID, arg.Version)
	var i EndUserPermissionBundleSnapshot
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.Version,
		&i.Items,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.RestoredFrom,
	)
	return i, err
}

const insertBundleSnapshot = `-- name: InsertBundleSnapshot :exec
INSERT INTO end_user_permission_bundle_snapshots (
  id,
  bundle_id,
  version,
  items,
  created_by,
  restored_from
)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertBundleSnapshotParams struct {
	ID           string
	BundleID     string
	Version      int32
	Items        json.RawMessage
	CreatedBy    sql.NullString
	RestoredFrom sql.NullInt32
}

func (q *Queries) InsertBundleSnapshot(ctx context.Context, arg InsertBundleSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertBundleSnapshot,
		arg.ID,
		arg.BundleID,
		arg.Version,
		arg.Items,
		arg.CreatedBy,
		arg.RestoredFrom,
	)
	return err
}

const listBundleSnapshots = `-- name: ListBundleSnapshots :many
SELECT id, bundle_id, version, items, created_at, created_by, restored_from
FROM end_user_permission_bundle_snapshots
WHERE bundle_id = ?
ORDER BY version DESC
LIMIT 5
`

func (q *Queries) ListBundleSnapshots(ctx context.Context, bundleID string) ([]EndUserPermissionBundleSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listBundleSnapshots, bundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserPermissionBundleSnapshot
	for rows.Next() {
		var i EndUserPermissionBundleSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.BundleID,
			&i.Version,
			&i.Items,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.RestoredFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
