// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bundle.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addPermissionToBundle = `-- name: AddPermissionToBundle :exec
INSERT INTO end_user_bundle_permissions (
  id,
  bundle_id,
  permission_id,
  sort_order
)
VALUES (?, ?, ?, ?)
`

type AddPermissionToBundleParams struct {
	ID           string
	BundleID     string
	PermissionID string
	SortOrder    int32
}

func (q *Queries) AddPermissionToBundle(ctx context.Context, arg AddPermissionToBundleParams) error {
	_, err := q.db.ExecContext(ctx, addPermissionToBundle,
		arg.ID,
		arg.BundleID,
		arg.PermissionID,
		arg.SortOrder,
	)
	return err
}

const createEndUserBundle = `-- name: CreateEndUserBundle :exec
INSERT INTO end_user_permission_bundles (
  id,
  org_name,
  project_slug,
  name,
  description
)
VALUES (?, ?, ?, ?, ?)
`

type CreateEndUserBundleParams struct {
	ID          string
	OrgName     string
	ProjectSlug string
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateEndUserBundle(ctx context.Context, arg CreateEndUserBundleParams) error {
	_, err := q.db.ExecContext(ctx, createEndUserBundle,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.Name,
		arg.Description,
	)
	return err
}

const deleteEndUserBundle = `-- name: DeleteEndUserBundle :execresult
DELETE FROM end_user_permission_bundles
WHERE id = ?
  AND org_name = ?
`

type DeleteEndUserBundleParams struct {
	ID      string
	OrgName string
}

func (q *Queries) DeleteEndUserBundle(ctx context.Context, arg DeleteEndUserBundleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEndUserBundle, arg.ID, arg.OrgName)
}

const getEndUserBundleByID = `-- name: GetEndUserBundleByID :one
SELECT id, org_name, project_slug, name, description, created_at, updated_at
FROM end_user_permission_bundles
WHERE id = ?
  AND org_name = ?
`

type GetEndUserBundleByIDParams struct {
	ID      string
	OrgName string
}

func (q *Queries) GetEndUserBundleByID(ctx context.Context, arg GetEndUserBundleByIDParams) (EndUserPermissionBundle, error) {
	row := q.db.QueryRowContext(ctx, getEndUserBundleByID, arg.ID, arg.OrgName)
	var i EndUserPermissionBundle
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEndUserBundlesByProject = `-- name: ListEndUserBundlesByProject :many
SELECT id, org_name, project_slug, name, description, created_at, updated_at
FROM end_user_permission_bundles
WHERE org_name = ?
  AND project_slug = ?
ORDER BY name
`

type ListEndUserBundlesByProjectParams struct {
	OrgName     string
	ProjectSlug string
}

func (q *Queries) ListEndUserBundlesByProject(ctx context.Context, arg ListEndUserBundlesByProjectParams) ([]EndUserPermissionBundle, error) {
	rows, err := q.db.QueryContext(ctx, listEndUserBundlesByProject, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserPermissionBundle
	for rows.Next() {
		var i EndUserPermissionBundle
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsInBundle = `-- name: ListPermissionsInBundle :many
SELECT p.id, p.org_name, p.project_slug, p.model_id, p.name, p.description, p.action, p.column_policy, p.row_scope, p.created_at, p.updated_at
FROM end_user_permissions p
  JOIN end_user_bundle_permissions bp ON p.id = bp.permission_id
WHERE bp.bundle_id = ?
ORDER BY bp.sort_order, bp.created_at
`

func (q *Queries) ListPermissionsInBundle(ctx context.Context, bundleID string) ([]EndUserPermission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsInBundle, bundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserPermission
	for rows.Next() {
		var i EndUserPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.ModelID,
			&i.Name,
			&i.Description,
			&i.Action,
			&i.ColumnPolicy,
			&i.RowScope,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionFromBundle = `-- name: RemovePermissionFromBundle :execresult
DELETE FROM end_user_bundle_permissions
WHERE bundle_id = ?
  AND permission_id = ?
`

type RemovePermissionFromBundleParams struct {
	BundleID     string
	PermissionID string
}

func (q *Queries) RemovePermissionFromBundle(ctx context.Context, arg RemovePermissionFromBundleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, removePermissionFromBundle, arg.BundleID, arg.PermissionID)
}

const updateEndUserBundle = `-- name: UpdateEndUserBundle :execresult
UPDATE end_user_permission_bundles
SET name = ?,
    description = ?,
    updated_at = NOW(3)
WHERE id = ?
  AND org_name = ?
`

type UpdateEndUserBundleParams struct {
	Name        string
	Description sql.NullString
	ID          string
	OrgName     string
}

func (q *Queries) UpdateEndUserBundle(ctx context.Context, arg UpdateEndUserBundleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEndUserBundle,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.OrgName,
	)
}
