// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: casbin.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createPermission = `-- name: CreatePermission :exec
INSERT INTO role_permissions (role_id, org_name, obj, act, created_at)
VALUES (?, ?, ?, ?, NOW(3))
`

type CreatePermissionParams struct {
	RoleID  int64
	OrgName string
	Obj     string
	Act     string
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission,
		arg.RoleID,
		arg.OrgName,
		arg.Obj,
		arg.Act,
	)
	return err
}

const createRole = `-- name: CreateRole :execresult
INSERT INTO roles (name, description, is_system, org_name, created_at, updated_at)
VALUES (?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateRoleParams struct {
	Name        string
	Description sql.NullString
	IsSystem    bool
	OrgName     string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRole,
		arg.Name,
		arg.Description,
		arg.IsSystem,
		arg.OrgName,
	)
}

const createUserRole = `-- name: CreateUserRole :execresult
INSERT INTO user_roles (user_id, role_id, org_name, created_at)
VALUES (?, ?, ?, NOW(3))
`

type CreateUserRoleParams struct {
	UserID  string
	RoleID  int64
	OrgName string
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserRole, arg.UserID, arg.RoleID, arg.OrgName)
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM role_permissions
WHERE role_id = ? AND obj = ? AND act = ?
`

type DeletePermissionParams struct {
	RoleID int64
	Obj    string
	Act    string
}

func (q *Queries) DeletePermission(ctx context.Context, arg DeletePermissionParams) error {
	_, err := q.db.ExecContext(ctx, deletePermission, arg.RoleID, arg.Obj, arg.Act)
	return err
}

const deletePermissionsByRole = `-- name: DeletePermissionsByRole :exec
DELETE FROM role_permissions WHERE role_id = ?
`

func (q *Queries) DeletePermissionsByRole(ctx context.Context, roleID int64) error {
	_, err := q.db.ExecContext(ctx, deletePermissionsByRole, roleID)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = ?
`

func (q *Queries) DeleteRole(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const deleteUserRole = `-- name: DeleteUserRole :exec
DELETE FROM user_roles
WHERE user_id = ? AND role_id = ? AND org_name = ?
`

type DeleteUserRoleParams struct {
	UserID  string
	RoleID  int64
	OrgName string
}

func (q *Queries) DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserRole, arg.UserID, arg.RoleID, arg.OrgName)
	return err
}

const deleteUserRolesByRole = `-- name: DeleteUserRolesByRole :exec
DELETE FROM user_roles WHERE role_id = ?
`

func (q *Queries) DeleteUserRolesByRole(ctx context.Context, roleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserRolesByRole, roleID)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, is_system, org_name, created_at, updated_at FROM roles WHERE id = ? LIMIT 1
`

func (q *Queries) GetRoleByID(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.OrgName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system, org_name, created_at, updated_at FROM roles WHERE name = ? LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.OrgName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByNameAndOrg = `-- name: GetRoleByNameAndOrg :one
SELECT id, name, description, is_system, org_name, created_at, updated_at FROM roles WHERE name = ? AND org_name = ? LIMIT 1
`

type GetRoleByNameAndOrgParams struct {
	Name    string
	OrgName string
}

func (q *Queries) GetRoleByNameAndOrg(ctx context.Context, arg GetRoleByNameAndOrgParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByNameAndOrg, arg.Name, arg.OrgName)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.OrgName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemRoleByName = `-- name: GetSystemRoleByName :one
SELECT id, name, description, is_system, org_name, created_at, updated_at FROM roles WHERE name = ? AND is_system = true LIMIT 1
`

func (q *Queries) GetSystemRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getSystemRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.OrgName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT id, user_id, role_id, org_name, created_at FROM user_roles
WHERE user_id = ? AND role_id = ? AND org_name = ?
LIMIT 1
`

type GetUserRoleParams struct {
	UserID  string
	RoleID  int64
	OrgName string
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, arg.UserID, arg.RoleID, arg.OrgName)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.OrgName,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissionsByRole = `-- name: ListPermissionsByRole :many
SELECT id, role_id, org_name, obj, act, created_at FROM role_permissions WHERE role_id = ?
`

func (q *Queries) ListPermissionsByRole(ctx context.Context, roleID int64) ([]RolePermission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.OrgName,
			&i.Obj,
			&i.Act,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByRoleAndOrg = `-- name: ListPermissionsByRoleAndOrg :many
SELECT id, role_id, org_name, obj, act, created_at FROM role_permissions
WHERE role_id = ? AND org_name = ?
`

type ListPermissionsByRoleAndOrgParams struct {
	RoleID  int64
	OrgName string
}

func (q *Queries) ListPermissionsByRoleAndOrg(ctx context.Context, arg ListPermissionsByRoleAndOrgParams) ([]RolePermission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByRoleAndOrg, arg.RoleID, arg.OrgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.OrgName,
			&i.Obj,
			&i.Act,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleUsers = `-- name: ListRoleUsers :many
SELECT id, user_id, role_id, org_name, created_at FROM user_roles
WHERE role_id = ? AND org_name = ?
`

type ListRoleUsersParams struct {
	RoleID  int64
	OrgName string
}

func (q *Queries) ListRoleUsers(ctx context.Context, arg ListRoleUsersParams) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, listRoleUsers, arg.RoleID, arg.OrgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.OrgName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, is_system, org_name, created_at, updated_at FROM roles ORDER BY name ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.OrgName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByOrg = `-- name: ListRolesByOrg :many
SELECT id, name, description, is_system, org_name, created_at, updated_at FROM roles
WHERE org_name = ?
ORDER BY name ASC
`

func (q *Queries) ListRolesByOrg(ctx context.Context, orgName string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByOrg, orgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.OrgName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByOrgIncludeSystem = `-- name: ListRolesByOrgIncludeSystem :many
SELECT id, name, description, is_system, org_name, created_at, updated_at FROM roles
WHERE org_name = ? OR org_name = '__SYSTEM__'
ORDER BY name ASC
`

func (q *Queries) ListRolesByOrgIncludeSystem(ctx context.Context, orgName string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByOrgIncludeSystem, orgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.OrgName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT id, user_id, role_id, org_name, created_at FROM user_roles
WHERE user_id = ? AND org_name = ?
`

type ListUserRolesParams struct {
	UserID  string
	OrgName string
}

func (q *Queries) ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles, arg.UserID, arg.OrgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.OrgName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles
SET description = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateRoleParams struct {
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole, arg.Description, arg.ID)
	return err
}
