// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: field.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
)

const countFieldsByEnumRelationID = `-- name: CountFieldsByEnumRelationID :one
SELECT COUNT(*) FROM field_definitions
WHERE org_name = ? AND enum_relation_id = ?
`

type CountFieldsByEnumRelationIDParams struct {
	OrgName        string
	EnumRelationID sql.NullString
}

func (q *Queries) CountFieldsByEnumRelationID(ctx context.Context, arg CountFieldsByEnumRelationIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFieldsByEnumRelationID, arg.OrgName, arg.EnumRelationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFieldsByModelID = `-- name: CountFieldsByModelID :one
SELECT COUNT(*) FROM field_definitions WHERE model_id = ?
`

func (q *Queries) CountFieldsByModelID(ctx context.Context, modelID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFieldsByModelID, modelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFieldDefinition = `-- name: CreateFieldDefinition :exec
INSERT INTO field_definitions (model_id, org_name, project_slug, model_name, database_name, name, enum_name, enum_relation_id, title, description, format, non_null, required, is_unique, is_primary, is_deprecated, status, validation, display_order, metadata, relate_fk_id, belongs_to_fk_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateFieldDefinitionParams struct {
	ModelID        string
	OrgName        string
	ProjectSlug    string
	ModelName      string
	DatabaseName   string
	Name           string
	EnumName       sql.NullString
	EnumRelationID sql.NullString
	Title          string
	Description    sql.NullString
	Format         string
	NonNull        sql.NullBool
	Required       sql.NullBool
	IsUnique       sql.NullBool
	IsPrimary      sql.NullBool
	IsDeprecated   sql.NullBool
	Status         string
	Validation     *json.RawMessage
	DisplayOrder   string
	Metadata       *json.RawMessage
	RelateFkID     sql.NullString
	BelongsToFkID  sql.NullString
}

func (q *Queries) CreateFieldDefinition(ctx context.Context, arg CreateFieldDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, createFieldDefinition,
		arg.ModelID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.ModelName,
		arg.DatabaseName,
		arg.Name,
		arg.EnumName,
		arg.EnumRelationID,
		arg.Title,
		arg.Description,
		arg.Format,
		arg.NonNull,
		arg.Required,
		arg.IsUnique,
		arg.IsPrimary,
		arg.IsDeprecated,
		arg.Status,
		arg.Validation,
		arg.DisplayOrder,
		arg.Metadata,
		arg.RelateFkID,
		arg.BelongsToFkID,
	)
	return err
}

const deleteFieldsByModelID = `-- name: DeleteFieldsByModelID :exec
DELETE FROM field_definitions WHERE model_id = ?
`

func (q *Queries) DeleteFieldsByModelID(ctx context.Context, modelID string) error {
	_, err := q.db.ExecContext(ctx, deleteFieldsByModelID, modelID)
	return err
}

const deleteFieldsByNames = `-- name: DeleteFieldsByNames :execresult
DELETE FROM field_definitions
WHERE model_id = ? AND name IN (/*SLICE:names*/?)
`

type DeleteFieldsByNamesParams struct {
	ModelID string
	Names   []string
}

func (q *Queries) DeleteFieldsByNames(ctx context.Context, arg DeleteFieldsByNamesParams) (sql.Result, error) {
	query := deleteFieldsByNames
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ModelID)
	if len(arg.Names) > 0 {
		for _, v := range arg.Names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(arg.Names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	return q.db.ExecContext(ctx, query, queryParams...)
}

const existsFieldByName = `-- name: ExistsFieldByName :one
SELECT COUNT(*) FROM field_definitions WHERE model_id = ? AND name = ?
`

type ExistsFieldByNameParams struct {
	ModelID string
	Name    string
}

func (q *Queries) ExistsFieldByName(ctx context.Context, arg ExistsFieldByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsFieldByName, arg.ModelID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFieldByModelIDAndName = `-- name: GetFieldByModelIDAndName :one
SELECT model_id, name, org_name, project_slug, model_name, database_name, enum_name, enum_relation_id, belongs_to_fk_id, relate_fk_id, title, description, format, non_null, required, is_unique, is_primary, is_deprecated, status, validation, display_order, metadata, created_at, updated_at FROM field_definitions
WHERE model_id = ? AND name = ?
LIMIT 1
`

type GetFieldByModelIDAndNameParams struct {
	ModelID string
	Name    string
}

func (q *Queries) GetFieldByModelIDAndName(ctx context.Context, arg GetFieldByModelIDAndNameParams) (FieldDefinition, error) {
	row := q.db.QueryRowContext(ctx, getFieldByModelIDAndName, arg.ModelID, arg.Name)
	var i FieldDefinition
	err := row.Scan(
		&i.ModelID,
		&i.Name,
		&i.OrgName,
		&i.ProjectSlug,
		&i.ModelName,
		&i.DatabaseName,
		&i.EnumName,
		&i.EnumRelationID,
		&i.BelongsToFkID,
		&i.RelateFkID,
		&i.Title,
		&i.Description,
		&i.Format,
		&i.NonNull,
		&i.Required,
		&i.IsUnique,
		&i.IsPrimary,
		&i.IsDeprecated,
		&i.Status,
		&i.Validation,
		&i.DisplayOrder,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFieldsByModelID = `-- name: GetFieldsByModelID :many
SELECT model_id, name, org_name, project_slug, model_name, database_name, enum_name, enum_relation_id, belongs_to_fk_id, relate_fk_id, title, description, format, non_null, required, is_unique, is_primary, is_deprecated, status, validation, display_order, metadata, created_at, updated_at FROM field_definitions
WHERE model_id = ?
ORDER BY display_order ASC
`

func (q *Queries) GetFieldsByModelID(ctx context.Context, modelID string) ([]FieldDefinition, error) {
	rows, err := q.db.QueryContext(ctx, getFieldsByModelID, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FieldDefinition
	for rows.Next() {
		var i FieldDefinition
		if err := rows.Scan(
			&i.ModelID,
			&i.Name,
			&i.OrgName,
			&i.ProjectSlug,
			&i.ModelName,
			&i.DatabaseName,
			&i.EnumName,
			&i.EnumRelationID,
			&i.BelongsToFkID,
			&i.RelateFkID,
			&i.Title,
			&i.Description,
			&i.Format,
			&i.NonNull,
			&i.Required,
			&i.IsUnique,
			&i.IsPrimary,
			&i.IsDeprecated,
			&i.Status,
			&i.Validation,
			&i.DisplayOrder,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTailFieldDisplayOrder = `-- name: GetTailFieldDisplayOrder :one
SELECT display_order FROM field_definitions
WHERE model_id = ?
ORDER BY display_order DESC
LIMIT 1
`

func (q *Queries) GetTailFieldDisplayOrder(ctx context.Context, modelID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTailFieldDisplayOrder, modelID)
	var display_order string
	err := row.Scan(&display_order)
	return display_order, err
}

const updateField = `-- name: UpdateField :execresult
UPDATE field_definitions
SET title = ?, description = ?, non_null = ?, required = ?, is_unique = ?, is_primary = ?, is_deprecated = ?, status = ?, validation = ?, display_order = ?, metadata = ?, enum_relation_id = ?, updated_at = NOW(3)
WHERE model_id = ? AND name = ?
`

type UpdateFieldParams struct {
	Title          string
	Description    sql.NullString
	NonNull        sql.NullBool
	Required       sql.NullBool
	IsUnique       sql.NullBool
	IsPrimary      sql.NullBool
	IsDeprecated   sql.NullBool
	Status         string
	Validation     *json.RawMessage
	DisplayOrder   string
	Metadata       *json.RawMessage
	EnumRelationID sql.NullString
	ModelID        string
	Name           string
}

func (q *Queries) UpdateField(ctx context.Context, arg UpdateFieldParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateField,
		arg.Title,
		arg.Description,
		arg.NonNull,
		arg.Required,
		arg.IsUnique,
		arg.IsPrimary,
		arg.IsDeprecated,
		arg.Status,
		arg.Validation,
		arg.DisplayOrder,
		arg.Metadata,
		arg.EnumRelationID,
		arg.ModelID,
		arg.Name,
	)
}

const updateFieldDisplayOrder = `-- name: UpdateFieldDisplayOrder :exec
UPDATE field_definitions
SET display_order = ?, updated_at = NOW(3)
WHERE model_id = ? AND name = ?
`

type UpdateFieldDisplayOrderParams struct {
	DisplayOrder string
	ModelID      string
	Name         string
}

func (q *Queries) UpdateFieldDisplayOrder(ctx context.Context, arg UpdateFieldDisplayOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateFieldDisplayOrder, arg.DisplayOrder, arg.ModelID, arg.Name)
	return err
}

const updateFieldsStatus = `-- name: UpdateFieldsStatus :exec
UPDATE field_definitions
SET status = ?, updated_at = NOW(3)
WHERE model_id = ? AND name IN (/*SLICE:names*/?)
`

type UpdateFieldsStatusParams struct {
	Status  string
	ModelID string
	Names   []string
}

func (q *Queries) UpdateFieldsStatus(ctx context.Context, arg UpdateFieldsStatusParams) error {
	query := updateFieldsStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.ModelID)
	if len(arg.Names) > 0 {
		for _, v := range arg.Names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(arg.Names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}
