// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logical_foreign_key.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createLogicalForeignKey = `-- name: CreateLogicalForeignKey :exec
INSERT INTO logical_foreign_keys (id, pair_id, direction, model_id, model_name, ref_model_id, ref_model_name, source_fields, target_fields, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateLogicalForeignKeyParams struct {
	ID           string
	PairID       string
	Direction    LogicalForeignKeysDirection
	ModelID      string
	ModelName    string
	RefModelID   string
	RefModelName string
	SourceFields json.RawMessage
	TargetFields json.RawMessage
}

func (q *Queries) CreateLogicalForeignKey(ctx context.Context, arg CreateLogicalForeignKeyParams) error {
	_, err := q.db.ExecContext(ctx, createLogicalForeignKey,
		arg.ID,
		arg.PairID,
		arg.Direction,
		arg.ModelID,
		arg.ModelName,
		arg.RefModelID,
		arg.RefModelName,
		arg.SourceFields,
		arg.TargetFields,
	)
	return err
}

const deleteLogicalForeignKeyByPairID = `-- name: DeleteLogicalForeignKeyByPairID :exec
DELETE FROM logical_foreign_keys WHERE pair_id = ?
`

func (q *Queries) DeleteLogicalForeignKeyByPairID(ctx context.Context, pairID string) error {
	_, err := q.db.ExecContext(ctx, deleteLogicalForeignKeyByPairID, pairID)
	return err
}

const findFieldsByBelongsToFKID = `-- name: FindFieldsByBelongsToFKID :many
SELECT model_id, name, org_name, project_slug, model_name, database_name, parent_relation_id, enum_name, enum_relation_id, belongs_to_fk_id, relate_fk_id, title, description, format, non_null, required, is_unique, is_primary, status, validation, display_order, metadata, created_at, updated_at
FROM field_definitions
WHERE belongs_to_fk_id = ?
`

type FindFieldsByBelongsToFKIDRow struct {
	ModelID          string
	Name             string
	OrgName          string
	ProjectSlug      string
	ModelName        string
	DatabaseName     string
	ParentRelationID sql.NullString
	EnumName         sql.NullString
	EnumRelationID   sql.NullString
	BelongsToFkID    sql.NullString
	RelateFkID       sql.NullString
	Title            string
	Description      sql.NullString
	Format           string
	NonNull          sql.NullBool
	Required         sql.NullBool
	IsUnique         sql.NullBool
	IsPrimary        sql.NullBool
	Status           string
	Validation       *json.RawMessage
	DisplayOrder     string
	Metadata         *json.RawMessage
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) FindFieldsByBelongsToFKID(ctx context.Context, belongsToFkID sql.NullString) ([]FindFieldsByBelongsToFKIDRow, error) {
	rows, err := q.db.QueryContext(ctx, findFieldsByBelongsToFKID, belongsToFkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFieldsByBelongsToFKIDRow
	for rows.Next() {
		var i FindFieldsByBelongsToFKIDRow
		if err := rows.Scan(
			&i.ModelID,
			&i.Name,
			&i.OrgName,
			&i.ProjectSlug,
			&i.ModelName,
			&i.DatabaseName,
			&i.ParentRelationID,
			&i.EnumName,
			&i.EnumRelationID,
			&i.BelongsToFkID,
			&i.RelateFkID,
			&i.Title,
			&i.Description,
			&i.Format,
			&i.NonNull,
			&i.Required,
			&i.IsUnique,
			&i.IsPrimary,
			&i.Status,
			&i.Validation,
			&i.DisplayOrder,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFieldsByRelateFKID = `-- name: FindFieldsByRelateFKID :many
SELECT model_id, name, org_name, project_slug, model_name, database_name, parent_relation_id, enum_name, enum_relation_id, belongs_to_fk_id, relate_fk_id, title, description, format, non_null, required, is_unique, is_primary, status, validation, display_order, metadata, created_at, updated_at
FROM field_definitions
WHERE relate_fk_id = ?
`

type FindFieldsByRelateFKIDRow struct {
	ModelID          string
	Name             string
	OrgName          string
	ProjectSlug      string
	ModelName        string
	DatabaseName     string
	ParentRelationID sql.NullString
	EnumName         sql.NullString
	EnumRelationID   sql.NullString
	BelongsToFkID    sql.NullString
	RelateFkID       sql.NullString
	Title            string
	Description      sql.NullString
	Format           string
	NonNull          sql.NullBool
	Required         sql.NullBool
	IsUnique         sql.NullBool
	IsPrimary        sql.NullBool
	Status           string
	Validation       *json.RawMessage
	DisplayOrder     string
	Metadata         *json.RawMessage
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) FindFieldsByRelateFKID(ctx context.Context, relateFkID sql.NullString) ([]FindFieldsByRelateFKIDRow, error) {
	rows, err := q.db.QueryContext(ctx, findFieldsByRelateFKID, relateFkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFieldsByRelateFKIDRow
	for rows.Next() {
		var i FindFieldsByRelateFKIDRow
		if err := rows.Scan(
			&i.ModelID,
			&i.Name,
			&i.OrgName,
			&i.ProjectSlug,
			&i.ModelName,
			&i.DatabaseName,
			&i.ParentRelationID,
			&i.EnumName,
			&i.EnumRelationID,
			&i.BelongsToFkID,
			&i.RelateFkID,
			&i.Title,
			&i.Description,
			&i.Format,
			&i.NonNull,
			&i.Required,
			&i.IsUnique,
			&i.IsPrimary,
			&i.Status,
			&i.Validation,
			&i.DisplayOrder,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLogicalForeignKeysByModelID = `-- name: FindLogicalForeignKeysByModelID :many
SELECT id, pair_id, direction, model_id, model_name, ref_model_id, ref_model_name, source_fields, target_fields, created_at, updated_at
FROM logical_foreign_keys
WHERE model_id = ?
`

func (q *Queries) FindLogicalForeignKeysByModelID(ctx context.Context, modelID string) ([]LogicalForeignKey, error) {
	rows, err := q.db.QueryContext(ctx, findLogicalForeignKeysByModelID, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogicalForeignKey
	for rows.Next() {
		var i LogicalForeignKey
		if err := rows.Scan(
			&i.ID,
			&i.PairID,
			&i.Direction,
			&i.ModelID,
			&i.ModelName,
			&i.RefModelID,
			&i.RefModelName,
			&i.SourceFields,
			&i.TargetFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLogicalForeignKeysByPairID = `-- name: FindLogicalForeignKeysByPairID :many
SELECT id, pair_id, direction, model_id, model_name, ref_model_id, ref_model_name, source_fields, target_fields, created_at, updated_at
FROM logical_foreign_keys
WHERE pair_id = ?
`

func (q *Queries) FindLogicalForeignKeysByPairID(ctx context.Context, pairID string) ([]LogicalForeignKey, error) {
	rows, err := q.db.QueryContext(ctx, findLogicalForeignKeysByPairID, pairID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogicalForeignKey
	for rows.Next() {
		var i LogicalForeignKey
		if err := rows.Scan(
			&i.ID,
			&i.PairID,
			&i.Direction,
			&i.ModelID,
			&i.ModelName,
			&i.RefModelID,
			&i.RefModelName,
			&i.SourceFields,
			&i.TargetFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLogicalForeignKeysByRefModelID = `-- name: FindLogicalForeignKeysByRefModelID :many
SELECT id, pair_id, direction, model_id, model_name, ref_model_id, ref_model_name, source_fields, target_fields, created_at, updated_at
FROM logical_foreign_keys
WHERE ref_model_id = ?
`

func (q *Queries) FindLogicalForeignKeysByRefModelID(ctx context.Context, refModelID string) ([]LogicalForeignKey, error) {
	rows, err := q.db.QueryContext(ctx, findLogicalForeignKeysByRefModelID, refModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogicalForeignKey
	for rows.Next() {
		var i LogicalForeignKey
		if err := rows.Scan(
			&i.ID,
			&i.PairID,
			&i.Direction,
			&i.ModelID,
			&i.ModelName,
			&i.RefModelID,
			&i.RefModelName,
			&i.SourceFields,
			&i.TargetFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogicalForeignKeyByID = `-- name: GetLogicalForeignKeyByID :one
SELECT id, pair_id, direction, model_id, model_name, ref_model_id, ref_model_name, source_fields, target_fields, created_at, updated_at
FROM logical_foreign_keys
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetLogicalForeignKeyByID(ctx context.Context, id string) (LogicalForeignKey, error) {
	row := q.db.QueryRowContext(ctx, getLogicalForeignKeyByID, id)
	var i LogicalForeignKey
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.Direction,
		&i.ModelID,
		&i.ModelName,
		&i.RefModelID,
		&i.RefModelName,
		&i.SourceFields,
		&i.TargetFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
