// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_database.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countModelDatabaseCatalog = `-- name: CountModelDatabaseCatalog :one
SELECT COUNT(*) FROM model_database
WHERE org_name = ?
  AND project_slug = ?
  AND (? IS NULL OR name LIKE CONCAT('%', ?, '%'))
  AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
`

type CountModelDatabaseCatalogParams struct {
	OrgName      string
	ProjectSlug  string
	SearchFilter interface{}
	Search       interface{}
}

func (q *Queries) CountModelDatabaseCatalog(ctx context.Context, arg CountModelDatabaseCatalogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModelDatabaseCatalog,
		arg.OrgName,
		arg.ProjectSlug,
		arg.SearchFilter,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModelDatabase = `-- name: CreateModelDatabase :exec
INSERT INTO model_database (id, org_name, project_slug, cluster_id, name, title, description, mode, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateModelDatabaseParams struct {
	ID          string
	OrgName     string
	ProjectSlug string
	ClusterID   string
	Name        string
	Title       string
	Description sql.NullString
	Mode        ModelDatabaseMode
}

func (q *Queries) CreateModelDatabase(ctx context.Context, arg CreateModelDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, createModelDatabase,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.ClusterID,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.Mode,
	)
	return err
}

const createModelDatabaseSyncJob = `-- name: CreateModelDatabaseSyncJob :exec
INSERT INTO model_database_sync_job (
  id,
  org_name,
  project_slug,
  database_id,
  status,
  total_tables,
  processed_tables,
  created_models,
  synced_models,
  failed_count,
  failed_tables,
  deleted_at,
  delete_token,
  started_at,
  finished_at,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, 0, ?, ?, NOW(3), NOW(3))
`

type CreateModelDatabaseSyncJobParams struct {
	ID              string
	OrgName         string
	ProjectSlug     string
	DatabaseID      string
	Status          ModelDatabaseSyncJobStatus
	TotalTables     int32
	ProcessedTables int32
	CreatedModels   int32
	SyncedModels    int32
	FailedCount     int32
	FailedTables    json.RawMessage
	StartedAt       sql.NullTime
	FinishedAt      sql.NullTime
}

func (q *Queries) CreateModelDatabaseSyncJob(ctx context.Context, arg CreateModelDatabaseSyncJobParams) error {
	_, err := q.db.ExecContext(ctx, createModelDatabaseSyncJob,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.DatabaseID,
		arg.Status,
		arg.TotalTables,
		arg.ProcessedTables,
		arg.CreatedModels,
		arg.SyncedModels,
		arg.FailedCount,
		arg.FailedTables,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const deleteModelDatabase = `-- name: DeleteModelDatabase :exec
UPDATE model_database
SET ` + "`" + `deleted_at` + "`" + ` = CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000 AS UNSIGNED),
    ` + "`" + `delete_token` + "`" + ` = CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(6)) * 1000000 AS UNSIGNED)
WHERE id = ? AND org_name = ? AND project_slug = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
`

type DeleteModelDatabaseParams struct {
	ID          string
	OrgName     string
	ProjectSlug string
}

func (q *Queries) DeleteModelDatabase(ctx context.Context, arg DeleteModelDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, deleteModelDatabase, arg.ID, arg.OrgName, arg.ProjectSlug)
	return err
}

const failStaleSyncJobs = `-- name: FailStaleSyncJobs :exec
UPDATE model_database_sync_job
SET status = 'failed',
    finished_at = NOW(3),
    updated_at = NOW(3)
WHERE ` + "`" + `model_database_sync_job` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
  AND status IN ('pending', 'running')
  AND updated_at <= ?
`

func (q *Queries) FailStaleSyncJobs(ctx context.Context, updatedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, failStaleSyncJobs, updatedAt)
	return err
}

const getActiveModelDatabaseSyncJobByDatabase = `-- name: GetActiveModelDatabaseSyncJobByDatabase :one
SELECT id, org_name, project_slug, database_id, status, total_tables, processed_tables, created_models, synced_models, failed_count, failed_tables, deleted_at, delete_token, started_at, finished_at, created_at, updated_at FROM model_database_sync_job
WHERE org_name = ?
  AND project_slug = ?
  AND database_id = ?
  AND ` + "`" + `model_database_sync_job` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
  AND status IN ('pending', 'running')
  AND updated_at > ?
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveModelDatabaseSyncJobByDatabaseParams struct {
	OrgName     string
	ProjectSlug string
	DatabaseID  string
	UpdatedAt   time.Time
}

func (q *Queries) GetActiveModelDatabaseSyncJobByDatabase(ctx context.Context, arg GetActiveModelDatabaseSyncJobByDatabaseParams) (ModelDatabaseSyncJob, error) {
	row := q.db.QueryRowContext(ctx, getActiveModelDatabaseSyncJobByDatabase,
		arg.OrgName,
		arg.ProjectSlug,
		arg.DatabaseID,
		arg.UpdatedAt,
	)
	var i ModelDatabaseSyncJob
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.DatabaseID,
		&i.Status,
		&i.TotalTables,
		&i.ProcessedTables,
		&i.CreatedModels,
		&i.SyncedModels,
		&i.FailedCount,
		&i.FailedTables,
		&i.DeletedAt,
		&i.DeleteToken,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelDatabaseByID = `-- name: GetModelDatabaseByID :one
SELECT id, org_name, project_slug, cluster_id, name, title, description, mode, deleted_at, delete_token, created_at, updated_at FROM model_database
WHERE id = ? AND org_name = ? AND project_slug = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
LIMIT 1
`

type GetModelDatabaseByIDParams struct {
	ID          string
	OrgName     string
	ProjectSlug string
}

func (q *Queries) GetModelDatabaseByID(ctx context.Context, arg GetModelDatabaseByIDParams) (ModelDatabase, error) {
	row := q.db.QueryRowContext(ctx, getModelDatabaseByID, arg.ID, arg.OrgName, arg.ProjectSlug)
	var i ModelDatabase
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.ClusterID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Mode,
		&i.DeletedAt,
		&i.DeleteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelDatabaseByName = `-- name: GetModelDatabaseByName :one
SELECT id, org_name, project_slug, cluster_id, name, title, description, mode, deleted_at, delete_token, created_at, updated_at FROM model_database
WHERE org_name = ? AND project_slug = ? AND name = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
LIMIT 1
`

type GetModelDatabaseByNameParams struct {
	OrgName     string
	ProjectSlug string
	Name        string
}

func (q *Queries) GetModelDatabaseByName(ctx context.Context, arg GetModelDatabaseByNameParams) (ModelDatabase, error) {
	row := q.db.QueryRowContext(ctx, getModelDatabaseByName, arg.OrgName, arg.ProjectSlug, arg.Name)
	var i ModelDatabase
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.ClusterID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Mode,
		&i.DeletedAt,
		&i.DeleteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelDatabaseSyncJobByID = `-- name: GetModelDatabaseSyncJobByID :one
SELECT id, org_name, project_slug, database_id, status, total_tables, processed_tables, created_models, synced_models, failed_count, failed_tables, deleted_at, delete_token, started_at, finished_at, created_at, updated_at FROM model_database_sync_job
WHERE id = ? AND org_name = ? AND project_slug = ? AND ` + "`" + `model_database_sync_job` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
LIMIT 1
`

type GetModelDatabaseSyncJobByIDParams struct {
	ID          string
	OrgName     string
	ProjectSlug string
}

func (q *Queries) GetModelDatabaseSyncJobByID(ctx context.Context, arg GetModelDatabaseSyncJobByIDParams) (ModelDatabaseSyncJob, error) {
	row := q.db.QueryRowContext(ctx, getModelDatabaseSyncJobByID, arg.ID, arg.OrgName, arg.ProjectSlug)
	var i ModelDatabaseSyncJob
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.DatabaseID,
		&i.Status,
		&i.TotalTables,
		&i.ProcessedTables,
		&i.CreatedModels,
		&i.SyncedModels,
		&i.FailedCount,
		&i.FailedTables,
		&i.DeletedAt,
		&i.DeleteToken,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModelDatabaseCatalog = `-- name: ListModelDatabaseCatalog :many
SELECT name FROM model_database
WHERE org_name = ?
  AND project_slug = ?
  AND (? IS NULL OR name LIKE CONCAT('%', ?, '%'))
  AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListModelDatabaseCatalogParams struct {
	OrgName      string
	ProjectSlug  string
	SearchFilter interface{}
	Search       interface{}
	Limit        int32
	Offset       int32
}

func (q *Queries) ListModelDatabaseCatalog(ctx context.Context, arg ListModelDatabaseCatalogParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listModelDatabaseCatalog,
		arg.OrgName,
		arg.ProjectSlug,
		arg.SearchFilter,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelDatabasesByProject = `-- name: ListModelDatabasesByProject :many
SELECT id, org_name, project_slug, cluster_id, name, title, description, mode, deleted_at, delete_token, created_at, updated_at FROM model_database
WHERE org_name = ? AND project_slug = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
ORDER BY created_at ASC
`

type ListModelDatabasesByProjectParams struct {
	OrgName     string
	ProjectSlug string
}

func (q *Queries) ListModelDatabasesByProject(ctx context.Context, arg ListModelDatabasesByProjectParams) ([]ModelDatabase, error) {
	rows, err := q.db.QueryContext(ctx, listModelDatabasesByProject, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelDatabase
	for rows.Next() {
		var i ModelDatabase
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.ClusterID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.Mode,
			&i.DeletedAt,
			&i.DeleteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelDatabase = `-- name: UpdateModelDatabase :exec
UPDATE model_database
SET title = ?, description = ?, mode = ?, updated_at = NOW(3)
WHERE id = ? AND org_name = ? AND project_slug = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
`

type UpdateModelDatabaseParams struct {
	Title       string
	Description sql.NullString
	Mode        ModelDatabaseMode
	ID          string
	OrgName     string
	ProjectSlug string
}

func (q *Queries) UpdateModelDatabase(ctx context.Context, arg UpdateModelDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, updateModelDatabase,
		arg.Title,
		arg.Description,
		arg.Mode,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
	)
	return err
}

const updateModelDatabaseSyncJob = `-- name: UpdateModelDatabaseSyncJob :exec
UPDATE model_database_sync_job
SET status = ?,
    total_tables = ?,
    processed_tables = ?,
    created_models = ?,
    synced_models = ?,
    failed_count = ?,
    failed_tables = ?,
    started_at = ?,
    finished_at = ?,
    updated_at = NOW(3)
WHERE id = ? AND ` + "`" + `model_database_sync_job` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
`

type UpdateModelDatabaseSyncJobParams struct {
	Status          ModelDatabaseSyncJobStatus
	TotalTables     int32
	ProcessedTables int32
	CreatedModels   int32
	SyncedModels    int32
	FailedCount     int32
	FailedTables    json.RawMessage
	StartedAt       sql.NullTime
	FinishedAt      sql.NullTime
	ID              string
}

func (q *Queries) UpdateModelDatabaseSyncJob(ctx context.Context, arg UpdateModelDatabaseSyncJobParams) error {
	_, err := q.db.ExecContext(ctx, updateModelDatabaseSyncJob,
		arg.Status,
		arg.TotalTables,
		arg.ProcessedTables,
		arg.CreatedModels,
		arg.SyncedModels,
		arg.FailedCount,
		arg.FailedTables,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
