// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type EndUserBundleDataPermissionItemsGrantType string

const (
	EndUserBundleDataPermissionItemsGrantTypePRESET EndUserBundleDataPermissionItemsGrantType = "PRESET"
	EndUserBundleDataPermissionItemsGrantTypeCUSTOM EndUserBundleDataPermissionItemsGrantType = "CUSTOM"
)

func (e *EndUserBundleDataPermissionItemsGrantType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EndUserBundleDataPermissionItemsGrantType(s)
	case string:
		*e = EndUserBundleDataPermissionItemsGrantType(s)
	default:
		return fmt.Errorf("unsupported scan type for EndUserBundleDataPermissionItemsGrantType: %T", src)
	}
	return nil
}

type NullEndUserBundleDataPermissionItemsGrantType struct {
	EndUserBundleDataPermissionItemsGrantType EndUserBundleDataPermissionItemsGrantType
	Valid                                     bool // Valid is true if EndUserBundleDataPermissionItemsGrantType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEndUserBundleDataPermissionItemsGrantType) Scan(value interface{}) error {
	if value == nil {
		ns.EndUserBundleDataPermissionItemsGrantType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EndUserBundleDataPermissionItemsGrantType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEndUserBundleDataPermissionItemsGrantType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EndUserBundleDataPermissionItemsGrantType), nil
}

type EndUserBundleDataPermissionItemsPreset string

const (
	EndUserBundleDataPermissionItemsPresetREADWRITEALL      EndUserBundleDataPermissionItemsPreset = "READ_WRITE_ALL"
	EndUserBundleDataPermissionItemsPresetREADALL           EndUserBundleDataPermissionItemsPreset = "READ_ALL"
	EndUserBundleDataPermissionItemsPresetREADWRITEOWNER    EndUserBundleDataPermissionItemsPreset = "READ_WRITE_OWNER"
	EndUserBundleDataPermissionItemsPresetREADALLWRITEOWNER EndUserBundleDataPermissionItemsPreset = "READ_ALL_WRITE_OWNER"
)

func (e *EndUserBundleDataPermissionItemsPreset) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EndUserBundleDataPermissionItemsPreset(s)
	case string:
		*e = EndUserBundleDataPermissionItemsPreset(s)
	default:
		return fmt.Errorf("unsupported scan type for EndUserBundleDataPermissionItemsPreset: %T", src)
	}
	return nil
}

type NullEndUserBundleDataPermissionItemsPreset struct {
	EndUserBundleDataPermissionItemsPreset EndUserBundleDataPermissionItemsPreset
	Valid                                  bool // Valid is true if EndUserBundleDataPermissionItemsPreset is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEndUserBundleDataPermissionItemsPreset) Scan(value interface{}) error {
	if value == nil {
		ns.EndUserBundleDataPermissionItemsPreset, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EndUserBundleDataPermissionItemsPreset.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEndUserBundleDataPermissionItemsPreset) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EndUserBundleDataPermissionItemsPreset), nil
}

type LogicalForeignKeysDirection string

const (
	LogicalForeignKeysDirectionNormal  LogicalForeignKeysDirection = "normal"
	LogicalForeignKeysDirectionReverse LogicalForeignKeysDirection = "reverse"
)

func (e *LogicalForeignKeysDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogicalForeignKeysDirection(s)
	case string:
		*e = LogicalForeignKeysDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for LogicalForeignKeysDirection: %T", src)
	}
	return nil
}

type NullLogicalForeignKeysDirection struct {
	LogicalForeignKeysDirection LogicalForeignKeysDirection
	Valid                       bool // Valid is true if LogicalForeignKeysDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogicalForeignKeysDirection) Scan(value interface{}) error {
	if value == nil {
		ns.LogicalForeignKeysDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogicalForeignKeysDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogicalForeignKeysDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogicalForeignKeysDirection), nil
}

type ModelDatabaseMode string

const (
	ModelDatabaseModeSelfHosted ModelDatabaseMode = "self_hosted"
	ModelDatabaseModeManaged    ModelDatabaseMode = "managed"
)

func (e *ModelDatabaseMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModelDatabaseMode(s)
	case string:
		*e = ModelDatabaseMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ModelDatabaseMode: %T", src)
	}
	return nil
}

type NullModelDatabaseMode struct {
	ModelDatabaseMode ModelDatabaseMode
	Valid             bool // Valid is true if ModelDatabaseMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModelDatabaseMode) Scan(value interface{}) error {
	if value == nil {
		ns.ModelDatabaseMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModelDatabaseMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModelDatabaseMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModelDatabaseMode), nil
}

type ModelsCreatedVia string

const (
	ModelsCreatedViaNEW      ModelsCreatedVia = "NEW"
	ModelsCreatedViaIMPORTED ModelsCreatedVia = "IMPORTED"
)

func (e *ModelsCreatedVia) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModelsCreatedVia(s)
	case string:
		*e = ModelsCreatedVia(s)
	default:
		return fmt.Errorf("unsupported scan type for ModelsCreatedVia: %T", src)
	}
	return nil
}

type NullModelsCreatedVia struct {
	ModelsCreatedVia ModelsCreatedVia
	Valid            bool // Valid is true if ModelsCreatedVia is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModelsCreatedVia) Scan(value interface{}) error {
	if value == nil {
		ns.ModelsCreatedVia, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModelsCreatedVia.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModelsCreatedVia) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModelsCreatedVia), nil
}

type ApiKey struct {
	ID     string
	UserID string
	// 用户命名，如 GitHub Actions
	Name string
	// SHA256 hash，不存明文
	KeyHash string
	// 完整 key 前 10 位，如 mc_a1b2c3d4
	KeyPrefix string
	// 绑定的角色 ID 列表（roles.id）
	RoleIds *json.RawMessage
	// 防抖：距上次 > 1 分钟才更新
	LastUsedAt sql.NullTime
	// NULL = 永不过期
	ExpiresAt sql.NullTime
	CreatedAt time.Time
	// NULL = 有效
	RevokedAt sql.NullTime
}

// 数据库集群配置信息表
type DatabaseCluster struct {
	// 集群唯一标识符
	ID string
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// 集群显示标题
	Title string
	// 集群描述信息
	Description sql.NullString
	// 数据库主机地址
	Host string
	// 数据库端口号
	Port int64
	// 数据库用户名
	Username string
	// 数据库密码
	Password string
	// 连接超时(秒,5-15)
	ConnectionTimeout int32
	// 数据库字符集
	Charset sql.NullString
	// 最大打开连接数
	MaxOpenConns sql.NullInt64
	// 最大空闲连接数
	MaxIdleConns sql.NullInt64
	// 连接最大生命周期（秒）
	ConnMaxLifetime sql.NullInt64
	// 集群状态:active/inactive
	Status sql.NullString
	// 数据版本号
	Version sql.NullInt64
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 终端用户会话表（Org 级隔离）
type EndUserAccount struct {
	// 会话 ID (UUID)
	ID string
	// 所属 Org
	OrgName string
	// 终端用户 ID
	UserID string
	// 刷新令牌哈希
	RefreshTokenHash string
	// 过期时间
	ExpiresAt time.Time
	// 是否已撤销
	Revoked   bool
	CreatedAt time.Time
}

// Bundle 数据权限 Item：bundle 在某模型上的唯一数据权限配置
type EndUserBundleDataPermissionItem struct {
	// Item UUID
	ID string
	// 所属权限包 ID，FK → end_user_permission_bundles.id
	BundleID string
	// 目标模型 ID，FK → models.id
	ModelID string
	// 授权来源类型
	GrantType EndUserBundleDataPermissionItemsGrantType
	// PRESET 模板枚举值（仅 grant_type=PRESET 时有值）
	Preset NullEndUserBundleDataPermissionItemsPreset
	// 自定义权限实体 ID（仅 grant_type=CUSTOM 时有值），FK → end_user_data_permissions.id
	CustomPermissionID sql.NullString
	// 显示排序权重（ASC）
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

// 自定义数据权限实体：管理员手工定义的模型级行列策略（仅 CUSTOM）
type EndUserDataPermission struct {
	// 权限实体 UUID
	ID string
	// 所属组织（冗余，不做 FK）
	OrgName string
	// 所属项目（冗余，不做 FK）
	ProjectSlug string
	// 数据源名称（可空，预留按数据源授权能力）
	DatabaseName sql.NullString
	// 模型名称（可空，预留按模型名授权能力）
	ModelName sql.NullString
	// 关联模型 ID，FK → models.id
	ModelID string
	// 权限名称，人类可读
	Name string
	// 权限描述
	Description sql.NullString
	// 列策略 JSON
	ColumnPolicy *json.RawMessage
	// 行策略 JSON，谓词为 GraphQL Runtime where 条件
	RowPolicy *json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 权限包：数据权限 item 的命名集合，用于角色授权或用户直接授权
type EndUserPermissionBundle struct {
	// 权限包 UUID
	ID string
	// 用户可自定义的 URL 友好标识符，同项目内唯一，创建时设定后不可修改
	Slug string
	// 所属组织
	OrgName string
	// 所属项目
	ProjectSlug string
	// 权限包名称
	Name string
	// 权限包描述
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 权限包历史快照：记录每次 data permission item 列表变更，支持回滚
type EndUserPermissionBundleSnapshot struct {
	// 快照 UUID
	ID string
	// 所属权限包 ID，FK → end_user_permission_bundles.id
	BundleID string
	// 版本号，从 1 开始，每个权限包独立计数
	Version int32
	// 快照时刻的 data permission item 列表，格式：[{"modelId":"uuid","grantType":"PRESET|CUSTOM","preset":"READ_ALL|...","customPermissionId":"uuid|null","sortOrder":0}]
	Items json.RawMessage
	// 快照创建时间
	CreatedAt time.Time
	// 操作人标识（用户 ID 或 system）
	CreatedBy sql.NullString
	// 若为回滚操作，指向来源版本号；否则为 NULL
	RestoredFrom sql.NullInt32
}

// 终端用户角色表（Project 级隔离）
type EndUserRole struct {
	// 角色 ID (UUID)
	ID string
	// 所属 Org
	OrgName string
	// 所属项目
	ProjectSlug string
	// Project 内唯一角色名
	Name string
	// 角色描述
	Description sql.NullString
	// 内置隐式角色标志：0=显式角色（用户手动分配），1=隐式角色（系统自动注入）
	IsImplicit bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
	// 受保护角色：不可删除、不可改名、不可修改权限包关联
	IsProtected bool
}

// 角色-权限包 关联：角色持有哪些权限包
type EndUserRoleBundle struct {
	// UUID
	ID string
	// 所属组织（冗余，快速查询）
	OrgName string
	// 所属项目（冗余，快速查询）
	ProjectSlug string
	// 角色 ID，FK → end_user_roles.id
	RoleID string
	// 权限包 ID，FK → end_user_permission_bundles.id
	BundleID string
	// 授权时间
	GrantedAt time.Time
}

// 终端用户角色-用户关联表（Org 级隔离）
type EndUserRoleUser struct {
	// 关联 ID (UUID)
	ID string
	// 所属 Org
	OrgName string
	// 角色 ID
	RoleID string
	// 终端用户 ID
	UserID    string
	CreatedAt time.Time
}

// 终端用户账号表（Org 级隔离）
type EndUserUser struct {
	// 终端用户 ID (UUID)
	ID string
	// 所属 Org
	OrgName string
	// Org 内唯一用户名
	Username string
	// bcrypt 密码哈希
	Password string
	// 是否禁用
	IsForbidden bool
	// 是否为平台内置账号（每个 Org 唯一，不可删除/禁用）
	IsBuiltin bool
	// 创建者（平台用户 ID）
	CreatedBy sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 用户直接授权-权限包：绕过角色直接给用户授予权限包
type EndUserUserBundle struct {
	// UUID
	ID string
	// 所属组织
	OrgName string
	// 所属项目
	ProjectSlug string
	// 用户 ID（复合 FK 的 id 部分）
	UserID string
	// 权限包 ID，FK → end_user_permission_bundles.id
	BundleID string
	// 授权时间
	GrantedAt time.Time
}

// 模型字段定义表
type FieldDefinition struct {
	// 所属模型ID
	ModelID string
	// 字段名称
	Name string
	// 所属组织名称（多租户隔离）
	OrgName string
	// 项目标识符（多租户隔离）
	ProjectSlug string
	// 模型名称
	ModelName string
	// 数据库名称
	DatabaseName string
	// 关联的枚举名称（format=ENUM）
	EnumName sql.NullString
	// 所属逻辑外键ID（FK列字段使用）
	BelongsToFkID sql.NullString
	// 关联的逻辑外键ID（RELATION格式字段使用）
	RelateFkID sql.NullString
	// 字段显示标题
	Title string
	// 字段描述信息
	Description sql.NullString
	// 字段格式类型
	Format string
	// 是否可为null
	NonNull sql.NullBool
	// 是否创建时必填
	Required sql.NullBool
	// 是否唯一
	IsUnique sql.NullBool
	// 是否主键
	IsPrimary sql.NullBool
	// 是否已废弃
	IsDeprecated sql.NullBool
	// 字段状态：init/active/inactive
	Status string
	// 字段验证规则配置
	Validation *json.RawMessage
	// 字典序排序键，用于拖拽排序（lexicographic fractional index）
	DisplayOrder string
	// 字段元数据配置
	Metadata *json.RawMessage
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 逻辑外键定义表
type LogicalForeignKey struct {
	// 逻辑外键唯一标识符
	ID string
	// 外键对ID，normal 和 reverse 行共享
	PairID string
	// 所属组织名称
	OrgName string
	// 外键方向：normal（正向）/ reverse（反向）
	Direction LogicalForeignKeysDirection
	// 所属模型ID
	ModelID string
	// 所属模型名称（冗余存储，model_name 不变）
	ModelName string
	// 引用模型ID（外部表场景可为空）
	RefModelID sql.NullString
	// 引用模型名称（冗余存储，model_name 不变）
	RefModelName string
	// 引用数据库名（外部表场景）
	RefDatabaseName sql.NullString
	// 引用表名（外部表场景）
	RefTableName sql.NullString
	// 源字段列表（JSON数组）
	SourceFields json.RawMessage
	// 目标字段列表（JSON数组）
	TargetFields json.RawMessage
	// 是否允许删除（系统FK为0）
	IsDeletable bool
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 模型定义主表
type Model struct {
	// 模型唯一标识符
	ID string
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// 模型名称（唯一标识）
	Name string
	// 模型显示标题
	Title string
	// 模型描述信息
	Description sql.NullString
	// 存储类型
	StorageType string
	// 数据库名称
	DatabaseName string
	// 用于 runtime _displayName 解析的字段名（必须是模型中存在且可字符串化的字段）
	DisplayField sql.NullString
	// 数据版本号
	Version sql.NullInt64
	// 模型状态：draft/published/archived
	Status sql.NullString
	// 所属分组ID，NULL表示未分组（ungrouped）
	GroupID sql.NullString
	// 部署状态：pending/success/failed
	DeploymentStatus sql.NullString
	// 最后同步时间
	LastSyncAt sql.NullTime
	// 同步错误信息
	SyncError sql.NullString
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
	// 模型创建来源：NEW=新建，IMPORTED=导入
	CreatedVia ModelsCreatedVia
}

// Project 已接管的 MySQL database 注册表
type ModelDatabase struct {
	// 数据库唯一标识符 (UUID)
	ID string
	// 所属组织名称
	OrgName string
	// 所属项目标识符
	ProjectSlug string
	// 所属数据库集群 ID
	ClusterID string
	// MySQL database 原始名，来自 SHOW DATABASES，注册后不可修改
	Name string
	// 用户设置的友好名称，默认等于 name
	Title string
	// 可选描述
	Description sql.NullString
	// self_hosted=可读写; managed=只读
	Mode ModelDatabaseMode
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// 模型枚举定义表
type ModelEnum struct {
	// 枚举唯一标识符
	ID string
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// 枚举名称（唯一标识）
	Name string
	// 枚举显示名称
	DisplayName string
	// 枚举描述信息
	Description sql.NullString
	// 枚举选项配置（JSON数组格式）
	Options json.RawMessage
	// 是否支持多选
	IsMultiSelect sql.NullBool
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 模型字段与枚举关联表
type ModelFieldEnumAssociation struct {
	// 模型ID
	ModelID string
	// 字段名称
	FieldName string
	// 所属组织名称
	OrgName string
	// 所属项目标识符
	ProjectSlug string
	// 关联的枚举名称
	EnumName string
	// 数据库名称
	DatabaseName string
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
}

// 模型分组定义表
type ModelGroup struct {
	// 分组唯一标识符
	ID string
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// 分组名称，仅小写字母、数字和下划线，字母开头
	Name string
	// 字典序排序键，用于拖拽排序（lexicographic fractional index）
	DisplayOrder string
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// Model RLS 策略配置
type ModelRlsPolicy struct {
	ID uint64
	// 模型 ID
	ModelID string
	// SELECT USING 谓词 JSON
	SelectPredicate string
	// INSERT WITH CHECK 谓词 JSON
	InsertCheck string
	// UPDATE USING 谓词 JSON
	UpdatePredicate string
	// UPDATE WITH CHECK 谓词 JSON
	UpdateCheck string
	// DELETE USING 谓词 JSON
	DeletePredicate string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// 组织表（多租户容器）
type Organization struct {
	// 唯一标识符，随机slug
	Name string
	// 用于 UI 显示的名称
	DisplayName sql.NullString
	// 组织创建者/所有者（引用 users.id）
	OwnerID sql.NullString
	// 状态：active、suspended、deleted
	Status string
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 用户资料表
type Profile struct {
	// profile UUID
	ID string
	// 用户 ID（引用 users.id）
	UserID string
	// 昵称
	Nickname string
	// 头像 URL（当前可为空，上传能力后续实现）
	AvatarUrl sql.NullString
	// 个人简介
	Bio sql.NullString
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 项目信息表（多租户，复合主键，只归档不删除）
type Project struct {
	// 组织名称（复合主键之一）
	OrgName string
	// 项目标识符（组织内唯一，复合主键之二）
	Slug string
	// 项目显示标题
	Title string
	// 项目描述信息
	Description sql.NullString
	// 项目状态：active/archived（永不物理删除）
	Status string
	// 关联的集群ID（一对一关系）
	ClusterID sql.NullString
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// Project-level authentication configuration
type ProjectAuthConfig struct {
	// Primary key
	ID int64
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// Authentication provider type: auth_provider, keycloak, oidc
	Provider string
	// Whether authentication is enabled for this project
	Enabled bool
	// Provider-specific configuration (endpoint, client_id, certificate, etc.)
	Config json.RawMessage
	// Record creation timestamp
	CreatedAt time.Time
	// Record last update timestamp
	UpdatedAt time.Time
}

// Project 认证变量配置
type ProjectAuthSchema struct {
	ID uint64
	// 所属组织名称
	OrgName string
	// 所属项目标识符
	ProjectSlug string
	// 认证变量列表 [{name, source, type}]
	Variables json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	ID     string
	UserID string
	// SHA256 hash，不存明文
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
	// NULL = 有效
	RevokedAt sql.NullTime
}

// 角色表（支持系统角色和租户自定义角色）
type Role struct {
	// 角色 ID（主键）
	ID int64
	// 角色名称（如 owner, admin, editor, viewer, 或自定义）
	Name string
	// 角色描述
	Description sql.NullString
	// 系统角色标识（true = 不可修改删除）
	IsSystem bool
	// 所属组织名称（__SYSTEM__ = 系统角色，其他 = 租户自定义角色）
	OrgName string
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 角色权限表（仅存储自定义角色权限）
type RolePermission struct {
	// 主键 ID
	ID int64
	// 角色 ID（引用 roles.id）
	RoleID int64
	// 组织名称（冗余字段，优化查询）
	OrgName string
	// 资源对象（如 project, model, cluster, enum）
	Obj string
	// 操作动作（如 create, read, update, delete, *）
	Act string
	// 创建时间
	CreatedAt time.Time
}

type SecurityAuditLog struct {
	ID     string
	UserID string
	// 如 REUSE_DETECTED
	Event string
	// token_id, ip 等上下文
	Detail    *json.RawMessage
	CreatedAt time.Time
}

// 用户表
type User struct {
	// 内部 UUID
	ID string
	// 外部认证提供者用户 ID（来自 JWT.sub，AuthProvider 用户有值，本地注册用户为 NULL）
	ExternalID sql.NullString
	// 用户名（userName）
	Name string
	// 用户手机号
	Phone string
	// bcrypt 密码哈希（本地注册用户有值，AuthProvider 用户为空）
	PasswordHash string
	// 用于 UI 显示的名称
	DisplayName sql.NullString
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
	// 软删除时间戳，0 表示活跃
	DeletedAt uint64
	// 唯一键避让位，0 表示活跃
	DeleteToken uint64
}

// 用户-组织关联表
type UserOrganization struct {
	// UUID
	ID string
	// 用户 ID（引用 users.id）
	UserID string
	// 组织名称（引用 organizations.name）
	OrgName string
	// 状态：active、suspended、invited
	Status string
	// 邀请人（用户引用）
	InvitedBy sql.NullString
	// 邀请发送时间
	InvitedAt sql.NullTime
	// 接受邀请时间
	JoinedAt sql.NullTime
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
}

// 用户角色绑定表（支持多租户）
type UserRole struct {
	// 主键 ID
	ID int64
	// 用户 ID（引用 users.id）
	UserID string
	// 角色 ID（引用 roles.id）
	RoleID int64
	// 组织名称（多租户隔离）
	OrgName string
	// 创建时间
	CreatedAt time.Time
}
