// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_group.sql

package dbgen

import (
	"context"
)

const createModelGroup = `-- name: CreateModelGroup :exec
INSERT INTO model_groups (id, org_name, project_slug, name, display_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateModelGroupParams struct {
	ID           string
	OrgName      string
	ProjectSlug  string
	Name         string
	DisplayOrder string
}

func (q *Queries) CreateModelGroup(ctx context.Context, arg CreateModelGroupParams) error {
	_, err := q.db.ExecContext(ctx, createModelGroup,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.Name,
		arg.DisplayOrder,
	)
	return err
}

const deleteModelGroup = `-- name: DeleteModelGroup :exec
DELETE FROM model_groups WHERE id = ?
`

func (q *Queries) DeleteModelGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteModelGroup, id)
	return err
}

const getModelGroupByID = `-- name: GetModelGroupByID :one
SELECT id, org_name, project_slug, name, display_order, created_at, updated_at FROM model_groups WHERE id = ? LIMIT 1
`

func (q *Queries) GetModelGroupByID(ctx context.Context, id string) (ModelGroup, error) {
	row := q.db.QueryRowContext(ctx, getModelGroupByID, id)
	var i ModelGroup
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.Name,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelGroupByName = `-- name: GetModelGroupByName :one
SELECT id, org_name, project_slug, name, display_order, created_at, updated_at FROM model_groups
WHERE org_name = ? AND project_slug = ? AND name = ?
LIMIT 1
`

type GetModelGroupByNameParams struct {
	OrgName     string
	ProjectSlug string
	Name        string
}

func (q *Queries) GetModelGroupByName(ctx context.Context, arg GetModelGroupByNameParams) (ModelGroup, error) {
	row := q.db.QueryRowContext(ctx, getModelGroupByName, arg.OrgName, arg.ProjectSlug, arg.Name)
	var i ModelGroup
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.Name,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTailModelGroupDisplayOrder = `-- name: GetTailModelGroupDisplayOrder :one
SELECT display_order FROM model_groups
WHERE org_name = ? AND project_slug = ?
ORDER BY display_order DESC
LIMIT 1
`

type GetTailModelGroupDisplayOrderParams struct {
	OrgName     string
	ProjectSlug string
}

func (q *Queries) GetTailModelGroupDisplayOrder(ctx context.Context, arg GetTailModelGroupDisplayOrderParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getTailModelGroupDisplayOrder, arg.OrgName, arg.ProjectSlug)
	var display_order string
	err := row.Scan(&display_order)
	return display_order, err
}

const listModelGroupsByProject = `-- name: ListModelGroupsByProject :many
SELECT id, org_name, project_slug, name, display_order, created_at, updated_at FROM model_groups
WHERE org_name = ? AND project_slug = ?
ORDER BY display_order ASC
`

type ListModelGroupsByProjectParams struct {
	OrgName     string
	ProjectSlug string
}

func (q *Queries) ListModelGroupsByProject(ctx context.Context, arg ListModelGroupsByProjectParams) ([]ModelGroup, error) {
	rows, err := q.db.QueryContext(ctx, listModelGroupsByProject, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelGroup
	for rows.Next() {
		var i ModelGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.Name,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelGroup = `-- name: UpdateModelGroup :exec
UPDATE model_groups
SET name = ?, display_order = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateModelGroupParams struct {
	Name         string
	DisplayOrder string
	ID           string
}

func (q *Queries) UpdateModelGroup(ctx context.Context, arg UpdateModelGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateModelGroup, arg.Name, arg.DisplayOrder, arg.ID)
	return err
}
