// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type EndUserPermissionsAction string

const (
	EndUserPermissionsActionSelect EndUserPermissionsAction = "select"
	EndUserPermissionsActionInsert EndUserPermissionsAction = "insert"
	EndUserPermissionsActionUpdate EndUserPermissionsAction = "update"
	EndUserPermissionsActionDelete EndUserPermissionsAction = "delete"
	EndUserPermissionsActionExport EndUserPermissionsAction = "export"
)

func (e *EndUserPermissionsAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EndUserPermissionsAction(s)
	case string:
		*e = EndUserPermissionsAction(s)
	default:
		return fmt.Errorf("unsupported scan type for EndUserPermissionsAction: %T", src)
	}
	return nil
}

type NullEndUserPermissionsAction struct {
	EndUserPermissionsAction EndUserPermissionsAction
	Valid                    bool // Valid is true if EndUserPermissionsAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEndUserPermissionsAction) Scan(value interface{}) error {
	if value == nil {
		ns.EndUserPermissionsAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EndUserPermissionsAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEndUserPermissionsAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EndUserPermissionsAction), nil
}

type EndUserPermissionsRowScope string

const (
	EndUserPermissionsRowScopeALL             EndUserPermissionsRowScope = "ALL"
	EndUserPermissionsRowScopeSELF            EndUserPermissionsRowScope = "SELF"
	EndUserPermissionsRowScopeDEPT            EndUserPermissionsRowScope = "DEPT"
	EndUserPermissionsRowScopeDEPTANDCHILDREN EndUserPermissionsRowScope = "DEPT_AND_CHILDREN"
)

func (e *EndUserPermissionsRowScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EndUserPermissionsRowScope(s)
	case string:
		*e = EndUserPermissionsRowScope(s)
	default:
		return fmt.Errorf("unsupported scan type for EndUserPermissionsRowScope: %T", src)
	}
	return nil
}

type NullEndUserPermissionsRowScope struct {
	EndUserPermissionsRowScope EndUserPermissionsRowScope
	Valid                      bool // Valid is true if EndUserPermissionsRowScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEndUserPermissionsRowScope) Scan(value interface{}) error {
	if value == nil {
		ns.EndUserPermissionsRowScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EndUserPermissionsRowScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEndUserPermissionsRowScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EndUserPermissionsRowScope), nil
}

type LogicalForeignKeysDirection string

const (
	LogicalForeignKeysDirectionNormal  LogicalForeignKeysDirection = "normal"
	LogicalForeignKeysDirectionReverse LogicalForeignKeysDirection = "reverse"
)

func (e *LogicalForeignKeysDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogicalForeignKeysDirection(s)
	case string:
		*e = LogicalForeignKeysDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for LogicalForeignKeysDirection: %T", src)
	}
	return nil
}

type NullLogicalForeignKeysDirection struct {
	LogicalForeignKeysDirection LogicalForeignKeysDirection
	Valid                       bool // Valid is true if LogicalForeignKeysDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogicalForeignKeysDirection) Scan(value interface{}) error {
	if value == nil {
		ns.LogicalForeignKeysDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogicalForeignKeysDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogicalForeignKeysDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogicalForeignKeysDirection), nil
}

type ModelsCreatedVia string

const (
	ModelsCreatedViaNEW      ModelsCreatedVia = "NEW"
	ModelsCreatedViaIMPORTED ModelsCreatedVia = "IMPORTED"
)

func (e *ModelsCreatedVia) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModelsCreatedVia(s)
	case string:
		*e = ModelsCreatedVia(s)
	default:
		return fmt.Errorf("unsupported scan type for ModelsCreatedVia: %T", src)
	}
	return nil
}

type NullModelsCreatedVia struct {
	ModelsCreatedVia ModelsCreatedVia
	Valid            bool // Valid is true if ModelsCreatedVia is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModelsCreatedVia) Scan(value interface{}) error {
	if value == nil {
		ns.ModelsCreatedVia, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModelsCreatedVia.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModelsCreatedVia) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModelsCreatedVia), nil
}

type ApiKey struct {
	ID     string
	UserID string
	// 用户命名，如 GitHub Actions
	Name string
	// SHA256 hash，不存明文
	KeyHash string
	// 完整 key 前 10 位，如 mc_a1b2c3d4
	KeyPrefix string
	// 绑定的角色 ID 列表（roles.id）
	RoleIds *json.RawMessage
	// 防抖：距上次 > 1 分钟才更新
	LastUsedAt sql.NullTime
	// NULL = 永不过期
	ExpiresAt sql.NullTime
	CreatedAt time.Time
	// NULL = 有效
	RevokedAt sql.NullTime
}

// 数据库集群配置信息表
type DatabaseCluster struct {
	// 集群唯一标识符
	ID string
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// 集群显示标题
	Title string
	// 集群描述信息
	Description sql.NullString
	// 数据库主机地址
	Host string
	// 数据库端口号
	Port int64
	// 数据库用户名
	Username string
	// 数据库密码
	Password string
	// 连接超时(秒,5-15)
	ConnectionTimeout int32
	// 数据库字符集
	Charset sql.NullString
	// 最大打开连接数
	MaxOpenConns sql.NullInt64
	// 最大空闲连接数
	MaxIdleConns sql.NullInt64
	// 连接最大生命周期（秒）
	ConnMaxLifetime sql.NullInt64
	// 集群状态:active/inactive
	Status sql.NullString
	// 数据版本号
	Version sql.NullInt64
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
}

// 终端用户会话表（租户隔离）
type EndUserAccount struct {
	// 会话 ID (UUID)
	ID string
	// 租户组织名
	OrgName string
	// 租户项目标识
	ProjectSlug string
	// 终端用户 ID
	UserID string
	// 刷新令牌哈希
	RefreshTokenHash string
	// 过期时间
	ExpiresAt time.Time
	// 是否已撤销
	Revoked   bool
	CreatedAt time.Time
}

// 权限包-权限点 有序中间表
type EndUserBundlePermission struct {
	// UUID
	ID string
	// 权限包 ID，FK → end_user_permission_bundles.id
	BundleID string
	// 权限点 ID，FK → end_user_permissions.id
	PermissionID string
	// 显示排序权重（ASC）
	SortOrder int32
	CreatedAt time.Time
}

// 权限点：每行描述对某模型某动作的行列级权限配置
type EndUserPermission struct {
	// 权限点 UUID
	ID string
	// 所属组织（冗余，不做 FK）
	OrgName string
	// 所属项目（冗余，不做 FK）
	ProjectSlug string
	// 关联模型 ID，FK → models.id
	ModelID string
	// 权限点名称，人类可读
	Name string
	// 权限点描述
	Description sql.NullString
	// 操作动作
	Action EndUserPermissionsAction
	// 列策略 JSON，结构见注释
	ColumnPolicy *json.RawMessage
	// 行范围：ALL全量/SELF本人/DEPT本部门/DEPT_AND_CHILDREN含子部门
	RowScope  EndUserPermissionsRowScope
	CreatedAt time.Time
	UpdatedAt time.Time
}

// 权限包：权限点的命名集合，用于角色授权或用户直接授权
type EndUserPermissionBundle struct {
	// 权限包 UUID
	ID string
	// 所属组织
	OrgName string
	// 所属项目
	ProjectSlug string
	// 权限包名称
	Name string
	// 权限包描述
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// 终端用户角色表（租户隔离）
type EndUserRole struct {
	// 角色 ID (UUID)
	ID string
	// 租户组织名
	OrgName string
	// 租户项目标识
	ProjectSlug string
	// 角色名（租户内唯一）
	Name string
	// 角色描述
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	// 内置隐式角色标志：0=显式角色（用户手动分配），1=隐式角色（系统自动注入）
	IsImplicit bool
}

// 角色-权限包 关联：角色持有哪些权限包
type EndUserRoleBundle struct {
	// UUID
	ID string
	// 所属组织（冗余，快速查询）
	OrgName string
	// 所属项目（冗余，快速查询）
	ProjectSlug string
	// 角色 ID，FK → end_user_roles.id
	RoleID string
	// 权限包 ID，FK → end_user_permission_bundles.id
	BundleID string
	// 授权时间
	GrantedAt time.Time
}

// 终端用户角色-用户关联表（租户隔离）
type EndUserRoleUser struct {
	// 关联 ID (UUID)
	ID string
	// 租户组织名
	OrgName string
	// 租户项目标识
	ProjectSlug string
	// 角色 ID
	RoleID string
	// 终端用户 ID
	UserID    string
	CreatedAt time.Time
}

// 终端用户账号表（租户隔离）
type EndUserUser struct {
	// 终端用户 ID (UUID)
	ID string
	// 租户组织名
	OrgName string
	// 租户项目标识
	ProjectSlug string
	// 项目内唯一用户名
	Username string
	// bcrypt 密码哈希
	Password string
	// 是否禁用
	IsForbidden bool
	// 创建者（平台用户 ID）
	CreatedBy sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

// 用户直接授权-权限包：绕过角色直接给用户授予权限包
type EndUserUserBundle struct {
	// UUID
	ID string
	// 所属组织
	OrgName string
	// 所属项目
	ProjectSlug string
	// 用户 ID（复合 FK 的 id 部分）
	UserID string
	// 权限包 ID，FK → end_user_permission_bundles.id
	BundleID string
	// 授权时间
	GrantedAt time.Time
}

// 模型字段定义表
type FieldDefinition struct {
	// 所属模型ID
	ModelID string
	// 字段名称
	Name string
	// 所属组织名称（多租户隔离）
	OrgName string
	// 项目标识符（多租户隔离）
	ProjectSlug string
	// 模型名称
	ModelName string
	// 数据库名称
	DatabaseName string
	// 关联的枚举名称（format=ENUM）
	EnumName sql.NullString
	// 所属逻辑外键ID（FK列字段使用）
	BelongsToFkID sql.NullString
	// 关联的逻辑外键ID（RELATION格式字段使用）
	RelateFkID sql.NullString
	// 字段显示标题
	Title string
	// 字段描述信息
	Description sql.NullString
	// 字段格式类型
	Format string
	// 是否可为null
	NonNull sql.NullBool
	// 是否创建时必填
	Required sql.NullBool
	// 是否唯一
	IsUnique sql.NullBool
	// 是否主键
	IsPrimary sql.NullBool
	// 是否已废弃
	IsDeprecated sql.NullBool
	// 字段状态：init/active/inactive
	Status string
	// 字段验证规则配置
	Validation *json.RawMessage
	// 字典序排序键，用于拖拽排序（lexicographic fractional index）
	DisplayOrder string
	// 字段元数据配置
	Metadata *json.RawMessage
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
}

// 逻辑外键定义表
type LogicalForeignKey struct {
	// 逻辑外键唯一标识符
	ID string
	// 外键对ID，normal 和 reverse 行共享
	PairID string
	// 所属组织名称
	OrgName string
	// 外键方向：normal（正向）/ reverse（反向）
	Direction LogicalForeignKeysDirection
	// 所属模型ID
	ModelID string
	// 所属模型名称（冗余存储，model_name 不变）
	ModelName string
	// 引用模型ID（外部表场景可为空）
	RefModelID sql.NullString
	// 引用模型名称（冗余存储，model_name 不变）
	RefModelName string
	// 引用数据库名（外部表场景）
	RefDatabaseName sql.NullString
	// 引用表名（外部表场景）
	RefTableName sql.NullString
	// 源字段列表（JSON数组）
	SourceFields json.RawMessage
	// 目标字段列表（JSON数组）
	TargetFields json.RawMessage
	// 是否允许删除（系统FK为0）
	IsDeletable bool
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
}

// 模型定义主表
type Model struct {
	// 模型唯一标识符
	ID string
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// 模型名称（唯一标识）
	Name string
	// 模型显示标题
	Title string
	// 模型描述信息
	Description sql.NullString
	// 存储类型
	StorageType string
	// 数据库名称
	DatabaseName string
	// 用于 runtime _displayName 解析的字段名（必须是模型中存在且可字符串化的字段）
	DisplayField sql.NullString
	// 数据版本号
	Version sql.NullInt64
	// 模型状态：draft/published/archived
	Status sql.NullString
	// 所属分组ID，NULL表示未分组（ungrouped）
	GroupID sql.NullString
	// 部署状态：pending/success/failed
	DeploymentStatus sql.NullString
	// 最后同步时间
	LastSyncAt sql.NullTime
	// 同步错误信息
	SyncError sql.NullString
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
	// 模型创建来源：NEW=新建，IMPORTED=导入
	CreatedVia ModelsCreatedVia
}

// 模型枚举定义表
type ModelEnum struct {
	// 枚举唯一标识符
	ID string
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// 枚举名称（唯一标识）
	Name string
	// 枚举显示名称
	DisplayName string
	// 枚举描述信息
	Description sql.NullString
	// 枚举选项配置（JSON数组格式）
	Options json.RawMessage
	// 是否支持多选
	IsMultiSelect sql.NullBool
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
}

// 模型字段与枚举关联表
type ModelFieldEnumAssociation struct {
	// 模型ID
	ModelID string
	// 字段名称
	FieldName string
	// 所属组织名称
	OrgName string
	// 所属项目标识符
	ProjectSlug string
	// 关联的枚举名称
	EnumName string
	// 数据库名称
	DatabaseName string
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
}

// 模型分组定义表
type ModelGroup struct {
	// 分组唯一标识符
	ID string
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// 分组名称，仅小写字母、数字和下划线，字母开头
	Name string
	// 字典序排序键，用于拖拽排序（lexicographic fractional index）
	DisplayOrder string
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
}

// Model RLS 策略配置
type ModelRlsPolicy struct {
	ID uint64
	// 模型 ID
	ModelID string
	// SELECT USING 谓词 JSON
	SelectPredicate string
	// INSERT WITH CHECK 谓词 JSON
	InsertCheck string
	// UPDATE USING 谓词 JSON
	UpdatePredicate string
	// UPDATE WITH CHECK 谓词 JSON
	UpdateCheck string
	// DELETE USING 谓词 JSON
	DeletePredicate string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// 组织表（多租户容器）
type Organization struct {
	// 唯一标识符，随机slug
	Name string
	// 用于 UI 显示的名称
	DisplayName sql.NullString
	// 组织创建者/所有者（引用 users.id）
	OwnerID sql.NullString
	// 状态：active、suspended、deleted
	Status string
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
}

// 用户资料表
type Profile struct {
	// profile UUID
	ID string
	// 用户 ID（引用 users.id）
	UserID string
	// 昵称
	Nickname string
	// 头像 URL（当前可为空，上传能力后续实现）
	AvatarUrl sql.NullString
	// 个人简介
	Bio sql.NullString
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
}

// 项目信息表（多租户，复合主键，只归档不删除）
type Project struct {
	// 组织名称（复合主键之一）
	OrgName string
	// 项目标识符（组织内唯一，复合主键之二）
	Slug string
	// 项目显示标题
	Title string
	// 项目描述信息
	Description sql.NullString
	// 项目状态：active/archived（永不物理删除）
	Status string
	// 关联的集群ID（一对一关系）
	ClusterID sql.NullString
	// 创建时间
	CreatedAt sql.NullTime
	// 更新时间
	UpdatedAt sql.NullTime
}

// Project-level authentication configuration
type ProjectAuthConfig struct {
	// Primary key
	ID int64
	// 所属组织名称（来自projects表复合主键）
	OrgName string
	// 所属项目标识符（来自projects表复合主键）
	ProjectSlug string
	// Authentication provider type: casdoor, keycloak, oidc
	Provider string
	// Whether authentication is enabled for this project
	Enabled bool
	// Provider-specific configuration (endpoint, client_id, certificate, etc.)
	Config json.RawMessage
	// Record creation timestamp
	CreatedAt time.Time
	// Record last update timestamp
	UpdatedAt time.Time
}

// Project 认证变量配置
type ProjectAuthSchema struct {
	ID uint64
	// 所属组织名称
	OrgName string
	// 所属项目标识符
	ProjectSlug string
	// 认证变量列表 [{name, source, type}]
	Variables json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	ID     string
	UserID string
	// SHA256 hash，不存明文
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
	// NULL = 有效
	RevokedAt sql.NullTime
}

// 角色表（支持系统角色和租户自定义角色）
type Role struct {
	// 角色 ID（主键）
	ID int64
	// 角色名称（如 owner, admin, editor, viewer, 或自定义）
	Name string
	// 角色描述
	Description sql.NullString
	// 系统角色标识（true = 不可修改删除）
	IsSystem bool
	// 所属组织名称（__SYSTEM__ = 系统角色，其他 = 租户自定义角色）
	OrgName string
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
}

// 角色权限表（仅存储自定义角色权限）
type RolePermission struct {
	// 主键 ID
	ID int64
	// 角色 ID（引用 roles.id）
	RoleID int64
	// 组织名称（冗余字段，优化查询）
	OrgName string
	// 资源对象（如 project, model, cluster, enum）
	Obj string
	// 操作动作（如 create, read, update, delete, *）
	Act string
	// 创建时间
	CreatedAt time.Time
}

type SecurityAuditLog struct {
	ID     string
	UserID string
	// 如 REUSE_DETECTED
	Event string
	// token_id, ip 等上下文
	Detail    *json.RawMessage
	CreatedAt time.Time
}

// 用户表
type User struct {
	// 内部 UUID
	ID string
	// 外部认证提供者用户 ID（来自 JWT.sub，Casdoor 用户有值，本地注册用户为 NULL）
	ExternalID sql.NullString
	// 用户名（userName）
	Name string
	// 用户手机号
	Phone string
	// bcrypt 密码哈希（本地注册用户有值，Casdoor 用户为空）
	PasswordHash string
	// 用于 UI 显示的名称
	DisplayName sql.NullString
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
}

// 用户-组织关联表
type UserOrganization struct {
	// UUID
	ID string
	// 用户 ID（引用 users.id）
	UserID string
	// 组织名称（引用 organizations.name）
	OrgName string
	// 状态：active、suspended、invited
	Status string
	// 邀请人（用户引用）
	InvitedBy sql.NullString
	// 邀请发送时间
	InvitedAt sql.NullTime
	// 接受邀请时间
	JoinedAt sql.NullTime
	// 创建时间
	CreatedAt time.Time
	// 更新时间
	UpdatedAt time.Time
}

// 用户角色绑定表（支持多租户）
type UserRole struct {
	// 主键 ID
	ID int64
	// 用户 ID（引用 users.id）
	UserID string
	// 角色 ID（引用 roles.id）
	RoleID int64
	// 组织名称（多租户隔离）
	OrgName string
	// 创建时间
	CreatedAt time.Time
}
