// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_database.sql

package dbgen

import (
	"context"
)

const createModelDatabase = `-- name: CreateModelDatabase :exec
INSERT INTO model_database (id, org_name, project_slug, cluster_id, name, title, description, mode, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateModelDatabaseParams struct {
	ID          string
	OrgName     string
	ProjectSlug string
	ClusterID   string
	Name        string
	Title       string
	Description string
	Mode        ModelDatabaseMode
}

func (q *Queries) CreateModelDatabase(ctx context.Context, arg CreateModelDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, createModelDatabase,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.ClusterID,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.Mode,
	)
	return err
}

const deleteModelDatabase = `-- name: DeleteModelDatabase :exec
UPDATE model_database
SET ` + "`" + `deleted_at` + "`" + ` = CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000 AS UNSIGNED),
    ` + "`" + `delete_token` + "`" + ` = CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(6)) * 1000000 AS UNSIGNED)
WHERE id = ? AND org_name = ? AND project_slug = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
`

type DeleteModelDatabaseParams struct {
	ID          string
	OrgName     string
	ProjectSlug string
}

func (q *Queries) DeleteModelDatabase(ctx context.Context, arg DeleteModelDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, deleteModelDatabase, arg.ID, arg.OrgName, arg.ProjectSlug)
	return err
}

const getModelDatabaseByID = `-- name: GetModelDatabaseByID :one
SELECT id, org_name, project_slug, cluster_id, name, title, description, mode, deleted_at, delete_token, created_at, updated_at FROM model_database
WHERE id = ? AND org_name = ? AND project_slug = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
LIMIT 1
`

type GetModelDatabaseByIDParams struct {
	ID          string
	OrgName     string
	ProjectSlug string
}

func (q *Queries) GetModelDatabaseByID(ctx context.Context, arg GetModelDatabaseByIDParams) (ModelDatabase, error) {
	row := q.db.QueryRowContext(ctx, getModelDatabaseByID, arg.ID, arg.OrgName, arg.ProjectSlug)
	var i ModelDatabase
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.ClusterID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Mode,
		&i.DeletedAt,
		&i.DeleteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelDatabaseByName = `-- name: GetModelDatabaseByName :one
SELECT id, org_name, project_slug, cluster_id, name, title, description, mode, deleted_at, delete_token, created_at, updated_at FROM model_database
WHERE org_name = ? AND project_slug = ? AND name = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
LIMIT 1
`

type GetModelDatabaseByNameParams struct {
	OrgName     string
	ProjectSlug string
	Name        string
}

func (q *Queries) GetModelDatabaseByName(ctx context.Context, arg GetModelDatabaseByNameParams) (ModelDatabase, error) {
	row := q.db.QueryRowContext(ctx, getModelDatabaseByName, arg.OrgName, arg.ProjectSlug, arg.Name)
	var i ModelDatabase
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.ClusterID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Mode,
		&i.DeletedAt,
		&i.DeleteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModelDatabasesByProject = `-- name: ListModelDatabasesByProject :many
SELECT id, org_name, project_slug, cluster_id, name, title, description, mode, deleted_at, delete_token, created_at, updated_at FROM model_database
WHERE org_name = ? AND project_slug = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
ORDER BY created_at ASC
`

type ListModelDatabasesByProjectParams struct {
	OrgName     string
	ProjectSlug string
}

func (q *Queries) ListModelDatabasesByProject(ctx context.Context, arg ListModelDatabasesByProjectParams) ([]ModelDatabase, error) {
	rows, err := q.db.QueryContext(ctx, listModelDatabasesByProject, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelDatabase
	for rows.Next() {
		var i ModelDatabase
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.ClusterID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.Mode,
			&i.DeletedAt,
			&i.DeleteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelDatabase = `-- name: UpdateModelDatabase :exec
UPDATE model_database
SET title = ?, description = ?, mode = ?, updated_at = NOW(3)
WHERE id = ? AND org_name = ? AND project_slug = ? AND ` + "`" + `model_database` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0
`

type UpdateModelDatabaseParams struct {
	Title       string
	Description string
	Mode        ModelDatabaseMode
	ID          string
	OrgName     string
	ProjectSlug string
}

func (q *Queries) UpdateModelDatabase(ctx context.Context, arg UpdateModelDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, updateModelDatabase,
		arg.Title,
		arg.Description,
		arg.Mode,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
	)
	return err
}
