// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
)

const countModels = `-- name: CountModels :one
SELECT COUNT(*) FROM models
WHERE project_slug = ?
  AND database_name = ?
  AND (? IS NULL OR name LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR title LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR status = ?)
  AND (? IS NULL OR storage_type = ?)
`

type CountModelsParams struct {
	ProjectSlug  string
	DatabaseName string
	Column3      interface{}
	CONCAT       interface{}
	Column5      interface{}
	CONCAT_2     interface{}
	Column7      interface{}
	Status       sql.NullString
	Column9      interface{}
	StorageType  string
}

func (q *Queries) CountModels(ctx context.Context, arg CountModelsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModels,
		arg.ProjectSlug,
		arg.DatabaseName,
		arg.Column3,
		arg.CONCAT,
		arg.Column5,
		arg.CONCAT_2,
		arg.Column7,
		arg.Status,
		arg.Column9,
		arg.StorageType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModel = `-- name: CreateModel :exec
INSERT INTO models (id, org_name, project_slug, name, title, description, storage_type, database_name, version, status, group_id, deployment_status, last_sync_at, sync_error, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateModelParams struct {
	ID               string
	OrgName          string
	ProjectSlug      string
	Name             string
	Title            string
	Description      sql.NullString
	StorageType      string
	DatabaseName     string
	Version          sql.NullInt64
	Status           sql.NullString
	GroupID          sql.NullString
	DeploymentStatus sql.NullString
	LastSyncAt       sql.NullTime
	SyncError        sql.NullString
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) error {
	_, err := q.db.ExecContext(ctx, createModel,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.StorageType,
		arg.DatabaseName,
		arg.Version,
		arg.Status,
		arg.GroupID,
		arg.DeploymentStatus,
		arg.LastSyncAt,
		arg.SyncError,
	)
	return err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM models WHERE id = ?
`

func (q *Queries) DeleteModel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteModel, id)
	return err
}

const findModelsByDeploymentStatus = `-- name: FindModelsByDeploymentStatus :many
SELECT id, org_name, project_slug, name, title, description, storage_type, database_name, version, status, group_id, deployment_status, last_sync_at, sync_error, created_at, updated_at FROM models
WHERE deployment_status IN (/*SLICE:statuses*/?)
`

func (q *Queries) FindModelsByDeploymentStatus(ctx context.Context, statuses []sql.NullString) ([]Model, error) {
	query := findModelsByDeploymentStatus
	var queryParams []interface{}
	if len(statuses) > 0 {
		for _, v := range statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.StorageType,
			&i.DatabaseName,
			&i.Version,
			&i.Status,
			&i.GroupID,
			&i.DeploymentStatus,
			&i.LastSyncAt,
			&i.SyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllModels = `-- name: GetAllModels :many
SELECT id, org_name, project_slug, name, title, description, storage_type, database_name, version, status, group_id, deployment_status, last_sync_at, sync_error, created_at, updated_at FROM models
`

func (q *Queries) GetAllModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, getAllModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.StorageType,
			&i.DatabaseName,
			&i.Version,
			&i.Status,
			&i.GroupID,
			&i.DeploymentStatus,
			&i.LastSyncAt,
			&i.SyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelByID = `-- name: GetModelByID :one
SELECT id, org_name, project_slug, name, title, description, storage_type, database_name, version, status, group_id, deployment_status, last_sync_at, sync_error, created_at, updated_at FROM models WHERE id = ? LIMIT 1
`

func (q *Queries) GetModelByID(ctx context.Context, id string) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModelByID, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.StorageType,
		&i.DatabaseName,
		&i.Version,
		&i.Status,
		&i.GroupID,
		&i.DeploymentStatus,
		&i.LastSyncAt,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelByName = `-- name: GetModelByName :one
SELECT id, org_name, project_slug, name, title, description, storage_type, database_name, version, status, group_id, deployment_status, last_sync_at, sync_error, created_at, updated_at FROM models
WHERE database_name = ? AND name = ? AND project_slug = ?
LIMIT 1
`

type GetModelByNameParams struct {
	DatabaseName string
	Name         string
	ProjectSlug  string
}

func (q *Queries) GetModelByName(ctx context.Context, arg GetModelByNameParams) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModelByName, arg.DatabaseName, arg.Name, arg.ProjectSlug)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.StorageType,
		&i.DatabaseName,
		&i.Version,
		&i.Status,
		&i.GroupID,
		&i.DeploymentStatus,
		&i.LastSyncAt,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModels = `-- name: ListModels :many
SELECT id, org_name, project_slug, name, title, description, storage_type, database_name, version, status, group_id, deployment_status, last_sync_at, sync_error, created_at, updated_at FROM models
WHERE project_slug = ?
  AND database_name = ?
  AND (? IS NULL OR name LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR title LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR status = ?)
  AND (? IS NULL OR storage_type = ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListModelsParams struct {
	ProjectSlug  string
	DatabaseName string
	Column3      interface{}
	CONCAT       interface{}
	Column5      interface{}
	CONCAT_2     interface{}
	Column7      interface{}
	Status       sql.NullString
	Column9      interface{}
	StorageType  string
	Limit        int32
	Offset       int32
}

func (q *Queries) ListModels(ctx context.Context, arg ListModelsParams) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, listModels,
		arg.ProjectSlug,
		arg.DatabaseName,
		arg.Column3,
		arg.CONCAT,
		arg.Column5,
		arg.CONCAT_2,
		arg.Column7,
		arg.Status,
		arg.Column9,
		arg.StorageType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.StorageType,
			&i.DatabaseName,
			&i.Version,
			&i.Status,
			&i.GroupID,
			&i.DeploymentStatus,
			&i.LastSyncAt,
			&i.SyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModel = `-- name: UpdateModel :execresult
UPDATE models
SET title = ?, description = ?, status = ?, group_id = ?, deployment_status = ?, version = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateModelParams struct {
	Title            string
	Description      sql.NullString
	Status           sql.NullString
	GroupID          sql.NullString
	DeploymentStatus sql.NullString
	Version          sql.NullInt64
	ID               string
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateModel,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.GroupID,
		arg.DeploymentStatus,
		arg.Version,
		arg.ID,
	)
}

const updateModelDeploymentStatus = `-- name: UpdateModelDeploymentStatus :exec
UPDATE models
SET deployment_status = ?, last_sync_at = ?, sync_error = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateModelDeploymentStatusParams struct {
	DeploymentStatus sql.NullString
	LastSyncAt       sql.NullTime
	SyncError        sql.NullString
	ID               string
}

func (q *Queries) UpdateModelDeploymentStatus(ctx context.Context, arg UpdateModelDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateModelDeploymentStatus,
		arg.DeploymentStatus,
		arg.LastSyncAt,
		arg.SyncError,
		arg.ID,
	)
	return err
}

const updateModelWithVersion = `-- name: UpdateModelWithVersion :execresult
UPDATE models
SET title = ?, description = ?, status = ?, group_id = ?, deployment_status = ?, version = version + 1, updated_at = NOW(3)
WHERE id = ? AND version = ?
`

type UpdateModelWithVersionParams struct {
	Title            string
	Description      sql.NullString
	Status           sql.NullString
	GroupID          sql.NullString
	DeploymentStatus sql.NullString
	ID               string
	Version          sql.NullInt64
}

func (q *Queries) UpdateModelWithVersion(ctx context.Context, arg UpdateModelWithVersionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateModelWithVersion,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.GroupID,
		arg.DeploymentStatus,
		arg.ID,
		arg.Version,
	)
}

const updateModelsGroupID = `-- name: UpdateModelsGroupID :exec
UPDATE models
SET group_id = ?, updated_at = NOW(3)
WHERE group_id = ?
`

type UpdateModelsGroupIDParams struct {
	GroupID   sql.NullString
	GroupID_2 sql.NullString
}

func (q *Queries) UpdateModelsGroupID(ctx context.Context, arg UpdateModelsGroupIDParams) error {
	_, err := q.db.ExecContext(ctx, updateModelsGroupID, arg.GroupID, arg.GroupID_2)
	return err
}
