// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countMembershipsByUser = `-- name: CountMembershipsByUser :one
SELECT COUNT(*) FROM user_organizations WHERE user_id = ?
`

func (q *Queries) CountMembershipsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembershipsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO user_organizations (id, user_id, org_name, status, invited_by, invited_at, joined_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateMembershipParams struct {
	ID        string
	UserID    string
	OrgName   string
	Status    string
	InvitedBy sql.NullString
	InvitedAt sql.NullTime
	JoinedAt  sql.NullTime
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createMembership,
		arg.ID,
		arg.UserID,
		arg.OrgName,
		arg.Status,
		arg.InvitedBy,
		arg.InvitedAt,
		arg.JoinedAt,
	)
	return err
}

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (name, display_name, owner_id, status, created_at, updated_at)
VALUES (?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateOrganizationParams struct {
	Name        string
	DisplayName sql.NullString
	OwnerID     sql.NullString
	Status      string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization,
		arg.Name,
		arg.DisplayName,
		arg.OwnerID,
		arg.Status,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, external_id, name, phone, display_name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateUserParams struct {
	ID          string
	ExternalID  string
	Name        string
	Phone       string
	DisplayName sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.ExternalID,
		arg.Name,
		arg.Phone,
		arg.DisplayName,
	)
	return err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM user_organizations WHERE id = ?
`

func (q *Queries) DeleteMembership(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMembership, id)
	return err
}

const existsOrganizationByName = `-- name: ExistsOrganizationByName :one
SELECT COUNT(*) FROM organizations WHERE name = ?
`

func (q *Queries) ExistsOrganizationByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsOrganizationByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsUserByExternalID = `-- name: ExistsUserByExternalID :one
SELECT COUNT(*) FROM users WHERE external_id = ?
`

func (q *Queries) ExistsUserByExternalID(ctx context.Context, externalID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsUserByExternalID, externalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findIDByExternalID = `-- name: FindIDByExternalID :one
SELECT id FROM users WHERE external_id = ? LIMIT 1
`

func (q *Queries) FindIDByExternalID(ctx context.Context, externalID string) (string, error) {
	row := q.db.QueryRowContext(ctx, findIDByExternalID, externalID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, user_id, org_name, status, invited_by, invited_at, joined_at, created_at, updated_at FROM user_organizations WHERE id = ? LIMIT 1
`

func (q *Queries) GetMembershipByID(ctx context.Context, id string) (UserOrganization, error) {
	row := q.db.QueryRowContext(ctx, getMembershipByID, id)
	var i UserOrganization
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgName,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByUserAndOrg = `-- name: GetMembershipByUserAndOrg :one
SELECT id, user_id, org_name, status, invited_by, invited_at, joined_at, created_at, updated_at FROM user_organizations
WHERE user_id = ? AND org_name = ?
LIMIT 1
`

type GetMembershipByUserAndOrgParams struct {
	UserID  string
	OrgName string
}

func (q *Queries) GetMembershipByUserAndOrg(ctx context.Context, arg GetMembershipByUserAndOrgParams) (UserOrganization, error) {
	row := q.db.QueryRowContext(ctx, getMembershipByUserAndOrg, arg.UserID, arg.OrgName)
	var i UserOrganization
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgName,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByName = `-- name: GetOrganizationByName :one
SELECT name, display_name, owner_id, status, created_at, updated_at FROM organizations WHERE name = ? LIMIT 1
`

func (q *Queries) GetOrganizationByName(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByName, name)
	var i Organization
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, name, phone, display_name, created_at, updated_at FROM users WHERE external_id = ? LIMIT 1
`

func (q *Queries) GetUserByExternalID(ctx context.Context, externalID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.Phone,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, external_id, name, phone, display_name, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.Phone,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByOrg = `-- name: ListMembershipsByOrg :many
SELECT id, user_id, org_name, status, invited_by, invited_at, joined_at, created_at, updated_at FROM user_organizations
WHERE org_name = ?
ORDER BY created_at DESC
`

func (q *Queries) ListMembershipsByOrg(ctx context.Context, orgName string) ([]UserOrganization, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsByOrg, orgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserOrganization
	for rows.Next() {
		var i UserOrganization
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgName,
			&i.Status,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT id, user_id, org_name, status, invited_by, invited_at, joined_at, created_at, updated_at FROM user_organizations
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID string) ([]UserOrganization, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserOrganization
	for rows.Next() {
		var i UserOrganization
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgName,
			&i.Status,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsWithOrgDetails = `-- name: ListMembershipsWithOrgDetails :many
SELECT m.id, m.user_id, m.org_name, m.status, m.invited_by, m.invited_at, m.joined_at, m.created_at, m.updated_at,
       o.display_name AS org_display_name
FROM user_organizations m
INNER JOIN organizations o ON m.org_name = o.name
WHERE m.user_id = ? AND m.status = 'active'
ORDER BY m.joined_at DESC
LIMIT ?
`

type ListMembershipsWithOrgDetailsParams struct {
	UserID string
	Limit  int32
}

type ListMembershipsWithOrgDetailsRow struct {
	ID             string
	UserID         string
	OrgName        string
	Status         string
	InvitedBy      sql.NullString
	InvitedAt      sql.NullTime
	JoinedAt       sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OrgDisplayName sql.NullString
}

func (q *Queries) ListMembershipsWithOrgDetails(ctx context.Context, arg ListMembershipsWithOrgDetailsParams) ([]ListMembershipsWithOrgDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsWithOrgDetails, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsWithOrgDetailsRow
	for rows.Next() {
		var i ListMembershipsWithOrgDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgName,
			&i.Status,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsWithUserName = `-- name: ListMembershipsWithUserName :many
SELECT m.id, m.user_id, m.org_name, m.status, m.invited_by, m.invited_at, m.joined_at, m.created_at, m.updated_at,
       COALESCE(u.name, '') AS user_name
FROM user_organizations m
LEFT JOIN users u ON m.user_id = u.id
WHERE m.org_name = ?
ORDER BY m.created_at DESC
`

type ListMembershipsWithUserNameRow struct {
	ID        string
	UserID    string
	OrgName   string
	Status    string
	InvitedBy sql.NullString
	InvitedAt sql.NullTime
	JoinedAt  sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
	UserName  string
}

func (q *Queries) ListMembershipsWithUserName(ctx context.Context, orgName string) ([]ListMembershipsWithUserNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsWithUserName, orgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsWithUserNameRow
	for rows.Next() {
		var i ListMembershipsWithUserNameRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgName,
			&i.Status,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByUser = `-- name: ListOrganizationsByUser :many
SELECT o.name, o.display_name, o.owner_id, o.status, o.created_at, o.updated_at FROM organizations o
INNER JOIN user_organizations m ON o.name = m.org_name
WHERE m.user_id = ? AND m.status = 'active'
ORDER BY o.created_at DESC
`

func (q *Queries) ListOrganizationsByUser(ctx context.Context, userID string) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.Name,
			&i.DisplayName,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembership = `-- name: UpdateMembership :exec
UPDATE user_organizations
SET status = ?, invited_by = ?, invited_at = ?, joined_at = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateMembershipParams struct {
	Status    string
	InvitedBy sql.NullString
	InvitedAt sql.NullTime
	JoinedAt  sql.NullTime
	ID        string
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) error {
	_, err := q.db.ExecContext(ctx, updateMembership,
		arg.Status,
		arg.InvitedBy,
		arg.InvitedAt,
		arg.JoinedAt,
		arg.ID,
	)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET display_name = ?, status = ?, updated_at = NOW(3)
WHERE name = ?
`

type UpdateOrganizationParams struct {
	DisplayName sql.NullString
	Status      string
	Name        string
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganization, arg.DisplayName, arg.Status, arg.Name)
	return err
}
