// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createEndUserPermission = `-- name: CreateEndUserPermission :exec
INSERT INTO end_user_data_permissions (
  id,
  org_name,
  project_slug,
  database_name,
  model_name,
  model_id,
  name,
  description,
  type,
  column_policy,
  row_policy,
  preset
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEndUserPermissionParams struct {
	ID           string
	OrgName      string
	ProjectSlug  string
	DatabaseName sql.NullString
	ModelName    sql.NullString
	ModelID      string
	Name         string
	Description  sql.NullString
	Type         EndUserDataPermissionsType
	ColumnPolicy *json.RawMessage
	RowPolicy    *json.RawMessage
	Preset       NullEndUserDataPermissionsPreset
}

func (q *Queries) CreateEndUserPermission(ctx context.Context, arg CreateEndUserPermissionParams) error {
	_, err := q.db.ExecContext(ctx, createEndUserPermission,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.DatabaseName,
		arg.ModelName,
		arg.ModelID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.ColumnPolicy,
		arg.RowPolicy,
		arg.Preset,
	)
	return err
}

const deleteEndUserPermission = `-- name: DeleteEndUserPermission :execresult
DELETE FROM end_user_data_permissions
WHERE id = ?
  AND org_name = ?
`

type DeleteEndUserPermissionParams struct {
	ID      string
	OrgName string
}

func (q *Queries) DeleteEndUserPermission(ctx context.Context, arg DeleteEndUserPermissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEndUserPermission, arg.ID, arg.OrgName)
}

const deleteEndUserPermissionsByModelAndType = `-- name: DeleteEndUserPermissionsByModelAndType :execresult
DELETE FROM end_user_data_permissions
WHERE model_id = ?
  AND org_name = ?
  AND type = ?
`

type DeleteEndUserPermissionsByModelAndTypeParams struct {
	ModelID string
	OrgName string
	Type    EndUserDataPermissionsType
}

func (q *Queries) DeleteEndUserPermissionsByModelAndType(ctx context.Context, arg DeleteEndUserPermissionsByModelAndTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEndUserPermissionsByModelAndType, arg.ModelID, arg.OrgName, arg.Type)
}

const getEndUserPermissionByID = `-- name: GetEndUserPermissionByID :one
SELECT id, org_name, project_slug, database_name, model_name, model_id, name, description, type, column_policy, row_policy, preset, created_at, updated_at
FROM end_user_data_permissions
WHERE id = ?
  AND org_name = ?
`

type GetEndUserPermissionByIDParams struct {
	ID      string
	OrgName string
}

func (q *Queries) GetEndUserPermissionByID(ctx context.Context, arg GetEndUserPermissionByIDParams) (EndUserDataPermission, error) {
	row := q.db.QueryRowContext(ctx, getEndUserPermissionByID, arg.ID, arg.OrgName)
	var i EndUserDataPermission
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.DatabaseName,
		&i.ModelName,
		&i.ModelID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.ColumnPolicy,
		&i.RowPolicy,
		&i.Preset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndUserPermissionByModelTypeName = `-- name: GetEndUserPermissionByModelTypeName :one
SELECT id, org_name, project_slug, database_name, model_name, model_id, name, description, type, column_policy, row_policy, preset, created_at, updated_at
FROM end_user_data_permissions
WHERE model_id = ?
  AND org_name = ?
  AND type = ?
  AND name = ?
LIMIT 1
`

type GetEndUserPermissionByModelTypeNameParams struct {
	ModelID string
	OrgName string
	Type    EndUserDataPermissionsType
	Name    string
}

func (q *Queries) GetEndUserPermissionByModelTypeName(ctx context.Context, arg GetEndUserPermissionByModelTypeNameParams) (EndUserDataPermission, error) {
	row := q.db.QueryRowContext(ctx, getEndUserPermissionByModelTypeName,
		arg.ModelID,
		arg.OrgName,
		arg.Type,
		arg.Name,
	)
	var i EndUserDataPermission
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.DatabaseName,
		&i.ModelName,
		&i.ModelID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.ColumnPolicy,
		&i.RowPolicy,
		&i.Preset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isPermissionReferencedByBundle = `-- name: IsPermissionReferencedByBundle :one
SELECT COUNT(*) > 0 AS referenced
FROM end_user_bundle_permissions
WHERE permission_id = ?
`

func (q *Queries) IsPermissionReferencedByBundle(ctx context.Context, permissionID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isPermissionReferencedByBundle, permissionID)
	var referenced bool
	err := row.Scan(&referenced)
	return referenced, err
}

const listEndUserPermissionsByModel = `-- name: ListEndUserPermissionsByModel :many
SELECT id, org_name, project_slug, database_name, model_name, model_id, name, description, type, column_policy, row_policy, preset, created_at, updated_at
FROM end_user_data_permissions
WHERE model_id = ?
  AND org_name = ?
ORDER BY created_at
`

type ListEndUserPermissionsByModelParams struct {
	ModelID string
	OrgName string
}

func (q *Queries) ListEndUserPermissionsByModel(ctx context.Context, arg ListEndUserPermissionsByModelParams) ([]EndUserDataPermission, error) {
	rows, err := q.db.QueryContext(ctx, listEndUserPermissionsByModel, arg.ModelID, arg.OrgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserDataPermission
	for rows.Next() {
		var i EndUserDataPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.DatabaseName,
			&i.ModelName,
			&i.ModelID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.ColumnPolicy,
			&i.RowPolicy,
			&i.Preset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndUserPermissionsByProject = `-- name: ListEndUserPermissionsByProject :many
SELECT id, org_name, project_slug, database_name, model_name, model_id, name, description, type, column_policy, row_policy, preset, created_at, updated_at
FROM end_user_data_permissions
WHERE org_name = ?
  AND project_slug = ?
ORDER BY created_at
`

type ListEndUserPermissionsByProjectParams struct {
	OrgName     string
	ProjectSlug string
}

func (q *Queries) ListEndUserPermissionsByProject(ctx context.Context, arg ListEndUserPermissionsByProjectParams) ([]EndUserDataPermission, error) {
	rows, err := q.db.QueryContext(ctx, listEndUserPermissionsByProject, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserDataPermission
	for rows.Next() {
		var i EndUserDataPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.DatabaseName,
			&i.ModelName,
			&i.ModelID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.ColumnPolicy,
			&i.RowPolicy,
			&i.Preset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetPermissionsByModel = `-- name: ListPresetPermissionsByModel :many
SELECT id, org_name, project_slug, database_name, model_name, model_id, name, description, type, column_policy, row_policy, preset, created_at, updated_at
FROM end_user_data_permissions
WHERE model_id = ?
  AND org_name = ?
  AND type = 'PRESET'
ORDER BY created_at
`

type ListPresetPermissionsByModelParams struct {
	ModelID string
	OrgName string
}

func (q *Queries) ListPresetPermissionsByModel(ctx context.Context, arg ListPresetPermissionsByModelParams) ([]EndUserDataPermission, error) {
	rows, err := q.db.QueryContext(ctx, listPresetPermissionsByModel, arg.ModelID, arg.OrgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserDataPermission
	for rows.Next() {
		var i EndUserDataPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.DatabaseName,
			&i.ModelName,
			&i.ModelID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.ColumnPolicy,
			&i.RowPolicy,
			&i.Preset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndUserPermission = `-- name: UpdateEndUserPermission :execresult
UPDATE end_user_data_permissions
SET name = ?,
    description = ?,
    column_policy = ?,
    updated_at = NOW(3)
WHERE id = ?
  AND org_name = ?
`

type UpdateEndUserPermissionParams struct {
	Name         string
	Description  sql.NullString
	ColumnPolicy *json.RawMessage
	ID           string
	OrgName      string
}

func (q *Queries) UpdateEndUserPermission(ctx context.Context, arg UpdateEndUserPermissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEndUserPermission,
		arg.Name,
		arg.Description,
		arg.ColumnPolicy,
		arg.ID,
		arg.OrgName,
	)
}

const updateEndUserPresetPermission = `-- name: UpdateEndUserPresetPermission :execresult
UPDATE end_user_data_permissions
SET name = ?,
    description = ?,
    row_policy = ?,
    preset = ?,
    updated_at = NOW(3)
WHERE id = ?
  AND org_name = ?
`

type UpdateEndUserPresetPermissionParams struct {
	Name        string
	Description sql.NullString
	RowPolicy   *json.RawMessage
	Preset      NullEndUserDataPermissionsPreset
	ID          string
	OrgName     string
}

func (q *Queries) UpdateEndUserPresetPermission(ctx context.Context, arg UpdateEndUserPresetPermissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEndUserPresetPermission,
		arg.Name,
		arg.Description,
		arg.RowPolicy,
		arg.Preset,
		arg.ID,
		arg.OrgName,
	)
}
