// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createEndUserPermission = `-- name: CreateEndUserPermission :exec
INSERT INTO end_user_data_permissions (
  id,
  org_name,
  project_slug,
  database_name,
  model_name,
  model_id,
  name,
  description,
  column_policy,
  row_policy
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEndUserPermissionParams struct {
	ID           string
	OrgName      string
	ProjectSlug  string
	DatabaseName sql.NullString
	ModelName    sql.NullString
	ModelID      string
	Name         string
	Description  sql.NullString
	ColumnPolicy *json.RawMessage
	RowPolicy    *json.RawMessage
}

func (q *Queries) CreateEndUserPermission(ctx context.Context, arg CreateEndUserPermissionParams) error {
	_, err := q.db.ExecContext(ctx, createEndUserPermission,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.DatabaseName,
		arg.ModelName,
		arg.ModelID,
		arg.Name,
		arg.Description,
		arg.ColumnPolicy,
		arg.RowPolicy,
	)
	return err
}

const deleteEndUserPermission = `-- name: DeleteEndUserPermission :execresult
DELETE FROM end_user_data_permissions
WHERE id = ?
  AND org_name = ?
`

type DeleteEndUserPermissionParams struct {
	ID      string
	OrgName string
}

func (q *Queries) DeleteEndUserPermission(ctx context.Context, arg DeleteEndUserPermissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEndUserPermission, arg.ID, arg.OrgName)
}

const getEndUserPermissionByID = `-- name: GetEndUserPermissionByID :one
SELECT id, org_name, project_slug, database_name, model_name, model_id, name, description, column_policy, row_policy, created_at, updated_at
FROM end_user_data_permissions
WHERE id = ?
  AND org_name = ?
`

type GetEndUserPermissionByIDParams struct {
	ID      string
	OrgName string
}

func (q *Queries) GetEndUserPermissionByID(ctx context.Context, arg GetEndUserPermissionByIDParams) (EndUserDataPermission, error) {
	row := q.db.QueryRowContext(ctx, getEndUserPermissionByID, arg.ID, arg.OrgName)
	var i EndUserDataPermission
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.DatabaseName,
		&i.ModelName,
		&i.ModelID,
		&i.Name,
		&i.Description,
		&i.ColumnPolicy,
		&i.RowPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndUserPermissionByModelAndName = `-- name: GetEndUserPermissionByModelAndName :one
SELECT id, org_name, project_slug, database_name, model_name, model_id, name, description, column_policy, row_policy, created_at, updated_at
FROM end_user_data_permissions
WHERE model_id = ?
  AND org_name = ?
  AND name = ?
LIMIT 1
`

type GetEndUserPermissionByModelAndNameParams struct {
	ModelID string
	OrgName string
	Name    string
}

func (q *Queries) GetEndUserPermissionByModelAndName(ctx context.Context, arg GetEndUserPermissionByModelAndNameParams) (EndUserDataPermission, error) {
	row := q.db.QueryRowContext(ctx, getEndUserPermissionByModelAndName, arg.ModelID, arg.OrgName, arg.Name)
	var i EndUserDataPermission
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.DatabaseName,
		&i.ModelName,
		&i.ModelID,
		&i.Name,
		&i.Description,
		&i.ColumnPolicy,
		&i.RowPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isPermissionReferencedByBundleItem = `-- name: IsPermissionReferencedByBundleItem :one
SELECT COUNT(*) > 0 AS referenced
FROM end_user_bundle_data_permission_items
WHERE custom_permission_id = ?
`

func (q *Queries) IsPermissionReferencedByBundleItem(ctx context.Context, customPermissionID sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, isPermissionReferencedByBundleItem, customPermissionID)
	var referenced bool
	err := row.Scan(&referenced)
	return referenced, err
}

const listEndUserPermissionsByModel = `-- name: ListEndUserPermissionsByModel :many
SELECT id, org_name, project_slug, database_name, model_name, model_id, name, description, column_policy, row_policy, created_at, updated_at
FROM end_user_data_permissions
WHERE model_id = ?
  AND org_name = ?
ORDER BY created_at
`

type ListEndUserPermissionsByModelParams struct {
	ModelID string
	OrgName string
}

func (q *Queries) ListEndUserPermissionsByModel(ctx context.Context, arg ListEndUserPermissionsByModelParams) ([]EndUserDataPermission, error) {
	rows, err := q.db.QueryContext(ctx, listEndUserPermissionsByModel, arg.ModelID, arg.OrgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserDataPermission
	for rows.Next() {
		var i EndUserDataPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.DatabaseName,
			&i.ModelName,
			&i.ModelID,
			&i.Name,
			&i.Description,
			&i.ColumnPolicy,
			&i.RowPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndUserPermissionsByProject = `-- name: ListEndUserPermissionsByProject :many
SELECT id, org_name, project_slug, database_name, model_name, model_id, name, description, column_policy, row_policy, created_at, updated_at
FROM end_user_data_permissions
WHERE org_name = ?
  AND project_slug = ?
ORDER BY created_at
`

type ListEndUserPermissionsByProjectParams struct {
	OrgName     string
	ProjectSlug string
}

func (q *Queries) ListEndUserPermissionsByProject(ctx context.Context, arg ListEndUserPermissionsByProjectParams) ([]EndUserDataPermission, error) {
	rows, err := q.db.QueryContext(ctx, listEndUserPermissionsByProject, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserDataPermission
	for rows.Next() {
		var i EndUserDataPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.DatabaseName,
			&i.ModelName,
			&i.ModelID,
			&i.Name,
			&i.Description,
			&i.ColumnPolicy,
			&i.RowPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndUserPermission = `-- name: UpdateEndUserPermission :execresult
UPDATE end_user_data_permissions
SET name = ?,
    description = ?,
    column_policy = ?,
    row_policy = ?,
    updated_at = NOW(3)
WHERE id = ?
  AND org_name = ?
`

type UpdateEndUserPermissionParams struct {
	Name         string
	Description  sql.NullString
	ColumnPolicy *json.RawMessage
	RowPolicy    *json.RawMessage
	ID           string
	OrgName      string
}

func (q *Queries) UpdateEndUserPermission(ctx context.Context, arg UpdateEndUserPermissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEndUserPermission,
		arg.Name,
		arg.Description,
		arg.ColumnPolicy,
		arg.RowPolicy,
		arg.ID,
		arg.OrgName,
	)
}
