// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package dbgen

import (
	"context"
	"database/sql"
)

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects
SET status = 'archived', updated_at = NOW(3)
WHERE slug = ? AND org_name = ?
`

type ArchiveProjectParams struct {
	Slug    string
	OrgName string
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) error {
	_, err := q.db.ExecContext(ctx, archiveProject, arg.Slug, arg.OrgName)
	return err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (org_name, slug, title, description, login_url, cluster_id, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateProjectParams struct {
	OrgName     string
	Slug        string
	Title       string
	Description sql.NullString
	LoginUrl    sql.NullString
	ClusterID   sql.NullString
	Status      string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.OrgName,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.LoginUrl,
		arg.ClusterID,
		arg.Status,
	)
	return err
}

const existsProjectBySlug = `-- name: ExistsProjectBySlug :one
SELECT COUNT(*) FROM projects
WHERE slug = ? AND org_name = ?
`

type ExistsProjectBySlugParams struct {
	Slug    string
	OrgName string
}

func (q *Queries) ExistsProjectBySlug(ctx context.Context, arg ExistsProjectBySlugParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsProjectBySlug, arg.Slug, arg.OrgName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProjectByClusterID = `-- name: GetProjectByClusterID :one
SELECT org_name, slug, title, description, login_url, status, cluster_id, created_at, updated_at FROM projects
WHERE org_name = ? AND cluster_id = ?
LIMIT 1
`

type GetProjectByClusterIDParams struct {
	OrgName   string
	ClusterID sql.NullString
}

func (q *Queries) GetProjectByClusterID(ctx context.Context, arg GetProjectByClusterIDParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByClusterID, arg.OrgName, arg.ClusterID)
	var i Project
	err := row.Scan(
		&i.OrgName,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LoginUrl,
		&i.Status,
		&i.ClusterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlugAndOrg = `-- name: GetProjectBySlugAndOrg :one
SELECT org_name, slug, title, description, login_url, status, cluster_id, created_at, updated_at FROM projects
WHERE slug = ? AND org_name = ?
LIMIT 1
`

type GetProjectBySlugAndOrgParams struct {
	Slug    string
	OrgName string
}

func (q *Queries) GetProjectBySlugAndOrg(ctx context.Context, arg GetProjectBySlugAndOrgParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlugAndOrg, arg.Slug, arg.OrgName)
	var i Project
	err := row.Scan(
		&i.OrgName,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LoginUrl,
		&i.Status,
		&i.ClusterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT org_name, slug, title, description, login_url, status, cluster_id, created_at, updated_at FROM projects
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.OrgName,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.LoginUrl,
			&i.Status,
			&i.ClusterID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT org_name, slug, title, description, login_url, status, cluster_id, created_at, updated_at FROM projects
WHERE org_name = ?
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOrg(ctx context.Context, orgName string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByOrg, orgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.OrgName,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.LoginUrl,
			&i.Status,
			&i.ClusterID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
SET title = ?, description = ?, login_url = ?, cluster_id = ?, updated_at = NOW(3)
WHERE slug = ? AND org_name = ?
`

type UpdateProjectParams struct {
	Title       string
	Description sql.NullString
	LoginUrl    sql.NullString
	ClusterID   sql.NullString
	Slug        string
	OrgName     string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.Title,
		arg.Description,
		arg.LoginUrl,
		arg.ClusterID,
		arg.Slug,
		arg.OrgName,
	)
	return err
}
