// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) error
	AssignBundleToRole(ctx context.Context, arg AssignBundleToRoleParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	BindBelongsToFKIDToFields(ctx context.Context, arg BindBelongsToFKIDToFieldsParams) error
	ClearBundleDataPermissionItems(ctx context.Context, bundleID string) error
	CountFieldsByModelID(ctx context.Context, modelID string) (int64, error)
	CountMembershipsByUser(ctx context.Context, userID string) (int64, error)
	CountModelDatabases(ctx context.Context, arg CountModelDatabasesParams) (int64, error)
	CountModels(ctx context.Context, arg CountModelsParams) (int64, error)
	CreateDatabaseCluster(ctx context.Context, arg CreateDatabaseClusterParams) error
	CreateEndUserBundle(ctx context.Context, arg CreateEndUserBundleParams) error
	CreateEndUserPermission(ctx context.Context, arg CreateEndUserPermissionParams) error
	CreateEndUserRole(ctx context.Context, arg CreateEndUserRoleParams) error
	CreateEnumDefinition(ctx context.Context, arg CreateEnumDefinitionParams) error
	CreateFieldDefinition(ctx context.Context, arg CreateFieldDefinitionParams) error
	CreateFieldEnumAssociation(ctx context.Context, arg CreateFieldEnumAssociationParams) error
	CreateInitialProfile(ctx context.Context, arg CreateInitialProfileParams) error
	CreateLogicalForeignKey(ctx context.Context, arg CreateLogicalForeignKeyParams) error
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	CreateModel(ctx context.Context, arg CreateModelParams) error
	CreateModelGroup(ctx context.Context, arg CreateModelGroupParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	CreatePermission(ctx context.Context, arg CreatePermissionParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (sql.Result, error)
	DeleteDatabaseCluster(ctx context.Context, arg DeleteDatabaseClusterParams) error
	DeleteEndUserBundle(ctx context.Context, arg DeleteEndUserBundleParams) (sql.Result, error)
	DeleteEndUserPermission(ctx context.Context, arg DeleteEndUserPermissionParams) (sql.Result, error)
	DeleteEndUserRole(ctx context.Context, arg DeleteEndUserRoleParams) (sql.Result, error)
	DeleteEnum(ctx context.Context, arg DeleteEnumParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteFieldEnumAssociation(ctx context.Context, arg DeleteFieldEnumAssociationParams) error
	DeleteFieldEnumAssociationsByModelID(ctx context.Context, modelID string) error
	DeleteFieldsByModelID(ctx context.Context, modelID string) error
	DeleteFieldsByNames(ctx context.Context, arg DeleteFieldsByNamesParams) (sql.Result, error)
	DeleteLogicalForeignKeyByPairID(ctx context.Context, arg DeleteLogicalForeignKeyByPairIDParams) error
	DeleteMembership(ctx context.Context, id string) error
	DeleteModel(ctx context.Context, id string) error
	DeleteModelGroup(ctx context.Context, id string) error
	DeleteModelRLSPolicy(ctx context.Context, modelID string) error
	DeleteOldBundleSnapshots(ctx context.Context, arg DeleteOldBundleSnapshotsParams) error
	DeletePermission(ctx context.Context, arg DeletePermissionParams) error
	DeletePermissionsByRole(ctx context.Context, roleID int64) error
	DeleteProjectAuthSchema(ctx context.Context, arg DeleteProjectAuthSchemaParams) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error
	DeleteUserRolesByRole(ctx context.Context, roleID int64) error
	ExistsByPhone(ctx context.Context, phone string) (bool, error)
	ExistsByUserName(ctx context.Context, name string) (bool, error)
	ExistsDatabaseClusterByProjectKey(ctx context.Context, arg ExistsDatabaseClusterByProjectKeyParams) (int64, error)
	ExistsEnumByName(ctx context.Context, arg ExistsEnumByNameParams) (int64, error)
	ExistsFieldByName(ctx context.Context, arg ExistsFieldByNameParams) (int64, error)
	ExistsModelRLSPolicy(ctx context.Context, modelID string) (bool, error)
	ExistsOrganizationByName(ctx context.Context, name string) (int64, error)
	ExistsProjectBySlug(ctx context.Context, arg ExistsProjectBySlugParams) (int64, error)
	ExistsUserByExternalID(ctx context.Context, externalID sql.NullString) (int64, error)
	FindFieldsByBelongsToFKID(ctx context.Context, arg FindFieldsByBelongsToFKIDParams) ([]FindFieldsByBelongsToFKIDRow, error)
	FindFieldsByRelateFKID(ctx context.Context, arg FindFieldsByRelateFKIDParams) ([]FindFieldsByRelateFKIDRow, error)
	FindIDByExternalID(ctx context.Context, externalID sql.NullString) (string, error)
	FindLogicalForeignKeysByModelID(ctx context.Context, arg FindLogicalForeignKeysByModelIDParams) ([]FindLogicalForeignKeysByModelIDRow, error)
	FindLogicalForeignKeysByPairID(ctx context.Context, arg FindLogicalForeignKeysByPairIDParams) ([]FindLogicalForeignKeysByPairIDRow, error)
	FindLogicalForeignKeysByRefModelID(ctx context.Context, arg FindLogicalForeignKeysByRefModelIDParams) ([]FindLogicalForeignKeysByRefModelIDRow, error)
	FindModelsByDeploymentStatus(ctx context.Context, statuses []sql.NullString) ([]Model, error)
	GetAllModels(ctx context.Context) ([]Model, error)
	GetBundleCurrentVersion(ctx context.Context, bundleID string) (interface{}, error)
	GetBundleDataPermissionItemByBundleAndModel(ctx context.Context, arg GetBundleDataPermissionItemByBundleAndModelParams) (EndUserBundleDataPermissionItem, error)
	// ⚡ 鉴权链 Step 3: 隐式角色关联的权限包 ID 列表（对所有认证用户执行，无需 user_id）
	GetBundleIDsByImplicitRoles(ctx context.Context, arg GetBundleIDsByImplicitRolesParams) ([]string, error)
	// ⚡ 鉴权链 Step 1: 用户直接关联的权限包 ID 列表
	GetBundleIDsByUserDirect(ctx context.Context, arg GetBundleIDsByUserDirectParams) ([]string, error)
	// ⚡ 鉴权链 Step 2: 通过显式角色关联的权限包 ID 列表（单次 JOIN 查询，避免 N+1）
	GetBundleIDsByUserExplicitRoles(ctx context.Context, arg GetBundleIDsByUserExplicitRolesParams) ([]string, error)
	GetBundleSnapshotByVersion(ctx context.Context, arg GetBundleSnapshotByVersionParams) (EndUserPermissionBundleSnapshot, error)
	// ⚡ 鉴权链 Step 5: 批量加载 custom permission 实体（CUSTOM item 引用）
	GetCustomPermissionsByIDs(ctx context.Context, arg GetCustomPermissionsByIDsParams) ([]EndUserDataPermission, error)
	// ⚡ 鉴权链 Step 4: 展开权限包 → data permission items
	GetDataPermissionItemsByBundleIDs(ctx context.Context, bundleids []string) ([]EndUserBundleDataPermissionItem, error)
	GetDatabaseClusterByID(ctx context.Context, arg GetDatabaseClusterByIDParams) (DatabaseCluster, error)
	GetDatabaseClusterByProjectKey(ctx context.Context, arg GetDatabaseClusterByProjectKeyParams) (DatabaseCluster, error)
	GetEndUserBundleByID(ctx context.Context, arg GetEndUserBundleByIDParams) (EndUserPermissionBundle, error)
	GetEndUserBundleBySlug(ctx context.Context, arg GetEndUserBundleBySlugParams) (EndUserPermissionBundle, error)
	GetEndUserPermissionByID(ctx context.Context, arg GetEndUserPermissionByIDParams) (EndUserDataPermission, error)
	GetEndUserPermissionByModelAndName(ctx context.Context, arg GetEndUserPermissionByModelAndNameParams) (EndUserDataPermission, error)
	GetEndUserRoleByID(ctx context.Context, arg GetEndUserRoleByIDParams) (EndUserRole, error)
	GetEnumByID(ctx context.Context, id string) (ModelEnum, error)
	GetEnumByName(ctx context.Context, arg GetEnumByNameParams) (ModelEnum, error)
	GetEnumReferencesByName(ctx context.Context, arg GetEnumReferencesByNameParams) ([]GetEnumReferencesByNameRow, error)
	GetEnumsByNames(ctx context.Context, arg GetEnumsByNamesParams) ([]ModelEnum, error)
	GetFieldByModelIDAndName(ctx context.Context, arg GetFieldByModelIDAndNameParams) (FieldDefinition, error)
	GetFieldEnumAssociationByField(ctx context.Context, arg GetFieldEnumAssociationByFieldParams) (ModelFieldEnumAssociation, error)
	GetFieldEnumAssociationsByEnumName(ctx context.Context, arg GetFieldEnumAssociationsByEnumNameParams) ([]ModelFieldEnumAssociation, error)
	GetFieldEnumAssociationsByModelID(ctx context.Context, modelID string) ([]ModelFieldEnumAssociation, error)
	GetFieldsByModelID(ctx context.Context, modelID string) ([]FieldDefinition, error)
	GetLogicalForeignKeyByID(ctx context.Context, id string) (GetLogicalForeignKeyByIDRow, error)
	GetMembershipByID(ctx context.Context, id string) (UserOrganization, error)
	GetMembershipByUserAndOrg(ctx context.Context, arg GetMembershipByUserAndOrgParams) (UserOrganization, error)
	GetModelByID(ctx context.Context, id string) (Model, error)
	GetModelByName(ctx context.Context, arg GetModelByNameParams) (Model, error)
	GetModelGroupByID(ctx context.Context, id string) (ModelGroup, error)
	GetModelGroupByName(ctx context.Context, arg GetModelGroupByNameParams) (ModelGroup, error)
	GetModelMetaByIDs(ctx context.Context, arg GetModelMetaByIDsParams) ([]Model, error)
	// ============================================
	// RLS (Row Level Security) Queries
	// ============================================
	// ----------------------------------------
	// Model RLS Policy Queries
	// ----------------------------------------
	GetModelRLSPolicy(ctx context.Context, modelID string) (ModelRlsPolicy, error)
	GetOrganizationByName(ctx context.Context, name string) (Organization, error)
	GetProfileByUserID(ctx context.Context, arg GetProfileByUserIDParams) (GetProfileByUserIDRow, error)
	// ----------------------------------------
	// Project Auth Schema Queries
	// ----------------------------------------
	GetProjectAuthSchema(ctx context.Context, arg GetProjectAuthSchemaParams) (ProjectAuthSchema, error)
	GetProjectByClusterID(ctx context.Context, arg GetProjectByClusterIDParams) (Project, error)
	GetProjectBySlugAndOrg(ctx context.Context, arg GetProjectBySlugAndOrgParams) (Project, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRoleByNameAndOrg(ctx context.Context, arg GetRoleByNameAndOrgParams) (Role, error)
	GetSystemRoleByName(ctx context.Context, name string) (Role, error)
	GetTailFieldDisplayOrder(ctx context.Context, modelID string) (string, error)
	GetTailModelGroupDisplayOrder(ctx context.Context, arg GetTailModelGroupDisplayOrderParams) (string, error)
	GetUserByExternalID(ctx context.Context, externalID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByName(ctx context.Context, name string) (GetUserByNameRow, error)
	GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error)
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (UserRole, error)
	GrantBundleToUser(ctx context.Context, arg GrantBundleToUserParams) error
	InsertBundleSnapshot(ctx context.Context, arg InsertBundleSnapshotParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	InsertSecurityAuditLog(ctx context.Context, arg InsertSecurityAuditLogParams) error
	// 检查指定用户是否为 Org 内置 admin（is_builtin=true）
	IsEndUserBuiltin(ctx context.Context, arg IsEndUserBuiltinParams) (bool, error)
	IsPermissionReferencedByBundleItem(ctx context.Context, customPermissionID sql.NullString) (bool, error)
	ListBundleDataPermissionItems(ctx context.Context, bundleID string) ([]EndUserBundleDataPermissionItem, error)
	ListBundleSnapshots(ctx context.Context, bundleID string) ([]EndUserPermissionBundleSnapshot, error)
	ListBundlesByRole(ctx context.Context, roleID string) ([]EndUserPermissionBundle, error)
	ListBundlesByUser(ctx context.Context, arg ListBundlesByUserParams) ([]EndUserPermissionBundle, error)
	ListDatabaseClusters(ctx context.Context, arg ListDatabaseClustersParams) ([]DatabaseCluster, error)
	// 全局扫描：不按租户过滤，供连接池同步使用
	ListDatabaseClustersUpdatedAfter(ctx context.Context, updatedAt sql.NullTime) ([]DatabaseCluster, error)
	ListEndUserBundlesByProject(ctx context.Context, arg ListEndUserBundlesByProjectParams) ([]EndUserPermissionBundle, error)
	ListEndUserPermissionsByModel(ctx context.Context, arg ListEndUserPermissionsByModelParams) ([]EndUserDataPermission, error)
	ListEndUserPermissionsByProject(ctx context.Context, arg ListEndUserPermissionsByProjectParams) ([]EndUserDataPermission, error)
	ListEndUserRolesByProject(ctx context.Context, arg ListEndUserRolesByProjectParams) ([]EndUserRole, error)
	ListEnums(ctx context.Context, arg ListEnumsParams) ([]ModelEnum, error)
	ListMembershipsByOrg(ctx context.Context, orgName string) ([]UserOrganization, error)
	ListMembershipsByUser(ctx context.Context, userID string) ([]UserOrganization, error)
	ListMembershipsWithOrgDetails(ctx context.Context, arg ListMembershipsWithOrgDetailsParams) ([]ListMembershipsWithOrgDetailsRow, error)
	ListMembershipsWithUserName(ctx context.Context, orgName string) ([]ListMembershipsWithUserNameRow, error)
	ListModelDatabases(ctx context.Context, arg ListModelDatabasesParams) ([]string, error)
	ListModelGroupsByProject(ctx context.Context, arg ListModelGroupsByProjectParams) ([]ModelGroup, error)
	ListModels(ctx context.Context, arg ListModelsParams) ([]Model, error)
	ListOrganizationsByUser(ctx context.Context, userID string) ([]Organization, error)
	ListPermissionsByRole(ctx context.Context, roleID int64) ([]RolePermission, error)
	ListPermissionsByRoleAndOrg(ctx context.Context, arg ListPermissionsByRoleAndOrgParams) ([]RolePermission, error)
	// 分页查询 Project 下有角色分配的用户列表（支持用户名搜索和角色过滤）
	ListProjectEndUserRoleUsers(ctx context.Context, arg ListProjectEndUserRoleUsersParams) ([]ListProjectEndUserRoleUsersRow, error)
	// 统计 Project 下有角色分配的用户总数（支持用户名搜索和角色过滤）
	ListProjectEndUserRoleUsersCount(ctx context.Context, arg ListProjectEndUserRoleUsersCountParams) (int64, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProjectsByOrg(ctx context.Context, orgName string) ([]Project, error)
	ListRoleUsers(ctx context.Context, arg ListRoleUsersParams) ([]UserRole, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListRolesByOrg(ctx context.Context, orgName string) ([]Role, error)
	ListRolesByOrgIncludeSystem(ctx context.Context, orgName string) ([]Role, error)
	ListRolesByUser(ctx context.Context, arg ListRolesByUserParams) ([]string, error)
	ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]UserRole, error)
	RemoveBundleDataPermissionItem(ctx context.Context, arg RemoveBundleDataPermissionItemParams) (sql.Result, error)
	RevokeAllRefreshTokensByUserID(ctx context.Context, userID string) error
	RevokeBundleFromRole(ctx context.Context, arg RevokeBundleFromRoleParams) (sql.Result, error)
	RevokeBundleFromUser(ctx context.Context, arg RevokeBundleFromUserParams) (sql.Result, error)
	RevokeRefreshToken(ctx context.Context, id string) error
	RevokeRoleFromUser(ctx context.Context, arg RevokeRoleFromUserParams) (sql.Result, error)
	UpdateDatabaseClusterWithVersion(ctx context.Context, arg UpdateDatabaseClusterWithVersionParams) (sql.Result, error)
	UpdateEndUserBundle(ctx context.Context, arg UpdateEndUserBundleParams) (sql.Result, error)
	UpdateEndUserPermission(ctx context.Context, arg UpdateEndUserPermissionParams) (sql.Result, error)
	// 注意：is_implicit=TRUE 或 is_protected=TRUE 的角色由业务层阻断，不走 SQL 层约束
	UpdateEndUserRole(ctx context.Context, arg UpdateEndUserRoleParams) (sql.Result, error)
	UpdateEnum(ctx context.Context, arg UpdateEnumParams) error
	UpdateField(ctx context.Context, arg UpdateFieldParams) (sql.Result, error)
	UpdateFieldDisplayOrder(ctx context.Context, arg UpdateFieldDisplayOrderParams) error
	UpdateFieldsStatus(ctx context.Context, arg UpdateFieldsStatusParams) error
	UpdateMembership(ctx context.Context, arg UpdateMembershipParams) error
	UpdateModel(ctx context.Context, arg UpdateModelParams) (sql.Result, error)
	UpdateModelDeploymentStatus(ctx context.Context, arg UpdateModelDeploymentStatusParams) error
	UpdateModelGroup(ctx context.Context, arg UpdateModelGroupParams) error
	UpdateModelWithVersion(ctx context.Context, arg UpdateModelWithVersionParams) (sql.Result, error)
	UpdateModelsGroupID(ctx context.Context, arg UpdateModelsGroupIDParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
	UpdateProfileByUserID(ctx context.Context, arg UpdateProfileByUserIDParams) (sql.Result, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	// Replace 语义：同一 bundle+model 最多一个 item
	UpsertBundleDataPermissionItem(ctx context.Context, arg UpsertBundleDataPermissionItemParams) error
	UpsertModelRLSPolicy(ctx context.Context, arg UpsertModelRLSPolicyParams) error
	UpsertProjectAuthSchema(ctx context.Context, arg UpsertProjectAuthSchemaParams) error
}

var _ Querier = (*Queries)(nil)
