// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) error
	BindBelongsToFKIDToFields(ctx context.Context, arg BindBelongsToFKIDToFieldsParams) error
	CountFieldsByModelID(ctx context.Context, modelID string) (int64, error)
	CountModelDatabaseCatalog(ctx context.Context, arg CountModelDatabaseCatalogParams) (int64, error)
	CountModelDatabases(ctx context.Context, arg CountModelDatabasesParams) (int64, error)
	CountModels(ctx context.Context, arg CountModelsParams) (int64, error)
	CountUsersByOrg(ctx context.Context, orgName string) (int64, error)
	CreateDatabaseCluster(ctx context.Context, arg CreateDatabaseClusterParams) error
	CreateEnumDefinition(ctx context.Context, arg CreateEnumDefinitionParams) error
	CreateFieldDefinition(ctx context.Context, arg CreateFieldDefinitionParams) error
	CreateFieldEnumAssociation(ctx context.Context, arg CreateFieldEnumAssociationParams) error
	CreateInitialProfile(ctx context.Context, arg CreateInitialProfileParams) error
	CreateLogicalForeignKey(ctx context.Context, arg CreateLogicalForeignKeyParams) error
	CreateModel(ctx context.Context, arg CreateModelParams) error
	CreateModelDatabase(ctx context.Context, arg CreateModelDatabaseParams) error
	CreateModelDatabaseSyncJob(ctx context.Context, arg CreateModelDatabaseSyncJobParams) error
	CreateModelGroup(ctx context.Context, arg CreateModelGroupParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	CreatePermission(ctx context.Context, arg CreatePermissionParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (sql.Result, error)
	DeleteDatabaseCluster(ctx context.Context, arg DeleteDatabaseClusterParams) error
	DeleteEnum(ctx context.Context, arg DeleteEnumParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteFieldEnumAssociation(ctx context.Context, arg DeleteFieldEnumAssociationParams) error
	DeleteFieldEnumAssociationsByModelID(ctx context.Context, modelID string) error
	DeleteFieldsByModelID(ctx context.Context, modelID string) error
	DeleteFieldsByNames(ctx context.Context, arg DeleteFieldsByNamesParams) (sql.Result, error)
	DeleteLogicalForeignKeyByPairID(ctx context.Context, arg DeleteLogicalForeignKeyByPairIDParams) error
	DeleteModel(ctx context.Context, id string) error
	DeleteModelDatabase(ctx context.Context, arg DeleteModelDatabaseParams) error
	DeleteModelGroup(ctx context.Context, id string) error
	DeletePermission(ctx context.Context, arg DeletePermissionParams) error
	DeletePermissionsByRole(ctx context.Context, roleID int64) error
	DeletePoliciesByModel(ctx context.Context, arg DeletePoliciesByModelParams) error
	DeletePolicy(ctx context.Context, arg DeletePolicyParams) error
	DeleteProjectAuthSchema(ctx context.Context, arg DeleteProjectAuthSchemaParams) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error
	DeleteUserRolesByRole(ctx context.Context, roleID int64) error
	ExistsByPhoneInOrg(ctx context.Context, arg ExistsByPhoneInOrgParams) (bool, error)
	ExistsByUserNameInOrg(ctx context.Context, arg ExistsByUserNameInOrgParams) (bool, error)
	ExistsDatabaseClusterByProjectKey(ctx context.Context, arg ExistsDatabaseClusterByProjectKeyParams) (int64, error)
	ExistsEnumByName(ctx context.Context, arg ExistsEnumByNameParams) (int64, error)
	ExistsFieldByName(ctx context.Context, arg ExistsFieldByNameParams) (int64, error)
	ExistsOrganizationByName(ctx context.Context, name string) (int64, error)
	ExistsOrganizationByPhone(ctx context.Context, phone string) (int64, error)
	ExistsProjectBySlug(ctx context.Context, arg ExistsProjectBySlugParams) (int64, error)
	ExistsUserByExternalID(ctx context.Context, externalID sql.NullString) (int64, error)
	FailStaleSyncJobs(ctx context.Context, updatedAt time.Time) error
	FindFieldsByBelongsToFKID(ctx context.Context, arg FindFieldsByBelongsToFKIDParams) ([]FindFieldsByBelongsToFKIDRow, error)
	FindFieldsByRelateFKID(ctx context.Context, arg FindFieldsByRelateFKIDParams) ([]FindFieldsByRelateFKIDRow, error)
	FindIDByExternalID(ctx context.Context, externalID sql.NullString) (string, error)
	FindLogicalForeignKeysByModelID(ctx context.Context, arg FindLogicalForeignKeysByModelIDParams) ([]FindLogicalForeignKeysByModelIDRow, error)
	FindLogicalForeignKeysByPairID(ctx context.Context, arg FindLogicalForeignKeysByPairIDParams) ([]FindLogicalForeignKeysByPairIDRow, error)
	FindLogicalForeignKeysByRefModelID(ctx context.Context, arg FindLogicalForeignKeysByRefModelIDParams) ([]FindLogicalForeignKeysByRefModelIDRow, error)
	FindModelsByDeploymentStatus(ctx context.Context, statuses []sql.NullString) ([]Model, error)
	GetActiveModelDatabaseSyncJobByDatabase(ctx context.Context, arg GetActiveModelDatabaseSyncJobByDatabaseParams) (ModelDatabaseSyncJob, error)
	GetAllModels(ctx context.Context) ([]Model, error)
	GetDatabaseClusterByID(ctx context.Context, arg GetDatabaseClusterByIDParams) (DatabaseCluster, error)
	GetDatabaseClusterByProjectKey(ctx context.Context, arg GetDatabaseClusterByProjectKeyParams) (DatabaseCluster, error)
	GetEnumByID(ctx context.Context, id string) (ModelEnum, error)
	GetEnumByName(ctx context.Context, arg GetEnumByNameParams) (ModelEnum, error)
	GetEnumReferencesByName(ctx context.Context, arg GetEnumReferencesByNameParams) ([]GetEnumReferencesByNameRow, error)
	GetEnumsByNames(ctx context.Context, arg GetEnumsByNamesParams) ([]ModelEnum, error)
	GetFieldByModelIDAndName(ctx context.Context, arg GetFieldByModelIDAndNameParams) (FieldDefinition, error)
	GetFieldEnumAssociationByField(ctx context.Context, arg GetFieldEnumAssociationByFieldParams) (ModelFieldEnumAssociation, error)
	GetFieldEnumAssociationsByEnumName(ctx context.Context, arg GetFieldEnumAssociationsByEnumNameParams) ([]ModelFieldEnumAssociation, error)
	GetFieldEnumAssociationsByModelID(ctx context.Context, modelID string) ([]ModelFieldEnumAssociation, error)
	GetFieldsByModelID(ctx context.Context, modelID string) ([]FieldDefinition, error)
	GetLogicalForeignKeyByID(ctx context.Context, id string) (GetLogicalForeignKeyByIDRow, error)
	GetModelByID(ctx context.Context, id string) (Model, error)
	GetModelByName(ctx context.Context, arg GetModelByNameParams) (Model, error)
	GetModelDatabaseByID(ctx context.Context, arg GetModelDatabaseByIDParams) (ModelDatabase, error)
	GetModelDatabaseByName(ctx context.Context, arg GetModelDatabaseByNameParams) (ModelDatabase, error)
	GetModelDatabaseSyncJobByID(ctx context.Context, arg GetModelDatabaseSyncJobByIDParams) (ModelDatabaseSyncJob, error)
	GetModelGroupByID(ctx context.Context, id string) (ModelGroup, error)
	GetModelGroupByName(ctx context.Context, arg GetModelGroupByNameParams) (ModelGroup, error)
	GetModelMetaByIDs(ctx context.Context, arg GetModelMetaByIDsParams) ([]Model, error)
	GetOrganizationByName(ctx context.Context, name string) (Organization, error)
	GetOrganizationByPhone(ctx context.Context, phone string) (Organization, error)
	GetProfileByUserID(ctx context.Context, arg GetProfileByUserIDParams) (GetProfileByUserIDRow, error)
	// ============================================
	// RLS (Row Level Security) Queries
	// ============================================
	// NOTE: model_rls_policies queries moved to rls_policy_v2.sql
	// Old single-policy queries (GetModelRLSPolicy, UpsertModelRLSPolicy,
	// DeleteModelRLSPolicy, ExistsModelRLSPolicy) removed.
	// ----------------------------------------
	// Project Auth Schema Queries
	// ----------------------------------------
	GetProjectAuthSchema(ctx context.Context, arg GetProjectAuthSchemaParams) (ProjectAuthSchema, error)
	GetProjectByClusterID(ctx context.Context, arg GetProjectByClusterIDParams) (Project, error)
	GetProjectBySlugAndOrg(ctx context.Context, arg GetProjectBySlugAndOrgParams) (Project, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRoleByNameAndOrg(ctx context.Context, arg GetRoleByNameAndOrgParams) (Role, error)
	GetSystemRoleByName(ctx context.Context, name string) (Role, error)
	GetTailFieldDisplayOrder(ctx context.Context, modelID string) (string, error)
	GetTailModelGroupDisplayOrder(ctx context.Context, arg GetTailModelGroupDisplayOrderParams) (string, error)
	GetUserByExternalID(ctx context.Context, externalID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByNameInOrg(ctx context.Context, arg GetUserByNameInOrgParams) (GetUserByNameInOrgRow, error)
	GetUserByPhoneInOrg(ctx context.Context, arg GetUserByPhoneInOrgParams) (GetUserByPhoneInOrgRow, error)
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (UserRole, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	InsertSecurityAuditLog(ctx context.Context, arg InsertSecurityAuditLogParams) error
	ListDatabaseClusters(ctx context.Context, arg ListDatabaseClustersParams) ([]DatabaseCluster, error)
	// 全局扫描：不按租户过滤，供连接池同步使用
	ListDatabaseClustersUpdatedAfter(ctx context.Context, updatedAt sql.NullTime) ([]DatabaseCluster, error)
	ListEnums(ctx context.Context, arg ListEnumsParams) ([]ModelEnum, error)
	ListModelDatabaseCatalog(ctx context.Context, arg ListModelDatabaseCatalogParams) ([]string, error)
	ListModelDatabases(ctx context.Context, arg ListModelDatabasesParams) ([]string, error)
	ListModelDatabasesByProject(ctx context.Context, arg ListModelDatabasesByProjectParams) ([]ModelDatabase, error)
	ListModelGroupsByProject(ctx context.Context, arg ListModelGroupsByProjectParams) ([]ModelGroup, error)
	ListModels(ctx context.Context, arg ListModelsParams) ([]Model, error)
	ListOrganizationsByUser(ctx context.Context, id string) ([]Organization, error)
	ListPermissionsByRole(ctx context.Context, roleID int64) ([]RolePermission, error)
	ListPermissionsByRoleAndOrg(ctx context.Context, arg ListPermissionsByRoleAndOrgParams) ([]RolePermission, error)
	// ============================================
	// RLS Policy V2 Queries — 多策略存储查询
	// ============================================
	ListPoliciesByAction(ctx context.Context, arg ListPoliciesByActionParams) ([]ModelRlsPolicy, error)
	ListPoliciesByModel(ctx context.Context, arg ListPoliciesByModelParams) ([]ModelRlsPolicy, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProjectsByOrg(ctx context.Context, orgName string) ([]Project, error)
	ListRoleUsers(ctx context.Context, arg ListRoleUsersParams) ([]UserRole, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListRolesByOrg(ctx context.Context, orgName string) ([]Role, error)
	ListRolesByOrgIncludeSystem(ctx context.Context, orgName string) ([]Role, error)
	ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]UserRole, error)
	ListUsersByOrgWithName(ctx context.Context, orgName string) ([]ListUsersByOrgWithNameRow, error)
	ListUsersWithOrgDetails(ctx context.Context, arg ListUsersWithOrgDetailsParams) ([]ListUsersWithOrgDetailsRow, error)
	PolicyExists(ctx context.Context, arg PolicyExistsParams) (bool, error)
	RevokeAllRefreshTokensByUserID(ctx context.Context, userID string) error
	RevokeRefreshToken(ctx context.Context, id string) error
	UpdateDatabaseClusterWithVersion(ctx context.Context, arg UpdateDatabaseClusterWithVersionParams) (sql.Result, error)
	UpdateEnum(ctx context.Context, arg UpdateEnumParams) error
	UpdateField(ctx context.Context, arg UpdateFieldParams) (sql.Result, error)
	UpdateFieldDisplayOrder(ctx context.Context, arg UpdateFieldDisplayOrderParams) error
	UpdateFieldsStatus(ctx context.Context, arg UpdateFieldsStatusParams) error
	UpdateInsertionOrderField(ctx context.Context, arg UpdateInsertionOrderFieldParams) error
	UpdateModel(ctx context.Context, arg UpdateModelParams) (sql.Result, error)
	UpdateModelDatabase(ctx context.Context, arg UpdateModelDatabaseParams) error
	UpdateModelDatabaseSyncJob(ctx context.Context, arg UpdateModelDatabaseSyncJobParams) error
	UpdateModelDeploymentStatus(ctx context.Context, arg UpdateModelDeploymentStatusParams) error
	UpdateModelGroup(ctx context.Context, arg UpdateModelGroupParams) error
	UpdateModelWithVersion(ctx context.Context, arg UpdateModelWithVersionParams) (sql.Result, error)
	UpdateModelsGroupID(ctx context.Context, arg UpdateModelsGroupIDParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
	UpdateProfileByUserID(ctx context.Context, arg UpdateProfileByUserIDParams) (sql.Result, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) error
	UpsertProjectAuthSchema(ctx context.Context, arg UpsertProjectAuthSchemaParams) error
}

var _ Querier = (*Queries)(nil)
