// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rls.sql

package dbgen

import (
	"context"
	"encoding/json"
)

const deleteProjectAuthSchema = `-- name: DeleteProjectAuthSchema :exec
DELETE FROM project_auth_schemas
WHERE org_name = ? AND project_slug = ?
`

type DeleteProjectAuthSchemaParams struct {
	OrgName     string
	ProjectSlug string
}

func (q *Queries) DeleteProjectAuthSchema(ctx context.Context, arg DeleteProjectAuthSchemaParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectAuthSchema, arg.OrgName, arg.ProjectSlug)
	return err
}

const getProjectAuthSchema = `-- name: GetProjectAuthSchema :one


SELECT id, org_name, project_slug, variables, created_at, updated_at FROM project_auth_schemas
WHERE org_name = ? AND project_slug = ?
`

type GetProjectAuthSchemaParams struct {
	OrgName     string
	ProjectSlug string
}

// ============================================
// Project Auth Schema Queries
// ============================================
// ----------------------------------------
// Project Auth Schema
// ----------------------------------------
func (q *Queries) GetProjectAuthSchema(ctx context.Context, arg GetProjectAuthSchemaParams) (ProjectAuthSchema, error) {
	row := q.db.QueryRowContext(ctx, getProjectAuthSchema, arg.OrgName, arg.ProjectSlug)
	var i ProjectAuthSchema
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectAuthSchema = `-- name: UpsertProjectAuthSchema :exec
INSERT INTO project_auth_schemas (
    org_name, project_slug, variables
) VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE
    variables = VALUES(variables)
`

type UpsertProjectAuthSchemaParams struct {
	OrgName     string
	ProjectSlug string
	Variables   json.RawMessage
}

func (q *Queries) UpsertProjectAuthSchema(ctx context.Context, arg UpsertProjectAuthSchemaParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectAuthSchema, arg.OrgName, arg.ProjectSlug, arg.Variables)
	return err
}
