// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package dbgen

import (
	"context"
	"database/sql"
)

const assignBundleToRole = `-- name: AssignBundleToRole :exec
INSERT INTO end_user_role_bundles (
  id,
  role_id,
  bundle_id
)
VALUES (?, ?, ?)
`

type AssignBundleToRoleParams struct {
	ID       string
	RoleID   string
	BundleID string
}

func (q *Queries) AssignBundleToRole(ctx context.Context, arg AssignBundleToRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignBundleToRole, arg.ID, arg.RoleID, arg.BundleID)
	return err
}

const createEndUserRole = `-- name: CreateEndUserRole :exec
INSERT INTO end_user_roles (
  id,
  org_name,
  project_slug,
  name,
  description,
  is_implicit
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateEndUserRoleParams struct {
	ID          string
	OrgName     string
	ProjectSlug string
	Name        string
	Description sql.NullString
	IsImplicit  bool
}

func (q *Queries) CreateEndUserRole(ctx context.Context, arg CreateEndUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, createEndUserRole,
		arg.ID,
		arg.OrgName,
		arg.ProjectSlug,
		arg.Name,
		arg.Description,
		arg.IsImplicit,
	)
	return err
}

const deleteEndUserRole = `-- name: DeleteEndUserRole :execresult
DELETE FROM end_user_roles
WHERE id = ?
  AND org_name = ?
  AND is_implicit = FALSE
`

type DeleteEndUserRoleParams struct {
	ID      string
	OrgName string
}

// 注意：is_implicit=TRUE 的角色由业务层阻断，不走 SQL 层约束
func (q *Queries) DeleteEndUserRole(ctx context.Context, arg DeleteEndUserRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEndUserRole, arg.ID, arg.OrgName)
}

const getEndUserRoleByID = `-- name: GetEndUserRoleByID :one
SELECT id, org_name, project_slug, name, description, created_at, updated_at, is_implicit
FROM end_user_roles
WHERE id = ?
  AND org_name = ?
`

type GetEndUserRoleByIDParams struct {
	ID      string
	OrgName string
}

func (q *Queries) GetEndUserRoleByID(ctx context.Context, arg GetEndUserRoleByIDParams) (EndUserRole, error) {
	row := q.db.QueryRowContext(ctx, getEndUserRoleByID, arg.ID, arg.OrgName)
	var i EndUserRole
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.ProjectSlug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsImplicit,
	)
	return i, err
}

const listBundlesByRole = `-- name: ListBundlesByRole :many
SELECT b.id, b.org_name, b.project_slug, b.name, b.description, b.created_at, b.updated_at
FROM end_user_permission_bundles b
  JOIN end_user_role_bundles rb ON b.id = rb.bundle_id
WHERE rb.role_id = ?
`

func (q *Queries) ListBundlesByRole(ctx context.Context, roleID string) ([]EndUserPermissionBundle, error) {
	rows, err := q.db.QueryContext(ctx, listBundlesByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserPermissionBundle
	for rows.Next() {
		var i EndUserPermissionBundle
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndUserRolesByProject = `-- name: ListEndUserRolesByProject :many
SELECT id, org_name, project_slug, name, description, created_at, updated_at, is_implicit
FROM end_user_roles
WHERE org_name = ?
  AND project_slug = ?
ORDER BY is_implicit DESC, name
`

type ListEndUserRolesByProjectParams struct {
	OrgName     string
	ProjectSlug string
}

func (q *Queries) ListEndUserRolesByProject(ctx context.Context, arg ListEndUserRolesByProjectParams) ([]EndUserRole, error) {
	rows, err := q.db.QueryContext(ctx, listEndUserRolesByProject, arg.OrgName, arg.ProjectSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndUserRole
	for rows.Next() {
		var i EndUserRole
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ProjectSlug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsImplicit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeBundleFromRole = `-- name: RevokeBundleFromRole :execresult
DELETE FROM end_user_role_bundles
WHERE role_id = ?
  AND bundle_id = ?
`

type RevokeBundleFromRoleParams struct {
	RoleID   string
	BundleID string
}

func (q *Queries) RevokeBundleFromRole(ctx context.Context, arg RevokeBundleFromRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeBundleFromRole, arg.RoleID, arg.BundleID)
}

const updateEndUserRole = `-- name: UpdateEndUserRole :execresult
UPDATE end_user_roles
SET name = ?,
    description = ?,
    updated_at = NOW(3)
WHERE id = ?
  AND org_name = ?
  AND is_implicit = FALSE
`

type UpdateEndUserRoleParams struct {
	Name        string
	Description sql.NullString
	ID          string
	OrgName     string
}

// 注意：is_implicit=TRUE 的角色由业务层阻断，不走 SQL 层约束
func (q *Queries) UpdateEndUserRole(ctx context.Context, arg UpdateEndUserRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEndUserRole,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.OrgName,
	)
}
