// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: security_audit_logs.sql

package dbgen

import (
	"context"
	"encoding/json"
)

const insertSecurityAuditLog = `-- name: InsertSecurityAuditLog :exec
INSERT INTO security_audit_logs (id, user_id, event, detail, created_at)
VALUES (?, ?, ?, ?, NOW())
`

type InsertSecurityAuditLogParams struct {
	ID     string
	UserID string
	Event  string
	Detail *json.RawMessage
}

func (q *Queries) InsertSecurityAuditLog(ctx context.Context, arg InsertSecurityAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertSecurityAuditLog,
		arg.ID,
		arg.UserID,
		arg.Event,
		arg.Detail,
	)
	return err
}
