// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_auth.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const existsByPhoneInOrg = `-- name: ExistsByPhoneInOrg :one
SELECT EXISTS(SELECT 1 FROM users WHERE org_name = ? AND phone = ?) AS phone_exists
`

type ExistsByPhoneInOrgParams struct {
	OrgName string
	Phone   string
}

func (q *Queries) ExistsByPhoneInOrg(ctx context.Context, arg ExistsByPhoneInOrgParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByPhoneInOrg, arg.OrgName, arg.Phone)
	var phone_exists bool
	err := row.Scan(&phone_exists)
	return phone_exists, err
}

const existsByUserNameInOrg = `-- name: ExistsByUserNameInOrg :one
SELECT EXISTS(SELECT 1 FROM users WHERE org_name = ? AND name = ?) AS name_exists
`

type ExistsByUserNameInOrgParams struct {
	OrgName string
	Name    string
}

func (q *Queries) ExistsByUserNameInOrg(ctx context.Context, arg ExistsByUserNameInOrgParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByUserNameInOrg, arg.OrgName, arg.Name)
	var name_exists bool
	err := row.Scan(&name_exists)
	return name_exists, err
}

const getUserByNameInOrg = `-- name: GetUserByNameInOrg :one
SELECT id, phone, password_hash, name, external_id, org_name, is_admin, status, created_at, updated_at
FROM users
WHERE org_name = ? AND name = ? AND ` + "`" + `users` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0 LIMIT 1
`

type GetUserByNameInOrgParams struct {
	OrgName string
	Name    string
}

type GetUserByNameInOrgRow struct {
	ID           string
	Phone        string
	PasswordHash string
	Name         string
	ExternalID   sql.NullString
	OrgName      string
	IsAdmin      bool
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByNameInOrg(ctx context.Context, arg GetUserByNameInOrgParams) (GetUserByNameInOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByNameInOrg, arg.OrgName, arg.Name)
	var i GetUserByNameInOrgRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Name,
		&i.ExternalID,
		&i.OrgName,
		&i.IsAdmin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhoneInOrg = `-- name: GetUserByPhoneInOrg :one
SELECT id, phone, password_hash, name, external_id, org_name, is_admin, status, created_at, updated_at
FROM users
WHERE org_name = ? AND phone = ? AND ` + "`" + `users` + "`" + `.` + "`" + `deleted_at` + "`" + ` = 0 LIMIT 1
`

type GetUserByPhoneInOrgParams struct {
	OrgName string
	Phone   string
}

type GetUserByPhoneInOrgRow struct {
	ID           string
	Phone        string
	PasswordHash string
	Name         string
	ExternalID   sql.NullString
	OrgName      string
	IsAdmin      bool
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByPhoneInOrg(ctx context.Context, arg GetUserByPhoneInOrgParams) (GetUserByPhoneInOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhoneInOrg, arg.OrgName, arg.Phone)
	var i GetUserByPhoneInOrgRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Name,
		&i.ExternalID,
		&i.OrgName,
		&i.IsAdmin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
