// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_auth.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const existsByPhone = `-- name: ExistsByPhone :one
SELECT EXISTS(SELECT 1 FROM users WHERE phone = ?) AS phone_exists
`

func (q *Queries) ExistsByPhone(ctx context.Context, phone string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByPhone, phone)
	var phone_exists bool
	err := row.Scan(&phone_exists)
	return phone_exists, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, password_hash, name, external_id, created_at, updated_at
FROM users
WHERE phone = ? LIMIT 1
`

type GetUserByPhoneRow struct {
	ID           string
	Phone        string
	PasswordHash string
	Name         string
	ExternalID   sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Name,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
