// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_api_tokens.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, org_name, end_user_id, name, token_hash,
       expires_at, last_used_at, created_at, deleted_at, delete_token
FROM user_api_tokens
WHERE token_hash = ? AND deleted_at = 0
LIMIT 1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (UserApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i UserApiToken
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.EndUserID,
		&i.Name,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeleteToken,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :exec
INSERT INTO user_api_tokens (id, org_name, end_user_id, name, token_hash, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAPITokenParams struct {
	ID        string
	OrgName   string
	EndUserID string
	Name      string
	TokenHash string
	ExpiresAt sql.NullTime
	CreatedAt time.Time
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIToken,
		arg.ID,
		arg.OrgName,
		arg.EndUserID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, org_name, end_user_id, name, token_hash,
       expires_at, last_used_at, created_at, deleted_at, delete_token
FROM user_api_tokens
WHERE org_name = ? AND end_user_id = ? AND deleted_at = 0
ORDER BY created_at DESC
`

type ListAPITokensByUserParams struct {
	OrgName   string
	EndUserID string
}

func (q *Queries) ListAPITokensByUser(ctx context.Context, arg ListAPITokensByUserParams) ([]UserApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensByUser, arg.OrgName, arg.EndUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserApiToken
	for rows.Next() {
		var i UserApiToken
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.EndUserID,
			&i.Name,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DeleteToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAPIToken = `-- name: SoftDeleteAPIToken :execrows
UPDATE user_api_tokens
SET deleted_at = ?, delete_token = ?
WHERE id = ? AND org_name = ? AND end_user_id = ? AND deleted_at = 0
`

type SoftDeleteAPITokenParams struct {
	DeletedAt   uint64
	DeleteToken uint64
	ID          string
	OrgName     string
	EndUserID   string
}

func (q *Queries) SoftDeleteAPIToken(ctx context.Context, arg SoftDeleteAPITokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteAPIToken,
		arg.DeletedAt,
		arg.DeleteToken,
		arg.ID,
		arg.OrgName,
		arg.EndUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE user_api_tokens
SET last_used_at = ?
WHERE id = ?
`

type UpdateAPITokenLastUsedParams struct {
	LastUsedAt sql.NullTime
	ID         string
}

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, arg UpdateAPITokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAPITokenLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
