#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}/.."

cd "${PROJECT_ROOT}"

SCHEMA_DIR="${SCHEMA_DIR:-db/schema/mysql}"
OUTPUT_PATH="${1:-db/schema/merged/mysql_schema.sql}"

if [[ "${OUTPUT_PATH}" == "${SCHEMA_DIR}/"* ]] || [[ "${OUTPUT_PATH}" == "${SCHEMA_DIR}" ]]; then
    echo "❌ Output path must be outside ${SCHEMA_DIR} to avoid merging the generated file back into itself."
    exit 1
fi

if [[ ! -d "${SCHEMA_DIR}" ]]; then
    echo "❌ Schema directory not found: ${SCHEMA_DIR}"
    exit 1
fi

mapfile -t SQL_FILES < <(find "${SCHEMA_DIR}" -maxdepth 1 -type f -name '*.sql' | LC_ALL=C sort)

if [[ ${#SQL_FILES[@]} -eq 0 ]]; then
    echo "❌ No SQL files found under ${SCHEMA_DIR}"
    exit 1
fi

OUTPUT_DIR="$(dirname "${OUTPUT_PATH}")"
mkdir -p "${OUTPUT_DIR}"

TMP_OUTPUT="$(mktemp "${OUTPUT_DIR}/mysql_schema.sql.tmp.XXXXXX")"
cleanup() {
    rm -f "${TMP_OUTPUT}"
}
trap cleanup EXIT

{
    echo "-- Auto-generated by scripts/merge-schema-sql.sh"
    echo "-- Source directory: ${SCHEMA_DIR}"
    echo "-- Files are merged in lexical order to match MySQL init behavior."
    echo

    for sql_file in "${SQL_FILES[@]}"; do
        echo "-- ============================================================================"
        echo "-- BEGIN FILE: ${sql_file}"
        echo "-- ============================================================================"
        cat "${sql_file}"
        echo
        echo "-- END FILE: ${sql_file}"
        echo
    done
} > "${TMP_OUTPUT}"

mv "${TMP_OUTPUT}" "${OUTPUT_PATH}"
trap - EXIT

echo "✅ Merged ${#SQL_FILES[@]} SQL files into ${OUTPUT_PATH}"
