-- Auto-generated by scripts/merge-schema-sql.sh
-- Source directory: db/schema/mysql
-- Files are merged in lexical order to match MySQL init behavior.

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/01_project.sql
-- ============================================================================
-- projects 表 SQL 定义
-- 项目信息表（多租户架构，复合主键）

CREATE TABLE IF NOT EXISTS `projects` (
  -- 复合主键字段
  `org_name` VARCHAR(36) NOT NULL COMMENT '组织名称（复合主键之一）',
  `slug` VARCHAR(64) NOT NULL COMMENT '项目标识符（组织内唯一，复合主键之二）',

  -- 基本信息字段
  `title` VARCHAR(255) NOT NULL COMMENT '项目显示标题',
  `description` TEXT NULL COMMENT '项目描述信息',

  -- 状态字段
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '项目状态：active/archived（永不物理删除）',

  -- 集群关联字段
  `cluster_id` VARCHAR(36) NULL COMMENT '关联的集群ID（一对一关系）',

  -- 时间戳字段
  `created_at` DATETIME(3) NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NULL COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  -- 复合主键约束
  PRIMARY KEY (`org_name`, `slug`, `delete_token`) COMMENT '组织+项目标识符复合主键（含软删避让位）',

  -- 普通索引
  KEY `idx_org_name` (`org_name`) COMMENT '组织查询索引',
  KEY `idx_project_slug` (`slug`) COMMENT '项目标识符查询索引',
  KEY `idx_projects_org_slug` (`org_name`, `slug`) COMMENT '活跃项目查询索引',
  KEY `idx_project_status` (`status`) COMMENT '状态查询索引',
  KEY `idx_project_cluster` (`cluster_id`) COMMENT '集群查询索引',
  KEY `idx_project_live_org` (`org_name`, `deleted_at`) COMMENT '组织活跃项目查询索引'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目信息表（多租户，复合主键，只归档不删除）';


-- project_auth_schemas 表 SQL 定义
-- 每个项目的认证变量配置表（每个项目只有一份）

CREATE TABLE IF NOT EXISTS `project_auth_schemas` (
  `id`           BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `org_name`     VARCHAR(36) NOT NULL COMMENT '所属组织名称',
  `project_slug` VARCHAR(64) NOT NULL COMMENT '所属项目标识符',

  -- 扩展变量配置（JSON 数组）
  `variables`    JSON NOT NULL COMMENT '认证变量列表 [{name, source, type}]',

  -- 时间戳字段
  `created_at`   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at`   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',

  -- 唯一约束：每个项目只有一份 auth schema
  UNIQUE KEY `uk_auth_schemas_project` (`org_name`, `project_slug`),

  KEY `idx_auth_schemas_project` (`org_name`, `project_slug`) COMMENT '项目查询索引'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Project 认证变量配置';

-- END FILE: db/schema/mysql/01_project.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/02_database_cluster.sql
-- ============================================================================
-- database_clusters 表 SQL 定义
-- 数据库集群配置信息表

CREATE TABLE IF NOT EXISTS `database_clusters` (
  -- 主键字段
  `id` VARCHAR(36) NOT NULL COMMENT '集群唯一标识符',

  -- 项目关联字段（复合引用）
  `org_name` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '所属组织名称（来自projects表复合主键）',
  `project_slug` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '所属项目标识符（来自projects表复合主键）',

  -- 基本信息字段
  `title` VARCHAR(255) NOT NULL COMMENT '集群显示标题',
  `description` TEXT NULL COMMENT '集群描述信息',

  -- 连接信息字段
  `host` VARCHAR(255) NOT NULL COMMENT '数据库主机地址',
  `port` BIGINT NOT NULL DEFAULT 3306 COMMENT '数据库端口号',
  `username` VARCHAR(255) NOT NULL COMMENT '数据库用户名',
  `password` TEXT NOT NULL COMMENT '数据库密码',
  `connection_timeout` INT NOT NULL DEFAULT 5 COMMENT '连接超时(秒,5-15)',
  `charset` VARCHAR(50) NULL DEFAULT 'utf8mb4' COMMENT '数据库字符集',

  -- 连接池配置字段
  `max_open_conns` BIGINT NULL DEFAULT 100 COMMENT '最大打开连接数',
  `max_idle_conns` BIGINT NULL DEFAULT 10 COMMENT '最大空闲连接数',
  `conn_max_lifetime` BIGINT NULL DEFAULT 3600 COMMENT '连接最大生命周期（秒）',

  -- 状态和版本字段
  `status` VARCHAR(20) NULL DEFAULT 'active' COMMENT '集群状态:active/inactive',
  `version` BIGINT NULL DEFAULT 1 COMMENT '数据版本号',

  -- 时间戳字段
  `created_at` DATETIME(3) NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NULL COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  -- 主键约束
  PRIMARY KEY (`id`),

  -- 不使用外键约束（避免复杂性，Project永不删除只归档）

  -- 唯一索引
  UNIQUE KEY `idx_cluster_project_unique` (`org_name`, `project_slug`, `delete_token`) COMMENT '一对一约束：一个项目只能有一个活跃集群',

  -- 普通索引
  KEY `idx_status` (`status`) COMMENT '状态查询索引',
  KEY `idx_cluster_project` (`org_name`, `project_slug`) COMMENT '项目查询索引',
  KEY `idx_cluster_live_project` (`org_name`, `project_slug`, `deleted_at`) COMMENT '项目活跃集群查询索引'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据库集群配置信息表';

-- END FILE: db/schema/mysql/02_database_cluster.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/03_model_domain.sql
-- ============================================================================
-- models 表 SQL 定义
-- 模型定义主表

CREATE TABLE IF NOT EXISTS `models` (
  -- 主键字段
  `id` VARCHAR(36) NOT NULL COMMENT '模型唯一标识符',

  -- 项目关联字段（复合引用）
  `org_name` VARCHAR(36) NOT NULL COMMENT '所属组织名称（来自projects表复合主键）',
  `project_slug` VARCHAR(64) NOT NULL COMMENT '所属项目标识符（来自projects表复合主键）',

  -- 基本信息字段
  `name` VARCHAR(64) NOT NULL COMMENT '模型名称（唯一标识）',
  `title` VARCHAR(255) NOT NULL COMMENT '模型显示标题',
  `description` TEXT NULL COMMENT '模型描述信息',

  -- 存储配置字段
  `storage_type` VARCHAR(100) NOT NULL COMMENT '存储类型',
  `database_name` VARCHAR(64) NOT NULL COMMENT '数据库名称',

  -- 运行时配置字段
  `display_field` VARCHAR(64) NULL COMMENT '用于 runtime _displayName 解析的字段名（必须是模型中存在且可字符串化的字段）',
  `insertion_order_field` VARCHAR(64) NULL COMMENT '用于 listPage cursor 分页的插入序字段名（单调递增字段，如 created_at）',

  -- 版本和状态字段
  `version` BIGINT NULL DEFAULT 1 COMMENT '数据版本号',
  `status` VARCHAR(50) NULL DEFAULT 'draft' COMMENT '模型状态：draft/published/archived',
  `group_id` VARCHAR(36) NULL COMMENT '所属分组ID，NULL表示未分组（ungrouped）',
  `deployment_status` VARCHAR(50) NULL DEFAULT 'pending' COMMENT '部署状态：pending/success/failed',

  -- 同步信息字段
  `last_sync_at` DATETIME(3) NULL COMMENT '最后同步时间',
  `sync_error` TEXT NULL COMMENT '同步错误信息',

  -- 创建来源字段
  `created_via` ENUM('NEW', 'IMPORTED') NOT NULL DEFAULT 'NEW' COMMENT '模型创建来源：NEW=新建，IMPORTED=导入',

  -- 只读控制字段（与 createdVia 解耦，由数据库 mode 决定）
  `is_read_only` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否只读：1=只读（禁止结构修改），0=可编辑',

  -- 时间戳字段
  `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  -- 主键约束
  PRIMARY KEY (`id`),

  -- 不使用外键约束（避免复杂性，Project永不删除只归档）

  -- 唯一索引
  UNIQUE KEY `idx_models_name` (`org_name`, `project_slug`, `database_name`, `name`, `delete_token`) COMMENT '组织+项目内模型名称唯一索引',

  -- 普通索引
  KEY `idx_models_project` (`org_name`, `project_slug`) COMMENT '项目查询索引',
  KEY `idx_models_live_project` (`org_name`, `project_slug`, `deleted_at`) COMMENT '项目活跃模型查询索引',
  KEY `idx_models_is_read_only` (`is_read_only`) COMMENT '只读模型查询索引',
  KEY `idx_models_created_via` (`created_via`) COMMENT '模型创建来源查询索引'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型定义主表';


-- model_groups 表 SQL 定义
-- 模型分组定义表

CREATE TABLE IF NOT EXISTS `model_groups` (
  -- 主键字段
  `id` VARCHAR(36) NOT NULL COMMENT '分组唯一标识符',

  -- 项目关联字段（复合引用）
  `org_name` VARCHAR(36) NOT NULL COMMENT '所属组织名称（来自projects表复合主键）',
  `project_slug` VARCHAR(64) NOT NULL COMMENT '所属项目标识符（来自projects表复合主键）',

  -- 基本信息字段
  `name` VARCHAR(64) NOT NULL COMMENT '分组名称，仅小写字母、数字和下划线，字母开头',

  -- 排序字段
  `display_order` VARCHAR(255) NOT NULL COMMENT '字典序排序键，用于拖拽排序（lexicographic fractional index）',

  -- 时间戳字段
  `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  -- 主键约束
  PRIMARY KEY (`id`),

  -- 不使用外键约束（避免复杂性，Project永不删除只归档）

  -- 唯一索引
  UNIQUE KEY `idx_model_groups_name` (`org_name`, `project_slug`, `name`, `delete_token`) COMMENT '组织+项目内分组名称唯一索引',

  -- 普通索引
  KEY `idx_model_groups_project_order` (`org_name`, `project_slug`, `display_order`) COMMENT '项目分组排序查询索引',
  KEY `idx_model_groups_live_project` (`org_name`, `project_slug`, `deleted_at`) COMMENT '项目活跃分组查询索引'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型分组定义表';





-- logical_foreign_keys 表 SQL 定义
-- 逻辑外键定义表（成对存储：normal + reverse）

CREATE TABLE IF NOT EXISTS `logical_foreign_keys` (
  -- 主键字段
  `id` VARCHAR(36) NOT NULL COMMENT '逻辑外键唯一标识符',

  -- 配对字段（normal 和 reverse 共享同一 pair_id）
  `pair_id` VARCHAR(36) NOT NULL COMMENT '外键对ID，normal 和 reverse 行共享',

  -- 租户隔离字段
  `org_name` VARCHAR(36) NOT NULL COMMENT '所属组织名称',

  -- 方向枚举
  `direction` ENUM('normal', 'reverse') NOT NULL COMMENT '外键方向：normal（正向）/ reverse（反向）',

  -- 模型关联字段
  `model_id` VARCHAR(36) NOT NULL COMMENT '所属模型ID',
  `model_name` VARCHAR(255) NOT NULL COMMENT '所属模型名称（冗余存储，model_name 不变）',
  `ref_model_id` VARCHAR(36) NULL COMMENT '引用模型ID（外部表场景可为空）',
  `ref_model_name` VARCHAR(255) NOT NULL COMMENT '引用模型名称（冗余存储，model_name 不变）',
  `ref_database_name` VARCHAR(64) NULL COMMENT '引用数据库名（外部表场景）',
  `ref_table_name` VARCHAR(64) NULL COMMENT '引用表名（外部表场景）',

  -- 字段映射配置
  `source_fields` JSON NOT NULL COMMENT '源字段列表（JSON数组）',
  `target_fields` JSON NOT NULL COMMENT '目标字段列表（JSON数组）',
  `is_deletable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否允许删除（系统FK为0）',

  -- 时间戳字段
  `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  -- 主键约束
  PRIMARY KEY (`id`),

  -- 索引
  KEY `idx_logical_fk_pair_live` (`pair_id`, `org_name`, `deleted_at`) COMMENT '外键对活跃记录查询索引',
  KEY `idx_logical_fk_model_live` (`model_id`, `org_name`, `deleted_at`) COMMENT '模型活跃逻辑外键查询索引',
  KEY `idx_logical_fk_ref_model_live` (`ref_model_id`, `org_name`, `deleted_at`) COMMENT '引用模型活跃逻辑外键查询索引',

  -- 外键约束
  CONSTRAINT `fk_logical_fk_model` FOREIGN KEY (`model_id`) REFERENCES `models` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_logical_fk_ref_model` FOREIGN KEY (`ref_model_id`) REFERENCES `models` (`id`) ON DELETE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='逻辑外键定义表';


-- model_enums 表 SQL 定义
-- 枚举定义表

CREATE TABLE IF NOT EXISTS `model_enums` (
  -- 主键字段
  `id` VARCHAR(36) NOT NULL COMMENT '枚举唯一标识符',

  -- 项目关联字段（复合引用）
  `org_name` VARCHAR(36) NOT NULL COMMENT '所属组织名称（来自projects表复合主键）',
  `project_slug` VARCHAR(64) NOT NULL COMMENT '所属项目标识符（来自projects表复合主键）',

  -- 基本信息字段
  `name` VARCHAR(64) NOT NULL COMMENT '枚举名称（唯一标识）',
  `display_name` VARCHAR(255) NOT NULL COMMENT '枚举显示名称',
  `description` TEXT NULL COMMENT '枚举描述信息',

  -- 枚举选项配置
  `options` JSON NOT NULL COMMENT '枚举选项配置（JSON数组格式）',
  `is_multi_select` TINYINT(1) NULL DEFAULT 0 COMMENT '是否支持多选',

  -- 时间戳字段
  `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  -- 主键约束
  PRIMARY KEY (`id`),

  -- 不使用外键约束（避免复杂性，Project永不删除只归档）

  -- 唯一索引
  UNIQUE KEY `idx_model_enums_name` (`org_name`, `project_slug`, `name`, `delete_token`) COMMENT '组织+项目内枚举名称唯一索引',

  -- 普通索引
  KEY `idx_model_enums_project` (`org_name`, `project_slug`) COMMENT '项目查询索引',
  KEY `idx_model_enums_live_project` (`org_name`, `project_slug`, `deleted_at`) COMMENT '项目活跃枚举查询索引'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型枚举定义表';


-- field_definitions 表 SQL 定义
-- 模型字段定义表

CREATE TABLE IF NOT EXISTS `field_definitions` (
  -- 复合主键字段
  `model_id` VARCHAR(36) NOT NULL COMMENT '所属模型ID',
  `name` VARCHAR(64) NOT NULL COMMENT '字段名称',
  
  -- 多租户隔离字段（与models表保持一致）
  `org_name` VARCHAR(36) NOT NULL COMMENT '所属组织名称（多租户隔离）',
  `project_slug` VARCHAR(64) NOT NULL COMMENT '项目标识符（多租户隔离）',
  
  -- 模型和集群信息字段
  `model_name` VARCHAR(64) NOT NULL COMMENT '模型名称',
  `database_name` VARCHAR(64) NOT NULL COMMENT '数据库名称',
  
  -- 关系关联字段
  `enum_name` VARCHAR(64) NULL COMMENT '关联的枚举名称（format=ENUM）',

  -- 逻辑外键关联字段
  `belongs_to_fk_id` VARCHAR(36) NULL COMMENT '所属逻辑外键ID（FK列字段使用）',
  `relate_fk_id` VARCHAR(36) NULL COMMENT '关联的逻辑外键ID（RELATION格式字段使用）',

  -- 字段基本信息
  `title` VARCHAR(255) NOT NULL COMMENT '字段显示标题',
  `description` TEXT NULL COMMENT '字段描述信息',
  `format` VARCHAR(50) NOT NULL COMMENT '字段格式类型',
  
  -- 字段属性配置
  `non_null` TINYINT(1) NULL DEFAULT 0 COMMENT '是否可为null',
  `required` TINYINT(1) NULL DEFAULT 0 COMMENT '是否创建时必填',
  `is_unique` TINYINT(1) NULL DEFAULT 0 COMMENT '是否唯一',
  `is_primary` TINYINT(1) NULL DEFAULT 0 COMMENT '是否主键',
  `is_deprecated` TINYINT(1) NULL DEFAULT 0 COMMENT '是否已废弃',
  
  -- 存储提示（对应 DB 列名，非空表示该字段由 DB 同步而来）
  `storage_hint` VARCHAR(128) NULL COMMENT '存储优化提示，通常为 DB 列名；非空表示该字段映射到实际 DB 列，参与 syncModelsFromDB 的 full sync',

  -- 状态和验证配置
  `status` VARCHAR(20) NOT NULL DEFAULT 'init' COMMENT '字段状态：init/active/inactive',
  `validation` JSON NULL COMMENT '字段验证规则配置',
  
  -- 显示和元数据配置
  `display_order` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '字典序排序键，用于拖拽排序（lexicographic fractional index）',
  `metadata` JSON NULL COMMENT '字段元数据配置',

  -- 时间戳字段
  `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',
  
  -- 复合主键约束
  PRIMARY KEY (`model_id`, `name`, `delete_token`),
  
  -- 索引：多租户查询优化（与其他表保持一致）
  INDEX `idx_field_definitions_project` (`org_name`, `project_slug`) COMMENT '项目查询索引',
  INDEX `idx_field_definitions_model` (`org_name`, `project_slug`, `model_name`) COMMENT '模型查询索引',
  INDEX `idx_field_definitions_live_project` (`org_name`, `project_slug`, `deleted_at`) COMMENT '项目活跃字段查询索引',
  
  -- 外键约束
  CONSTRAINT `fk_field_definitions_model` FOREIGN KEY (`model_id`) REFERENCES `models` (`id`) ON DELETE CASCADE
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型字段定义表';


-- model_field_enum_associations 表 SQL 定义
-- 模型字段与枚举关联表（保留）

CREATE TABLE IF NOT EXISTS `model_field_enum_associations` (
  -- 复合主键字段
  `model_id` VARCHAR(36) NOT NULL COMMENT '模型ID',
  `field_name` VARCHAR(64) NOT NULL COMMENT '字段名称',

  -- 项目关联字段（复合引用）
  `org_name` VARCHAR(36) NOT NULL COMMENT '所属组织名称',
  `project_slug` VARCHAR(64) NOT NULL COMMENT '所属项目标识符',

  -- 关联信息字段
  `enum_name` VARCHAR(64) NOT NULL COMMENT '关联的枚举名称',

  -- 数据库信息
  `database_name` VARCHAR(64) NOT NULL COMMENT '数据库名称',

  -- 时间戳字段
  `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',

  -- 复合主键约束
  PRIMARY KEY (`model_id`, `field_name`),

  -- 外键约束（仅对models表，不对projects表）
  CONSTRAINT `fk_field_enum_assoc_model` FOREIGN KEY (`model_id`) REFERENCES `models` (`id`) ON DELETE CASCADE,

  -- 查询优化索引
  KEY `idx_field_enum_assoc_enum_name` (`org_name`, `project_slug`, `enum_name`) COMMENT '组织+项目内枚举名称查询索引',
  KEY `idx_field_enum_assoc_cluster_db` (`database_name`) COMMENT '数据库查询索引',
  KEY `idx_field_enum_assoc_project` (`org_name`, `project_slug`) COMMENT '项目查询索引'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型字段与枚举关联表';

-- END FILE: db/schema/mysql/03_model_domain.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/04_auth.sql
-- ============================================================================
-- ============================================================================
-- Authentication Configuration Schema
-- ============================================================================
-- This schema defines project-level authentication configuration for ModelCraft.
-- Each project can configure its own authentication provider (AuthProvider, Keycloak, OIDC).

-- Create project_auth_configs table
CREATE TABLE IF NOT EXISTS project_auth_configs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key',

    -- 项目关联字段（复合引用）
    org_name VARCHAR(36) NOT NULL COMMENT '所属组织名称（来自projects表复合主键）',
    project_slug VARCHAR(64) NOT NULL COMMENT '所属项目标识符（来自projects表复合主键）',

    provider VARCHAR(32) NOT NULL COMMENT 'Authentication provider type: auth_provider, keycloak, oidc',
    enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'Whether authentication is enabled for this project',
    config JSON NOT NULL COMMENT 'Provider-specific configuration (endpoint, client_id, certificate, etc.)',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',

    -- 不使用外键约束（避免复杂性，Project永不删除只归档）

    -- 唯一约束：每个项目只能有一个认证配置
    UNIQUE KEY idx_project_auth_unique (org_name, project_slug),

    -- Check constraint: provider must be one of supported values
    CONSTRAINT chk_provider_type
        CHECK (provider IN ('auth_provider', 'keycloak', 'oidc'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Project-level authentication configuration';

-- Create index on project for fast lookups
CREATE INDEX idx_project_auth_configs_project ON project_auth_configs (org_name, project_slug);

-- Create index on provider for analytics/reporting
CREATE INDEX idx_project_auth_configs_provider ON project_auth_configs (provider);

-- ============================================================================
-- Example Configuration JSON Structure
-- ============================================================================
-- AuthProvider Configuration:
-- {
--   "endpoint": "https://auth_provider.example.com",
--   "client_id": "abc123",
--   "client_secret": "secret",
--   "organization": "tenant1",
--   "application": "modelcraft",
--   "certificate": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
-- }
--
-- Keycloak Configuration (future):
-- {
--   "realm": "myrealm",
--   "auth_server_url": "https://keycloak.example.com",
--   "jwks_uri": "https://keycloak.example.com/realms/myrealm/protocol/openid-connect/certs",
--   "client_id": "modelcraft"
-- }
--
-- Generic OIDC Configuration (future):
-- {
--   "issuer": "https://sso.company.com",
--   "jwks_uri": "https://sso.company.com/.well-known/jwks.json",
--   "client_id": "modelcraft"
-- }

-- END FILE: db/schema/mysql/04_auth.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/05_organizations.sql
-- ============================================================================
-- =============================================================================
-- 组织管理 (Organization Management)
-- 多租户组织单元，每个组织是项目、集群、模型等资源的逻辑容器
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 组织表 (Organizations)
-- 组织名称全局唯一，通常来自 AuthProvider
-- owner_id 在用户创建后会填充，初始创建时可能为空
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `organizations` (
  `name` VARCHAR(36) NOT NULL PRIMARY KEY COMMENT '唯一标识符，随机slug',
  `display_name` VARCHAR(255) COMMENT '用于 UI 显示的名称',
  `owner_id` VARCHAR(36) COMMENT '组织创建者/所有者（引用 users.id）',
  `phone` VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'Org 注册手机号，全局唯一',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active、suspended、deleted',

  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  UNIQUE INDEX `uk_org_phone` (`phone`, `delete_token`) COMMENT 'Org 手机号全局唯一',
  INDEX `idx_org_owner` (`owner_id`) COMMENT '按所有者查找组织',
  INDEX `idx_org_status` (`status`) COMMENT '按状态筛选',
  INDEX `idx_org_live_status` (`deleted_at`, `status`) COMMENT '按活跃状态筛选组织'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='组织表（多租户容器）';

-- END FILE: db/schema/mysql/05_organizations.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/06_users.sql
-- ============================================================================
-- =============================================================================
-- 用户管理 (User Management)
-- 包含：用户表（含 is_admin / status，已合并原 user_orgs 表）
-- 混合认证：支持手机号+密码本地注册，同时兼容外部认证提供者（AuthProvider）
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. 用户表 (Users)
-- 混合认证设计：支持手机号+密码本地注册登录，同时兼容外部认证提供者（AuthProvider）
-- external_id 可为 NULL（本地注册用户无外部 ID）
-- is_admin / status 原存于 user_orgs 表，因每用户仅属一个 Org 故合并至此
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY COMMENT '内部 UUID',
  `external_id` VARCHAR(255) NULL COMMENT '外部认证提供者用户 ID（来自 JWT.sub，AuthProvider 用户有值，本地注册用户为 NULL）',
  `name` VARCHAR(255) NOT NULL COMMENT '用户名（userName）',
  `phone` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户手机号',
  `password_hash` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'bcrypt 密码哈希（本地注册用户有值，AuthProvider 用户为空）',
  `display_name` VARCHAR(255) COMMENT '用于 UI 显示的名称',
  `org_name` VARCHAR(36) NOT NULL DEFAULT '' COMMENT '所属 Org，创建时绑定（引用 organizations.name）',
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否为管理员',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active | suspended',

  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  UNIQUE INDEX `uk_org_user_phone` (`org_name`, `phone`, `delete_token`) COMMENT 'Org 内手机号唯一',
  UNIQUE INDEX `uk_org_user_name` (`org_name`, `name`, `delete_token`) COMMENT 'Org 内用户名唯一',
  INDEX `idx_external_id` (`external_id`) COMMENT '按外部 ID 快速查找',
  INDEX `idx_users_live_name` (`deleted_at`, `org_name`, `name`) COMMENT '活跃用户查询索引',
  CONSTRAINT `fk_users_org` FOREIGN KEY (`org_name`) REFERENCES `organizations`(`name`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- -----------------------------------------------------------------------------
-- 2. 用户资料表 (Profile)
-- user 与 profile 为 1:1 关系：profile.user_id UNIQUE + FK(users.id)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `profile` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY COMMENT 'profile UUID',
  `user_id` VARCHAR(36) NOT NULL COMMENT '用户 ID（引用 users.id）',
  `nickname` VARCHAR(32) NOT NULL COMMENT '昵称',
  `avatar_url` VARCHAR(512) NULL COMMENT '头像 URL（当前可为空，上传能力后续实现）',
  `bio` VARCHAR(256) NULL COMMENT '个人简介',

  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  CONSTRAINT `fk_profile_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  UNIQUE KEY `uk_profile_user_id` (`user_id`, `delete_token`) COMMENT '保证一个用户仅有一个活跃 profile',
  INDEX `idx_profile_live_user` (`deleted_at`, `user_id`) COMMENT '活跃 profile 查询索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户资料表';

-- -----------------------------------------------------------------------------
-- 3. organizations.owner_id 与 users.id 之间不设外键约束
-- 原因：注册流程中 organizations 先于 users 创建（同一事务内），
-- 若设 FK 会导致循环依赖（organizations.owner_id → users.id，
-- users.org_name → organizations.name）。
-- 引用完整性由应用层保证。

-- END FILE: db/schema/mysql/06_users.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/07_roles_permissions.sql
-- ============================================================================
-- =============================================================================
-- Casbin 权限系统 (Casbin RBAC Permission System)
-- 包含：角色表、用户角色绑定表、角色权限表
--
-- 设计要点：
-- 1. 系统角色 (owner/admin/editor/viewer) 权限硬编码在 Go 代码中
-- 2. 自定义角色权限存储在 role_permissions 表中
-- 3. 支持多租户：同一用户在不同 org 可以有不同角色
-- 4. 使用 org_name='__SYSTEM__' 标识系统角色（而非 NULL，避免唯一约束问题）
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Step 2: 创建角色表 (Roles)
--
-- 设计变更：
-- - org_name 使用 '__SYSTEM__' 标识系统角色（全局），其他值为租户自定义角色
-- - 移除 permissions JSON 字段（系统角色权限硬编码，自定义角色权限在 role_permissions 表）
-- - 主键改为 INT AUTO_INCREMENT（更适合 Casbin enforcer 和外键关联）
-- - is_system=TRUE 的角色不可修改删除
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '角色 ID（主键）',
  `name` VARCHAR(64) NOT NULL COMMENT '角色名称（如 owner, admin, editor, viewer, 或自定义）',
  `description` TEXT COMMENT '角色描述',
  `is_system` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '系统角色标识（true = 不可修改删除）',
  `org_name` VARCHAR(36) NOT NULL DEFAULT '__SYSTEM__' COMMENT '所属组织名称（__SYSTEM__ = 系统角色，其他 = 租户自定义角色）',

  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  -- 唯一约束：租户内角色名称唯一（系统角色使用 __SYSTEM__ 标识，全局唯一）
  UNIQUE KEY `uk_role_name_org` (`name`, `org_name`, `delete_token`) COMMENT '租户内角色名称唯一',

  -- 索引
  INDEX `idx_org_name` (`org_name`) COMMENT '按组织查询角色',
  INDEX `idx_is_system` (`is_system`) COMMENT '筛选系统角色',
  INDEX `idx_roles_live_org` (`org_name`, `deleted_at`) COMMENT '组织活跃角色查询索引'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色表（支持系统角色和租户自定义角色）';

-- -----------------------------------------------------------------------------
-- Step 3: 系统角色初始化
--
-- 注意：
-- - 系统角色的初始化由应用代码负责（启动时自动创建）
-- - 系统角色的权限在 Go 代码中硬编码（internal/infrastructure/auth/system_roles.go）
-- - org_name = '__SYSTEM__' 表示全局系统角色
-- - is_system = TRUE 防止被删除或修改
-- -----------------------------------------------------------------------------

-- 系统角色列表（由应用代码创建）:
-- - owner: 拥有者 - 完全控制所有资源和团队管理
-- - admin: 管理员 - 管理所有资源和团队成员（不含用户管理）
-- - editor: 编辑者 - 创建和编辑资源（不能删除）
-- - viewer: 查看者 - 只读访问资源

-- -----------------------------------------------------------------------------
-- Step 4: 创建用户角色绑定表 (User Roles)
--
-- 设计变更：
-- - 简化为 user_id, role_id, org_name 三字段核心模型
-- - 移除 status, invited_by 等邀请流程字段（邀请流程在 user_organizations 表处理）
-- - role_id 外键级联删除：删除角色时自动删除所有用户角色绑定
-- - 支持同一用户在不同 org 有不同角色
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键 ID',
  `user_id` VARCHAR(36) NOT NULL COMMENT '用户 ID（引用 users.id）',
  `role_id` BIGINT NOT NULL COMMENT '角色 ID（引用 roles.id）',
  `org_name` VARCHAR(36) NOT NULL COMMENT '组织名称（多租户隔离）',

  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',

  -- 外键约束
  CONSTRAINT `fk_user_roles_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_roles_role` FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE CASCADE,

  -- 唯一约束：同一用户在同一组织不能重复绑定同一角色
  UNIQUE KEY `uk_user_role_org` (`user_id`, `role_id`, `org_name`) COMMENT '防止重复角色绑定',

  -- 索引
  INDEX `idx_user_org` (`user_id`, `org_name`) COMMENT '查询用户在某组织的所有角色',
  INDEX `idx_role_org` (`role_id`, `org_name`) COMMENT '查询某角色在某组织的所有用户',
  INDEX `idx_org_name` (`org_name`) COMMENT '按组织查询所有用户角色'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户角色绑定表（支持多租户）';

-- -----------------------------------------------------------------------------
-- Step 5: 创建角色权限表 (Role Permissions)
--
-- 说明：
-- - 仅存储租户自定义角色的权限（系统角色权限硬编码在 Go 代码中）
-- - obj: 资源名称（如 project, model, cluster, enum）
-- - act: 操作名称（如 create, read, update, delete, 或 * 表示所有）
-- - org_name: 冗余字段，用于优化查询（虽然可以通过 role_id JOIN 获取，但冗余提升性能）
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `role_permissions` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键 ID',
  `role_id` BIGINT NOT NULL COMMENT '角色 ID（引用 roles.id）',
  `org_name` VARCHAR(36) NOT NULL COMMENT '组织名称（冗余字段，优化查询）',
  `obj` VARCHAR(64) NOT NULL COMMENT '资源对象（如 project, model, cluster, enum）',
  `act` VARCHAR(64) NOT NULL COMMENT '操作动作（如 create, read, update, delete, *）',

  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',

  -- 外键约束
  CONSTRAINT `fk_role_perms_role` FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE CASCADE,

  -- 唯一约束：同一角色不能有重复的权限规则
  UNIQUE KEY `uk_role_obj_act` (`role_id`, `obj`, `act`) COMMENT '防止重复权限',

  -- 索引
  INDEX `idx_role_org` (`role_id`, `org_name`) COMMENT '查询某角色在某组织的权限（优化主查询路径）',
  INDEX `idx_org_name` (`org_name`) COMMENT '按组织查询权限'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色权限表（仅存储自定义角色权限）';

-- =============================================================================
-- 设计完成！
--
-- 下一步：
-- 1. 在 Go 代码中实现 Casbin enforcer 和系统角色权限硬编码
-- 2. 实现 GraphQL @hasPermission 指令
-- 3. 编写测试用例验证权限系统
--
-- 关键设计决策：
-- - 使用 '__SYSTEM__' 而非 NULL 避免 MySQL 唯一约束的 NULL 处理问题
-- - 系统角色权限硬编码提升性能且保证不可变性
-- - role_permissions 中冗余 org_name 优化查询性能
-- - 邀请流程字段保留在 user_organizations 表，角色绑定表保持简洁
-- =============================================================================

-- END FILE: db/schema/mysql/07_roles_permissions.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/08_refresh_tokens.sql
-- ============================================================================
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          VARCHAR(36)  NOT NULL,
    user_id     VARCHAR(36)  NOT NULL,
    token_hash  VARCHAR(64)  NOT NULL COMMENT 'SHA256 hash，不存明文',
    expires_at  DATETIME     NOT NULL,
    created_at  DATETIME     NOT NULL,
    revoked_at  DATETIME     NULL     COMMENT 'NULL = 有效',
    PRIMARY KEY (id),
    INDEX idx_token_hash (token_hash),
    INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- END FILE: db/schema/mysql/08_refresh_tokens.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/10_security_audit_logs.sql
-- ============================================================================
CREATE TABLE IF NOT EXISTS security_audit_logs (
    id         VARCHAR(36) NOT NULL,
    user_id    VARCHAR(36) NOT NULL,
    event      VARCHAR(50) NOT NULL COMMENT '如 REUSE_DETECTED',
    detail     JSON        NULL     COMMENT 'token_id, ip 等上下文',
    created_at DATETIME    NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_user_id_created (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- END FILE: db/schema/mysql/10_security_audit_logs.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/12_rls_policy_v2.sql
-- ============================================================================
-- ============================================
-- Migration: RLS Policy V2 — 多策略存储（role + action + 表达式）
-- Description: 替换旧单策略表，支持每个 model 多条 policy，按 action+role 匹配
-- ============================================

-- ----------------------------------------
-- 2. 创建新 model_rls_policies 表（多策略存储）
-- ----------------------------------------
CREATE TABLE model_rls_policies (
    id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    org_name        VARCHAR(36) NOT NULL COMMENT '组织名',
    project_slug    VARCHAR(64) NOT NULL COMMENT '项目标识',
    model_id        VARCHAR(36) NOT NULL COMMENT '模型 ID',

    -- 策略元信息
    policy_name     VARCHAR(255) NOT NULL COMMENT '策略名称（model 内唯一）',
    action          ENUM('read', 'create', 'update', 'delete') NOT NULL COMMENT '操作类型',
    role            VARCHAR(255) NOT NULL DEFAULT '*' COMMENT '匹配角色（*=通配，匹配所有 EndUser）',

    -- 表达式（CEL / legacy JSON 文本）
    using_expr      TEXT NULL COMMENT 'USING 表达式（read/update/delete）',
    with_check_expr TEXT NULL COMMENT 'WITH CHECK 表达式（create/update）',

    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    -- 唯一约束：同一 model 下 role + action 唯一
    UNIQUE KEY uk_policy_role_action (org_name, project_slug, model_id, role, action),

    -- 查询索引：按 policy_name 查找
    INDEX idx_policy_name (org_name, project_slug, model_id, policy_name),

    -- 级联外键：model 删除时自动清除其所有策略
    CONSTRAINT fk_rls_policies_model FOREIGN KEY (model_id) REFERENCES models (id) ON DELETE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='RLS 策略表（多策略存储）';

-- END FILE: db/schema/mysql/12_rls_policy_v2.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/16_model_database.sql
-- ============================================================================
-- =============================================================================
-- Model Database Registry (2026)
-- 说明：
-- - 新增 model_database 表，记录 Project 已接管的 MySQL database
-- - mode: self_hosted（可读写，支持新建/导入模型）/ managed（只读，仅同步模型）
-- - 通过 (project_slug, name, delete_token) 联合唯一索引支持软删除后重复接管
-- =============================================================================

CREATE TABLE IF NOT EXISTS `model_database` (
  `id`           VARCHAR(36)   NOT NULL COMMENT '数据库唯一标识符 (UUID)',
  `org_name`     VARCHAR(64)   NOT NULL COMMENT '所属组织名称',
  `project_slug` VARCHAR(64)   NOT NULL COMMENT '所属项目标识符',
  `cluster_id`   VARCHAR(36)   NOT NULL COMMENT '所属数据库集群 ID',
  `name`         VARCHAR(64)   NOT NULL COMMENT 'MySQL database 原始名，来自 SHOW DATABASES，注册后不可修改',
  `title`        VARCHAR(128)  NOT NULL COMMENT '用户设置的友好名称，默认等于 name',
  `description`  TEXT          NULL             COMMENT '可选描述',
  `mode`                ENUM('self_hosted','managed') NOT NULL COMMENT 'self_hosted=可读写; managed=只读',
  `latest_sync_job_id`  VARCHAR(36)      NULL     COMMENT '最近一次 ModelSyncJob ID',
  `deleted_at`   BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',
  `created_at`   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_project_database` (`project_slug`, `name`, `delete_token`),
  KEY `idx_model_database_cluster` (`cluster_id`),
  KEY `idx_model_database_project` (`org_name`, `project_slug`),
  KEY `idx_model_database_live_project` (`org_name`, `project_slug`, `deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Project 已接管的 MySQL database 注册表';

CREATE TABLE IF NOT EXISTS `model_database_sync_job` (
  `id`                VARCHAR(36)      NOT NULL COMMENT '同步任务唯一标识符 (UUID)',
  `org_name`          VARCHAR(64)      NOT NULL COMMENT '所属组织名称',
  `project_slug`      VARCHAR(64)      NOT NULL COMMENT '所属项目标识符',
  `database_id`       VARCHAR(36)      NOT NULL COMMENT '关联的已接管数据库 ID',
  `status`            ENUM('pending','running','succeeded','partial_success','failed') NOT NULL COMMENT '任务状态',
  `total_tables`      INT              NOT NULL DEFAULT 0 COMMENT '扫描到的表总数',
  `processed_tables`  INT              NOT NULL DEFAULT 0 COMMENT '已处理表数',
  `created_models`    INT              NOT NULL DEFAULT 0 COMMENT '新导入模型数',
  `synced_models`     INT              NOT NULL DEFAULT 0 COMMENT '已同步 schema 的模型数',
  `failed_count`      INT              NOT NULL DEFAULT 0 COMMENT '失败表数',
  `failed_tables`     JSON             NOT NULL COMMENT '失败表详情 [{tableName,message}]',
  `deleted_at`        BIGINT UNSIGNED  NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token`      BIGINT UNSIGNED  NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',
  `started_at`        DATETIME(3)      NULL COMMENT '任务开始时间',
  `finished_at`       DATETIME(3)      NULL COMMENT '任务结束时间',
  `created_at`        DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  KEY `idx_model_database_sync_job_project_db_created` (`org_name`, `project_slug`, `database_id`, `created_at`),
  KEY `idx_model_database_sync_job_project_status` (`org_name`, `project_slug`, `status`),
  KEY `idx_model_database_sync_job_live_project` (`org_name`, `project_slug`, `deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据库同步为模型的异步任务表';

-- END FILE: db/schema/mysql/16_model_database.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/17_user_api_tokens.sql
-- ============================================================================
-- =============================================================================
-- End-User API Tokens (PAT)
-- 说明：
-- - 存储 EndUser 创建的 Personal Access Token（明文不落库，存 SHA-256 hash）
-- - token_hash UNIQUE 索引用于 O(1) 验证
-- - 软删除：deleted_at + delete_token 联合避让，支持撤销后同名重建
-- =============================================================================

CREATE TABLE IF NOT EXISTS `user_api_tokens` (
  `id`            VARCHAR(36)   NOT NULL COMMENT '唯一标识符 (UUID v7)',
  `org_name`      VARCHAR(255)  NOT NULL COMMENT '所属组织',
  `end_user_id`   VARCHAR(36)   NOT NULL COMMENT '创建者 EndUser ID',
  `name`          VARCHAR(255)  NOT NULL COMMENT '用户自定义名称',
  `token_hash`    VARCHAR(64)   NOT NULL COMMENT 'SHA-256(plaintext) hex，用于验证',
  `expires_at`    DATETIME      NULL     COMMENT 'NULL 表示永不过期',
  `last_used_at`  DATETIME      NULL     COMMENT '最近使用时间，异步更新',
  `created_at`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted_at`    BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间戳，0 表示活跃',
  `delete_token`  BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '唯一键避让位，0 表示活跃',

  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_token_hash` (`token_hash`),
  UNIQUE KEY `uq_user_token_name` (`org_name`, `end_user_id`, `name`, `delete_token`),
  KEY `idx_user_tokens` (`org_name`, `end_user_id`, `deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='EndUser Personal Access Token 注册表（PAT）';

-- END FILE: db/schema/mysql/17_user_api_tokens.sql

-- ============================================================================
-- BEGIN FILE: db/schema/mysql/18_model_sync_job.sql
-- ============================================================================
-- model_sync_job 表 SQL 定义
-- syncModelsFromDB 异步任务表（以 databaseName 为维度，独立于 model_database_sync_job）

CREATE TABLE IF NOT EXISTS `model_sync_job` (
  `id`               VARCHAR(36)  NOT NULL COMMENT '任务唯一标识符',
  `batch_id`         VARCHAR(36)  NOT NULL DEFAULT '' COMMENT '批次 ID，同批次多条 job 共享',
  `database_id`      VARCHAR(36)  NOT NULL DEFAULT '' COMMENT '关联 model_database.id',
  `org_name`         VARCHAR(64)  NOT NULL COMMENT '所属组织名称',
  `project_slug`     VARCHAR(64)  NOT NULL COMMENT '所属项目标识符',
  `database_name`    VARCHAR(128) NOT NULL COMMENT '目标数据库名称',
  `table_names`      JSON         NOT NULL COMMENT '指定同步的表名列表，空数组表示全量',
  `status`           ENUM('pending','running','succeeded','partial_success','failed') NOT NULL COMMENT '任务状态',
  `total_tables`     INT          NOT NULL DEFAULT 0 COMMENT '扫描到的总表数',
  `processed_tables` INT          NOT NULL DEFAULT 0 COMMENT '已处理表数',
  `created_models`   INT          NOT NULL DEFAULT 0 COMMENT '新建模型数',
  `synced_models`    INT          NOT NULL DEFAULT 0 COMMENT '已同步模型数',
  `failed_count`     INT          NOT NULL DEFAULT 0 COMMENT '失败表数',
  `failed_tables`    JSON         NOT NULL COMMENT '失败明细，格式：[{tableName, message}]',
  `started_at`       DATETIME(3)  NULL     COMMENT 'worker 开始时间',
  `finished_at`      DATETIME(3)  NULL     COMMENT '任务结束时间',
  `created_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',

  PRIMARY KEY (`id`),
  INDEX `idx_model_sync_job_project_db`   (`org_name`, `project_slug`, `database_name`, `created_at`),
  INDEX `idx_model_sync_job_status`       (`org_name`, `project_slug`, `status`),
  INDEX `idx_model_sync_job_batch`        (`org_name`, `project_slug`, `batch_id`),
  INDEX `idx_model_sync_job_database_id`  (`org_name`, `project_slug`, `database_id`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='syncModelsFromDB 异步任务表';

-- END FILE: db/schema/mysql/18_model_sync_job.sql

