// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../../../../tmp/tmp.StTzFIPitn
// gowrap: http://github.com/hexdigest/gowrap

package dbgenwrap

import (
	"context"
	"database/sql"
	"modelcraft/internal/infrastructure/dbgen"
	"modelcraft/internal/infrastructure/sqlerr"
	_sourceDbgen "modelcraft/internal/infrastructure/dbgen"
)

type SafeQuerier struct {
	delegate dbgen.Querier
}

var _ dbgen.Querier = (*SafeQuerier)(nil)

func NewSafeQuerier(delegate dbgen.Querier) dbgen.Querier {
	return &SafeQuerier{delegate: delegate}
}
func (s *SafeQuerier) ArchiveProject(ctx context.Context, arg _sourceDbgen.ArchiveProjectParams) (err error) {
	err = s.delegate.ArchiveProject(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CountActiveAPIKeysByUserID(ctx context.Context, userID string) (i1 int64, err error) {
	i1, err = s.delegate.CountActiveAPIKeysByUserID(ctx, userID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CountFieldsByModelID(ctx context.Context, modelID string) (i1 int64, err error) {
	i1, err = s.delegate.CountFieldsByModelID(ctx, modelID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CountMembershipsByUser(ctx context.Context, userID string) (i1 int64, err error) {
	i1, err = s.delegate.CountMembershipsByUser(ctx, userID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CountModels(ctx context.Context, arg _sourceDbgen.CountModelsParams) (i1 int64, err error) {
	i1, err = s.delegate.CountModels(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateDatabaseCluster(ctx context.Context, arg _sourceDbgen.CreateDatabaseClusterParams) (err error) {
	err = s.delegate.CreateDatabaseCluster(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateEnumDefinition(ctx context.Context, arg _sourceDbgen.CreateEnumDefinitionParams) (err error) {
	err = s.delegate.CreateEnumDefinition(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateFieldDefinition(ctx context.Context, arg _sourceDbgen.CreateFieldDefinitionParams) (err error) {
	err = s.delegate.CreateFieldDefinition(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateFieldEnumAssociation(ctx context.Context, arg _sourceDbgen.CreateFieldEnumAssociationParams) (err error) {
	err = s.delegate.CreateFieldEnumAssociation(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateLogicalForeignKey(ctx context.Context, arg _sourceDbgen.CreateLogicalForeignKeyParams) (err error) {
	err = s.delegate.CreateLogicalForeignKey(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateMembership(ctx context.Context, arg _sourceDbgen.CreateMembershipParams) (err error) {
	err = s.delegate.CreateMembership(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateModel(ctx context.Context, arg _sourceDbgen.CreateModelParams) (err error) {
	err = s.delegate.CreateModel(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateModelGroup(ctx context.Context, arg _sourceDbgen.CreateModelGroupParams) (err error) {
	err = s.delegate.CreateModelGroup(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateOrganization(ctx context.Context, arg _sourceDbgen.CreateOrganizationParams) (err error) {
	err = s.delegate.CreateOrganization(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreatePermission(ctx context.Context, arg _sourceDbgen.CreatePermissionParams) (err error) {
	err = s.delegate.CreatePermission(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateProject(ctx context.Context, arg _sourceDbgen.CreateProjectParams) (err error) {
	err = s.delegate.CreateProject(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateRole(ctx context.Context, arg _sourceDbgen.CreateRoleParams) (r1 sql.Result, err error) {
	r1, err = s.delegate.CreateRole(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateUser(ctx context.Context, arg _sourceDbgen.CreateUserParams) (err error) {
	err = s.delegate.CreateUser(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) CreateUserRole(ctx context.Context, arg _sourceDbgen.CreateUserRoleParams) (r1 sql.Result, err error) {
	r1, err = s.delegate.CreateUserRole(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteDatabaseCluster(ctx context.Context, arg _sourceDbgen.DeleteDatabaseClusterParams) (err error) {
	err = s.delegate.DeleteDatabaseCluster(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteEnum(ctx context.Context, arg _sourceDbgen.DeleteEnumParams) (err error) {
	err = s.delegate.DeleteEnum(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteExpiredRefreshTokens(ctx context.Context) (err error) {
	err = s.delegate.DeleteExpiredRefreshTokens(ctx)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteFieldEnumAssociation(ctx context.Context, arg _sourceDbgen.DeleteFieldEnumAssociationParams) (err error) {
	err = s.delegate.DeleteFieldEnumAssociation(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteFieldEnumAssociationsByModelID(ctx context.Context, modelID string) (err error) {
	err = s.delegate.DeleteFieldEnumAssociationsByModelID(ctx, modelID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteFieldsByModelID(ctx context.Context, modelID string) (err error) {
	err = s.delegate.DeleteFieldsByModelID(ctx, modelID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteFieldsByNames(ctx context.Context, arg _sourceDbgen.DeleteFieldsByNamesParams) (r1 sql.Result, err error) {
	r1, err = s.delegate.DeleteFieldsByNames(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteLogicalForeignKeyByPairID(ctx context.Context, pairID string) (err error) {
	err = s.delegate.DeleteLogicalForeignKeyByPairID(ctx, pairID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteMembership(ctx context.Context, id string) (err error) {
	err = s.delegate.DeleteMembership(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteModel(ctx context.Context, id string) (err error) {
	err = s.delegate.DeleteModel(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteModelGroup(ctx context.Context, id string) (err error) {
	err = s.delegate.DeleteModelGroup(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeletePermission(ctx context.Context, arg _sourceDbgen.DeletePermissionParams) (err error) {
	err = s.delegate.DeletePermission(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeletePermissionsByRole(ctx context.Context, roleID int64) (err error) {
	err = s.delegate.DeletePermissionsByRole(ctx, roleID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteRevokedAPIKeys(ctx context.Context) (err error) {
	err = s.delegate.DeleteRevokedAPIKeys(ctx)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteRole(ctx context.Context, id int64) (err error) {
	err = s.delegate.DeleteRole(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteUserRole(ctx context.Context, arg _sourceDbgen.DeleteUserRoleParams) (err error) {
	err = s.delegate.DeleteUserRole(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) DeleteUserRolesByRole(ctx context.Context, roleID int64) (err error) {
	err = s.delegate.DeleteUserRolesByRole(ctx, roleID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ExistsByPhone(ctx context.Context, phone string) (b1 bool, err error) {
	b1, err = s.delegate.ExistsByPhone(ctx, phone)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ExistsByUserName(ctx context.Context, name string) (b1 bool, err error) {
	b1, err = s.delegate.ExistsByUserName(ctx, name)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ExistsDatabaseClusterByProjectKey(ctx context.Context, arg _sourceDbgen.ExistsDatabaseClusterByProjectKeyParams) (i1 int64, err error) {
	i1, err = s.delegate.ExistsDatabaseClusterByProjectKey(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ExistsEnumByName(ctx context.Context, arg _sourceDbgen.ExistsEnumByNameParams) (i1 int64, err error) {
	i1, err = s.delegate.ExistsEnumByName(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ExistsFieldByName(ctx context.Context, arg _sourceDbgen.ExistsFieldByNameParams) (i1 int64, err error) {
	i1, err = s.delegate.ExistsFieldByName(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ExistsOrganizationByName(ctx context.Context, name string) (i1 int64, err error) {
	i1, err = s.delegate.ExistsOrganizationByName(ctx, name)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ExistsProjectBySlug(ctx context.Context, arg _sourceDbgen.ExistsProjectBySlugParams) (i1 int64, err error) {
	i1, err = s.delegate.ExistsProjectBySlug(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ExistsUserByExternalID(ctx context.Context, externalID sql.NullString) (i1 int64, err error) {
	i1, err = s.delegate.ExistsUserByExternalID(ctx, externalID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) FindFieldsByBelongsToFKID(ctx context.Context, belongsToFkID sql.NullString) (fa1 []_sourceDbgen.FindFieldsByBelongsToFKIDRow, err error) {
	fa1, err = s.delegate.FindFieldsByBelongsToFKID(ctx, belongsToFkID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) FindFieldsByRelateFKID(ctx context.Context, relateFkID sql.NullString) (fa1 []_sourceDbgen.FindFieldsByRelateFKIDRow, err error) {
	fa1, err = s.delegate.FindFieldsByRelateFKID(ctx, relateFkID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) FindIDByExternalID(ctx context.Context, externalID sql.NullString) (s1 string, err error) {
	s1, err = s.delegate.FindIDByExternalID(ctx, externalID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) FindLogicalForeignKeysByModelID(ctx context.Context, modelID string) (la1 []_sourceDbgen.LogicalForeignKey, err error) {
	la1, err = s.delegate.FindLogicalForeignKeysByModelID(ctx, modelID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) FindLogicalForeignKeysByPairID(ctx context.Context, pairID string) (la1 []_sourceDbgen.LogicalForeignKey, err error) {
	la1, err = s.delegate.FindLogicalForeignKeysByPairID(ctx, pairID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) FindLogicalForeignKeysByRefModelID(ctx context.Context, refModelID string) (la1 []_sourceDbgen.LogicalForeignKey, err error) {
	la1, err = s.delegate.FindLogicalForeignKeysByRefModelID(ctx, refModelID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) FindModelsByDeploymentStatus(ctx context.Context, statuses []sql.NullString) (ma1 []_sourceDbgen.Model, err error) {
	ma1, err = s.delegate.FindModelsByDeploymentStatus(ctx, statuses)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetAPIKeyByHash(ctx context.Context, keyHash string) (a1 _sourceDbgen.ApiKey, err error) {
	a1, err = s.delegate.GetAPIKeyByHash(ctx, keyHash)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetAPIKeyByID(ctx context.Context, id string) (a1 _sourceDbgen.ApiKey, err error) {
	a1, err = s.delegate.GetAPIKeyByID(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetAllModels(ctx context.Context) (ma1 []_sourceDbgen.Model, err error) {
	ma1, err = s.delegate.GetAllModels(ctx)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetDatabaseClusterByID(ctx context.Context, arg _sourceDbgen.GetDatabaseClusterByIDParams) (d1 _sourceDbgen.DatabaseCluster, err error) {
	d1, err = s.delegate.GetDatabaseClusterByID(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetDatabaseClusterByProjectKey(ctx context.Context, arg _sourceDbgen.GetDatabaseClusterByProjectKeyParams) (d1 _sourceDbgen.DatabaseCluster, err error) {
	d1, err = s.delegate.GetDatabaseClusterByProjectKey(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetEnumByID(ctx context.Context, id string) (m1 _sourceDbgen.ModelEnum, err error) {
	m1, err = s.delegate.GetEnumByID(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetEnumByName(ctx context.Context, arg _sourceDbgen.GetEnumByNameParams) (m1 _sourceDbgen.ModelEnum, err error) {
	m1, err = s.delegate.GetEnumByName(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetEnumReferencesByName(ctx context.Context, arg _sourceDbgen.GetEnumReferencesByNameParams) (ga1 []_sourceDbgen.GetEnumReferencesByNameRow, err error) {
	ga1, err = s.delegate.GetEnumReferencesByName(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetEnumsByNames(ctx context.Context, arg _sourceDbgen.GetEnumsByNamesParams) (ma1 []_sourceDbgen.ModelEnum, err error) {
	ma1, err = s.delegate.GetEnumsByNames(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetFieldByModelIDAndName(ctx context.Context, arg _sourceDbgen.GetFieldByModelIDAndNameParams) (f1 _sourceDbgen.FieldDefinition, err error) {
	f1, err = s.delegate.GetFieldByModelIDAndName(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetFieldEnumAssociationByField(ctx context.Context, arg _sourceDbgen.GetFieldEnumAssociationByFieldParams) (m1 _sourceDbgen.ModelFieldEnumAssociation, err error) {
	m1, err = s.delegate.GetFieldEnumAssociationByField(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetFieldEnumAssociationsByEnumName(ctx context.Context, arg _sourceDbgen.GetFieldEnumAssociationsByEnumNameParams) (ma1 []_sourceDbgen.ModelFieldEnumAssociation, err error) {
	ma1, err = s.delegate.GetFieldEnumAssociationsByEnumName(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetFieldEnumAssociationsByModelID(ctx context.Context, modelID string) (ma1 []_sourceDbgen.ModelFieldEnumAssociation, err error) {
	ma1, err = s.delegate.GetFieldEnumAssociationsByModelID(ctx, modelID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetFieldsByModelID(ctx context.Context, modelID string) (fa1 []_sourceDbgen.FieldDefinition, err error) {
	fa1, err = s.delegate.GetFieldsByModelID(ctx, modelID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetLogicalForeignKeyByID(ctx context.Context, id string) (l1 _sourceDbgen.LogicalForeignKey, err error) {
	l1, err = s.delegate.GetLogicalForeignKeyByID(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetMembershipByID(ctx context.Context, id string) (u1 _sourceDbgen.UserOrganization, err error) {
	u1, err = s.delegate.GetMembershipByID(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetMembershipByUserAndOrg(ctx context.Context, arg _sourceDbgen.GetMembershipByUserAndOrgParams) (u1 _sourceDbgen.UserOrganization, err error) {
	u1, err = s.delegate.GetMembershipByUserAndOrg(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetModelByID(ctx context.Context, id string) (m1 _sourceDbgen.Model, err error) {
	m1, err = s.delegate.GetModelByID(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetModelByName(ctx context.Context, arg _sourceDbgen.GetModelByNameParams) (m1 _sourceDbgen.Model, err error) {
	m1, err = s.delegate.GetModelByName(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetModelGroupByID(ctx context.Context, id string) (m1 _sourceDbgen.ModelGroup, err error) {
	m1, err = s.delegate.GetModelGroupByID(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetModelGroupByName(ctx context.Context, arg _sourceDbgen.GetModelGroupByNameParams) (m1 _sourceDbgen.ModelGroup, err error) {
	m1, err = s.delegate.GetModelGroupByName(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetOrganizationByName(ctx context.Context, name string) (o1 _sourceDbgen.Organization, err error) {
	o1, err = s.delegate.GetOrganizationByName(ctx, name)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetProjectByClusterID(ctx context.Context, arg _sourceDbgen.GetProjectByClusterIDParams) (p1 _sourceDbgen.Project, err error) {
	p1, err = s.delegate.GetProjectByClusterID(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetProjectBySlugAndOrg(ctx context.Context, arg _sourceDbgen.GetProjectBySlugAndOrgParams) (p1 _sourceDbgen.Project, err error) {
	p1, err = s.delegate.GetProjectBySlugAndOrg(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (r1 _sourceDbgen.RefreshToken, err error) {
	r1, err = s.delegate.GetRefreshTokenByHash(ctx, tokenHash)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetRoleByID(ctx context.Context, id int64) (r1 _sourceDbgen.Role, err error) {
	r1, err = s.delegate.GetRoleByID(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetRoleByName(ctx context.Context, name string) (r1 _sourceDbgen.Role, err error) {
	r1, err = s.delegate.GetRoleByName(ctx, name)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetRoleByNameAndOrg(ctx context.Context, arg _sourceDbgen.GetRoleByNameAndOrgParams) (r1 _sourceDbgen.Role, err error) {
	r1, err = s.delegate.GetRoleByNameAndOrg(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetSystemRoleByName(ctx context.Context, name string) (r1 _sourceDbgen.Role, err error) {
	r1, err = s.delegate.GetSystemRoleByName(ctx, name)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetTailFieldDisplayOrder(ctx context.Context, modelID string) (s1 string, err error) {
	s1, err = s.delegate.GetTailFieldDisplayOrder(ctx, modelID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetTailModelGroupDisplayOrder(ctx context.Context, arg _sourceDbgen.GetTailModelGroupDisplayOrderParams) (s1 string, err error) {
	s1, err = s.delegate.GetTailModelGroupDisplayOrder(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetUserByExternalID(ctx context.Context, externalID sql.NullString) (u1 _sourceDbgen.User, err error) {
	u1, err = s.delegate.GetUserByExternalID(ctx, externalID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetUserByID(ctx context.Context, id string) (u1 _sourceDbgen.User, err error) {
	u1, err = s.delegate.GetUserByID(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetUserByName(ctx context.Context, name string) (g1 _sourceDbgen.GetUserByNameRow, err error) {
	g1, err = s.delegate.GetUserByName(ctx, name)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetUserByPhone(ctx context.Context, phone string) (g1 _sourceDbgen.GetUserByPhoneRow, err error) {
	g1, err = s.delegate.GetUserByPhone(ctx, phone)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) GetUserRole(ctx context.Context, arg _sourceDbgen.GetUserRoleParams) (u1 _sourceDbgen.UserRole, err error) {
	u1, err = s.delegate.GetUserRole(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) InsertAPIKey(ctx context.Context, arg _sourceDbgen.InsertAPIKeyParams) (err error) {
	err = s.delegate.InsertAPIKey(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) InsertRefreshToken(ctx context.Context, arg _sourceDbgen.InsertRefreshTokenParams) (err error) {
	err = s.delegate.InsertRefreshToken(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) InsertSecurityAuditLog(ctx context.Context, arg _sourceDbgen.InsertSecurityAuditLogParams) (err error) {
	err = s.delegate.InsertSecurityAuditLog(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListAPIKeysByUserID(ctx context.Context, userID string) (aa1 []_sourceDbgen.ApiKey, err error) {
	aa1, err = s.delegate.ListAPIKeysByUserID(ctx, userID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListDatabaseClusters(ctx context.Context, arg _sourceDbgen.ListDatabaseClustersParams) (da1 []_sourceDbgen.DatabaseCluster, err error) {
	da1, err = s.delegate.ListDatabaseClusters(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListDatabaseClustersUpdatedAfter(ctx context.Context, arg _sourceDbgen.ListDatabaseClustersUpdatedAfterParams) (da1 []_sourceDbgen.DatabaseCluster, err error) {
	da1, err = s.delegate.ListDatabaseClustersUpdatedAfter(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListEnums(ctx context.Context, arg _sourceDbgen.ListEnumsParams) (ma1 []_sourceDbgen.ModelEnum, err error) {
	ma1, err = s.delegate.ListEnums(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListMembershipsByOrg(ctx context.Context, orgName string) (ua1 []_sourceDbgen.UserOrganization, err error) {
	ua1, err = s.delegate.ListMembershipsByOrg(ctx, orgName)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListMembershipsByUser(ctx context.Context, userID string) (ua1 []_sourceDbgen.UserOrganization, err error) {
	ua1, err = s.delegate.ListMembershipsByUser(ctx, userID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListMembershipsWithOrgDetails(ctx context.Context, arg _sourceDbgen.ListMembershipsWithOrgDetailsParams) (la1 []_sourceDbgen.ListMembershipsWithOrgDetailsRow, err error) {
	la1, err = s.delegate.ListMembershipsWithOrgDetails(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListMembershipsWithUserName(ctx context.Context, orgName string) (la1 []_sourceDbgen.ListMembershipsWithUserNameRow, err error) {
	la1, err = s.delegate.ListMembershipsWithUserName(ctx, orgName)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListModelGroupsByProject(ctx context.Context, arg _sourceDbgen.ListModelGroupsByProjectParams) (ma1 []_sourceDbgen.ModelGroup, err error) {
	ma1, err = s.delegate.ListModelGroupsByProject(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListModels(ctx context.Context, arg _sourceDbgen.ListModelsParams) (ma1 []_sourceDbgen.Model, err error) {
	ma1, err = s.delegate.ListModels(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListOrganizationsByUser(ctx context.Context, userID string) (oa1 []_sourceDbgen.Organization, err error) {
	oa1, err = s.delegate.ListOrganizationsByUser(ctx, userID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListPermissionsByRole(ctx context.Context, roleID int64) (ra1 []_sourceDbgen.RolePermission, err error) {
	ra1, err = s.delegate.ListPermissionsByRole(ctx, roleID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListPermissionsByRoleAndOrg(ctx context.Context, arg _sourceDbgen.ListPermissionsByRoleAndOrgParams) (ra1 []_sourceDbgen.RolePermission, err error) {
	ra1, err = s.delegate.ListPermissionsByRoleAndOrg(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListProjects(ctx context.Context) (pa1 []_sourceDbgen.Project, err error) {
	pa1, err = s.delegate.ListProjects(ctx)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListProjectsByOrg(ctx context.Context, orgName string) (pa1 []_sourceDbgen.Project, err error) {
	pa1, err = s.delegate.ListProjectsByOrg(ctx, orgName)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListRoleUsers(ctx context.Context, arg _sourceDbgen.ListRoleUsersParams) (ua1 []_sourceDbgen.UserRole, err error) {
	ua1, err = s.delegate.ListRoleUsers(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListRoles(ctx context.Context) (ra1 []_sourceDbgen.Role, err error) {
	ra1, err = s.delegate.ListRoles(ctx)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListRolesByOrg(ctx context.Context, orgName string) (ra1 []_sourceDbgen.Role, err error) {
	ra1, err = s.delegate.ListRolesByOrg(ctx, orgName)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListRolesByOrgIncludeSystem(ctx context.Context, orgName string) (ra1 []_sourceDbgen.Role, err error) {
	ra1, err = s.delegate.ListRolesByOrgIncludeSystem(ctx, orgName)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) ListUserRoles(ctx context.Context, arg _sourceDbgen.ListUserRolesParams) (ua1 []_sourceDbgen.UserRole, err error) {
	ua1, err = s.delegate.ListUserRoles(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) RevokeAPIKey(ctx context.Context, arg _sourceDbgen.RevokeAPIKeyParams) (err error) {
	err = s.delegate.RevokeAPIKey(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) RevokeAllRefreshTokensByUserID(ctx context.Context, userID string) (err error) {
	err = s.delegate.RevokeAllRefreshTokensByUserID(ctx, userID)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) RevokeRefreshToken(ctx context.Context, id string) (err error) {
	err = s.delegate.RevokeRefreshToken(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateAPIKey(ctx context.Context, arg _sourceDbgen.UpdateAPIKeyParams) (err error) {
	err = s.delegate.UpdateAPIKey(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateAPIKeyLastUsed(ctx context.Context, id string) (err error) {
	err = s.delegate.UpdateAPIKeyLastUsed(ctx, id)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateDatabaseClusterWithVersion(ctx context.Context, arg _sourceDbgen.UpdateDatabaseClusterWithVersionParams) (r1 sql.Result, err error) {
	r1, err = s.delegate.UpdateDatabaseClusterWithVersion(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateEnum(ctx context.Context, arg _sourceDbgen.UpdateEnumParams) (err error) {
	err = s.delegate.UpdateEnum(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateField(ctx context.Context, arg _sourceDbgen.UpdateFieldParams) (r1 sql.Result, err error) {
	r1, err = s.delegate.UpdateField(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateFieldDisplayOrder(ctx context.Context, arg _sourceDbgen.UpdateFieldDisplayOrderParams) (err error) {
	err = s.delegate.UpdateFieldDisplayOrder(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateFieldsStatus(ctx context.Context, arg _sourceDbgen.UpdateFieldsStatusParams) (err error) {
	err = s.delegate.UpdateFieldsStatus(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateMembership(ctx context.Context, arg _sourceDbgen.UpdateMembershipParams) (err error) {
	err = s.delegate.UpdateMembership(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateModel(ctx context.Context, arg _sourceDbgen.UpdateModelParams) (r1 sql.Result, err error) {
	r1, err = s.delegate.UpdateModel(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateModelDeploymentStatus(ctx context.Context, arg _sourceDbgen.UpdateModelDeploymentStatusParams) (err error) {
	err = s.delegate.UpdateModelDeploymentStatus(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateModelGroup(ctx context.Context, arg _sourceDbgen.UpdateModelGroupParams) (err error) {
	err = s.delegate.UpdateModelGroup(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateModelWithVersion(ctx context.Context, arg _sourceDbgen.UpdateModelWithVersionParams) (r1 sql.Result, err error) {
	r1, err = s.delegate.UpdateModelWithVersion(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateModelsGroupID(ctx context.Context, arg _sourceDbgen.UpdateModelsGroupIDParams) (err error) {
	err = s.delegate.UpdateModelsGroupID(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateOrganization(ctx context.Context, arg _sourceDbgen.UpdateOrganizationParams) (err error) {
	err = s.delegate.UpdateOrganization(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateProject(ctx context.Context, arg _sourceDbgen.UpdateProjectParams) (err error) {
	err = s.delegate.UpdateProject(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
func (s *SafeQuerier) UpdateRole(ctx context.Context, arg _sourceDbgen.UpdateRoleParams) (err error) {
	err = s.delegate.UpdateRole(ctx, arg)
	sqlerr.WrapSQLErrorInPlace(&err)
	return
}
