PORT: "80"
FRONTEND_URL: "<your-cloudrun-frontend-domain>"
BACKEND_UPSTREAM: "backend:80"
AGENT_UPSTREAM: "agent:80"
JWT_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExhyKJmlGOYsCV1OV1ZF1yhVuPwcd\nL38DeWGLWil9mK+2nEzDbwLYWnDMZRlNTDRWDBtfIOPQ2F5FKuKlTBTZew==\n-----END PUBLIC KEY-----"
OTEL_EXPORTER_OTLP_ENDPOINT: ""
TZ: "Asia/Shanghai"
