server:
  port: "80"
  mode: "release"

database:
  type: "mysql"
  host: "172.17.0.11"
  port: 3306
  username: "admin"
  password: "Modelcraft123"
  database: "modelcraft"
  charset: "utf8mb4"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600
  log_level: "info"
  migrate_on_startup: true

redis:
  host: "localhost"
  port: 6379
  password: ""

jwt:
  secret: "7f687b4450fbd9efb567f0e211f3eae2302e52d69086d9dcc3c374fd5fd192e6"
  private_key: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIExV1xYZQMvx0rDvpFtLV55SrcDq+p9S9boAuA5xrefaoAoGCCqGSM49\nAwEHoUQDQgAExhyKJmlGOYsCV1OV1ZF1yhVuPwcdL38DeWGLWil9mK+2nEzDbwLY\nWnDMZRlNTDRWDBtfIOPQ2F5FKuKlTBTZew==\n-----END EC PRIVATE KEY-----"
  expiration: 21600s
  issuer: "modelcraft"

auth:
  cookie:
    domain: ""
    secure: true
    same_site: "lax"
  design:
    jwt_public_key_path: ""
    jwt_public_key: ""
    accept_modelcraft_jwt: true
  runtime:
    optional_for_projects: []

crypto:
  aes_key: "f60bd580d4196e40094c8a561366ef30cdbdf34146c95708108008e25cbb1ab4"

logger:
  level: "info"
  output_path: "stdout"
  max_size: 100
  max_backups: 10
  max_age: 7
  compress: true
